### ISSUE TITLE
ETQ profil superviseur je peux extraire des données

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1000]
ETQ profil superviseur, je peux solliciter **une extraction** sur une période données, 

L'issue est terminée lorsque ETQ superviseur, je peux extraire sous la forme d'un tableur, pour ma ou mes caisses, les données suivantes  :

- [ ]   N°demande
- [ ]  libellé de la CPAM
- [ ]  région de la CPAM
- [ ]   date de naissance bénéficiaire
- [ ]   statut de la demande
- [ ]   demande "en cours d'étude" (Y/N)
- [ ]   date de demande
- [ ]  signalement assuré (Y/N)
- [ ]  signalement technicien (Y/N)
- [ ]   Nombre de trajet
- [ ]   VP (Y/N)
- [ ]   ATP (Y/N)
- [ ]   Assurée a basculé
- [ ]   nombre Km
- [ ]   montant frais de parking
- [ ]  montant total des frais de VP
- [ ]   montant total remboursement VP
- [ ]   montant total ATP
- [ ]   cout théorique taxi
- [ ]   motif de rejet
- [ ]   motif de contact

le bouton d'export des données est positionné sur la page demande pour pouvoir utiliser les filtres existants

https://www.mrs.beta.gouv.fr/admin/mrsrequest

A placer sous les filtres

**Comment by Johan1983** [comment]
Investiguer les modales actuellement en place

> le faire en export classique csv

**Comment by fb86** [comment]
remplacer l'export csv par un export excel
