### ISSUE TITLE
Profil superviseur réparer le filtre par caisse et agen 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1001]

**Comment by jpic** [comment]
J'aimerai plus de details sur cette issue (mais pour les autres elles sont relues et acceptées ;) )

**Comment by fb86** [comment]
Ca fait suite au retour de la cpam de moselle qui voyait, avec lz profil superviseur, l ensemble des cpam et des agents upn de France.... J ai pas eu le temps de reproduire donc piur l instant je garde en suspen




Télécharger Outlook pour Android







On Thu, Apr 18, 2019 at 12:40 PM +0200, "∞" <notifications@github.com> wrote:












J'aimerai plus de details sur cette issue (mais pour les autres elles sont relues et acceptées ;) )

**Comment by jpic** [comment]
Sur quelle URL merci.
