### ISSUE TITLE
ETQ profil superviseur, je peux accéder aux détails des contacts et des gabarits pour mon ou mes départements.

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1019]
Depuis https://github.com/betagouv/mrs/issues/998, le profil superviseur permet d’accéder à certains informations. toutefois,
-[ ] l’accès aux détails des contacts par département ne fonctionne pas ,
-[ ] le profil superviseur a bien accès au détail de gabarit par utilisateur mais pas au détail au niveau de son ou ses départements.

US terminée lorsque le profil  superviseur permet de visualiser le détail des contacts et des gabarits pour le département,

**Comment by jpic** [comment]
Je ne comprends pas tres bien, je viens de créer un utilisateur de test en STAGING, login/mdp: superviseur/superviseur

Quand je vais dans Gabarits, j'ai bien un champs de selection des caisses qui me sont affectées, ainsi que la liste des utilisateurs correspondants.

De meme, pour les contacts cela me semble fonctionnel en staging.

Est-ce-que cette issue correspond au bugfix que j'ai mis en staging la semaine derniere et qui n'avait pas d'issue ?

L'issue est-elle toujours d'actualité en staging ?

Merci

**Comment by fb86** [comment]
Oui, 


il manque juste le fait de pouvoir trier par département lorsque le superviseur à un profil sur plusieurs département à la fois

**Comment by fb86** [comment]
fonction développé sur 1er issue
