### ISSUE TITLE
Ergonnomie modale de contact et rejet

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#1030]
Actuellement, la modale de Contact et Rejet de demande s'ouvrent en bas de la page, sans bordure de contours, sur toute la largeur, avec les boutons "Annuler" et "Valider" en bas à gauche.

- [ ] Centrer la modale qui est actuellement sur toute la largeur
- [ ] Placer les boutons de manière ergonnomique standard: en bas à droite validation (actuellement impossible car la modale étant sur toute la largeur il y a un overlap avec les floating action), et en bas à gauche l'annulation
- [ ] Ajouter une croix en haut à droite pour la fermeture
- [ ] Ajouter une bordure de contours (material design)

**Comment by jpic** [comment]
en staging

**Comment by fb86** [comment]
Valider pour nous
