### ISSUE TITLE
Reviser la selection de la CPAM

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1032]
Aujourd'hui, un assurée peut choisir sa caisse à partir d'un menu déroulant. 

![liste caisses](https://user-images.githubusercontent.com/34480111/59679732-ebb0c880-91cf-11e9-9b00-db62bd5840d5.JPG)
Les CPAM ne sont pas l'état regroupé en région.

L'issue est terminée lorsque l'assuré peut choisir sa caisse sous un menu déroulant par région.

Liste des régions actives
Auvergne-Rhône-Alpes
Bourgogne-Franche-Comté
Bretagne (Aucune CPAM actives à ce jour pour la région donc choix de la région non visible)
Centre-Val de Loire (Aucune CPAM actives à ce jour pour la région donc choix de la région non visible)
Corse (Aucune CPAM actives à ce jour pour la région donc choix de la région non visible)
Grand Est
Hauts-de-France (Aucune CPAM actives à ce jour pour la région donc choix de la région non visible)
Île-de-France
Normandie
Nouvelle-Aquitaine
Occitanie
Pays de la Loire
Provence-Alpes-Côte d'Azur
Autres

Puis liste des CPAM actives associées à la région

ex Pays de la loire
 - CPAM de la Vendée
-  Autres 

le choix Autres renvoi sur la page de contact dès que défini sur la fonction précédente.

**Comment by sebroussel** [comment]
@fb86 Lorsque l'on clique sur "Autres", on aboutit au formulaire permettant de collecter le besoin de l'assuré pour le prévenir lorsque sa caisse ouvrira dans MRS. 

Aujourd'hui ce formulaire a deux listes déroulantes :

- Votre caisse de rattachement
- Votre régime d'Assurance Maladie

Doit-on rajouter une liste déroulante "Votre région" composée de toutes les régions topées comme "inactives", pour permettre à l'assuré de filtrer sa caisse de rattachement ?

**Comment by fb86** [comment]
@sebroussel oui effectif, je te liste les cpam pas region (ca c pas dure) mais également les regimes spéciaux.

**Comment by sebroussel** [comment]
@fb86 du coup pour bien comprendre, dans l'hypothèse où on a : 

- Une région "Régimes spéciaux", qui regroupe les caisses des régimes spéciaux
- Une région "Pays-de-la-Loire" où seule la CPAM de Loire-Atlantique est active, mais pas les autres

Si l'utilisateur sélectionne la région "Pays de la Loire", puis dans la liste des Caisses il sélectionne "Autres", l'application doit afficher toutes les caisses inactives de la région "Pays-de-la-Loire" ET toutes les caisses des Régimes spéciaux ?

Du coup dans ce cas précis on afficherait pas uniquement les caisses "filles" de la région concernée mais également les caisses des régimes spéciaux ?

**Comment by fb86** [comment]
Oui c est tout à fait cela.

Si par contre dans l hypothèse ou il selectionne directement autre, il faudra faire apparaitre les regions où il n y a aucune cpam actives + regimes spéciaux. 

A terme, lorsque toutes les regions auront ouvertes avec au moins un departement actif, il ne faudra plus affiché que les regimes speciaux si l utilisateur choisi directement autres dans la liste des régions
