### ISSUE TITLE
Indicateur d'erreur

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#104]
Lorsque la soumission est en erreur, re-soumettre automatiquement, tout en gardant l'indicateur de chargement (#103), ajouter un message comme quoi une erreur est survenue et qu'une nouvelle soumission est automatiquement en cours: qu'il faut laisser la page ouverte jusqu'à reception du message de succès de la soumission.

**Comment by tbinetruy** [comment]
On it ! ;)
