### ISSUE TITLE
ETQ adm je peux affecter une CPAM à une région

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1040]
Aujourd'hui les CPAM ne sont identifé que par leur département de rattachement,

l'issue est terminée lorsque le profil admin peut affecter à une CPAM une ou plusieurs régions de référence (choix sur menu déroulant, avec stockage de l'info). Il peut également modifier cette région à tout moment. 

liste des régions + "Régimes Particuliers"

https://www.mrs.beta.gouv.fr/admin/caisse?active=2

A ajouter sur la page ci dessous entre le nom et le mail

![fiche caisse](https://user-images.githubusercontent.com/34480111/59766905-7dd4d180-92a1-11e9-963f-6fe8d8b2c91f.JPG)

en lien préalable à https://github.com/betagouv/mrs/issues/1032

**Comment by jpic** [comment]
C'est quel genre de cas dans lesquels on a besoin de mettre plusieurs regions dans une caisse svp ?

**Comment by sebroussel** [comment]
Cas des MSA qui sont transrégionales : MSA Sud peut couvrir N régions du sud de la France par exemple.

**Comment by jpic** [comment]
Merci, pk pas mettre MSA Sud dans la region Regimes Particuliers ?

**Comment by fb86** [comment]
In souhaite réservé la notion de regime particulier au regimes particulier qui couvre l ensemble de la france, sans decoupage locale. Par exemple le régime de l assemblé nationale, des clercs et notaires, des cultes,.... La msa se decoupe en une 30 aine de sous ententie a travers la france. La plupart sont calqués sur une partie des decoupages des ex region mais pour certaines sa couvre 2 regions avec le redecoupage des regions.

**Comment by jpic** [comment]
Ce que je demande c'est si l'utilisateur va chercher MSA Sud dans Regime Speciaux ou si il cherchera sa Region en se disant que MSA Sud couvre plusieurs Regions.

**Comment by sebroussel** [comment]
Je pense qu'il cherchera sa MSA dans la région Occitanie.

Donc il commencera par sélectionner la région Occitanie dans la première liste déroulante, les caisses associées à la région Occitanie vont être remontées dans la liste déroulante suivante, et il cherchera dans celle-ci l'item MSA correspondant à sa caisse, en l'occurence MSA Sud.

S'il passait par "Régimes spéciaux", il aurait le choix entre MSA Nord / Ouest / Sud / Est, et s'il habite le centre de la France, ça peut être source d'erreurs.
