### ISSUE TITLE
bug navigateur edge

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1043]
Je n'ai pas pu reproduire, je vous fais part d'une demande d'un assuré:
``` Motif: J'ai une idée d'amélioration pour votre site
**Caisse: CPAM de la Manche**
Nom: BONAMY
Email: bonamy.isa@orange.fr
**Message:**
Bonjour, la sélection d'un jour sur le calendrier ne fonctionne pas sur le navigateur Microsoft Edge 42.17134.1.0. Cordialement ```

**Comment by notmoebius** [comment]
Avez-vous un moyen de tester avec cette version de navigateur ? Il semble d'après son message que le datepicker ne fonctionnerait pas bien avec Edga.

**Comment by jpic** [comment]
Il n'y a pas de datepicker sur le frontend ... C'est le navigateur qui l'implemente si il en a !
C'est ce qui permet notamment un meilleur support des mobiles.
