### ISSUE TITLE
Intégration HTML landing page campagne pub Linkedin

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#1045]
Nous allons mettre en place une campagne pub sur Linkedin (Quizz) renvoyant vers un landing page.
Du coup, nous avons besoin d'une landing page spécifique Professionnels de santé.
URL à définir (par exemple/PRO).

Nous allons réaliser la maquette sous Figma, nous vous fournirons le HTML et le CSS mais un peu de code serait à prévoir.

**Comment by Johan1983** [comment]
![LANDING PAGE MRS PRO](https://user-images.githubusercontent.com/34479425/60577336-6f95b380-9d7f-11e9-8708-28a6a6d42e5f.png)

maquette réalisé sous Figma, je vois pour le passage dans Adobe XD pour faciliter l'integration

**Comment by Johan1983** [comment]
La cible est mrs.beta.gouv.fr/pro

Les métriques d'utilisations doivent être dynamiques (à partir de la page stats de mrs)

**Comment by jeanbaptistemora** [comment]
Intégration terminée, en attente de la MEP avant de passer la démo en staging.
