### ISSUE TITLE
etq ADMIN DROIT LOCAL je peux faire évoluer les droits des techniciens de ma caisse

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1049]
Aujourd'hui les profils upn, stat et support sont données par les admin.
Il  n y a pas de profl admin locam permettant de gerer les profils des techniciens en local. 
L issue est terminée avec la creation d un profil admi local permettant au admin local de données des droits au techniciens de son département

**Comment by notmoebius** [comment]
Cette issue fonctionne avec le profil Superviseur. Pour des raisons de sécurité, il faut créer un groupe admin-local qui peut uniquement gérer les utilsiateurs:
- créer un utilisateur
- modifier son profil/groupe
- reset un password
- afficher le détail d'un utilisateur
il ne peut pas devenir un utilisateur, ni consulter les données MRS.

**Comment by jpic** [comment]
Attention: Si il peut creer un utilisateur alors il peut le devenir ! Il suffit qu'il mette son propre email ;)

**Comment by notmoebius** [comment]
On a des mécanismes d'audit et de contrôle. Nous avons déjà ces cas de figures donc oui, le risque est calculé. Merci pour l'alerte.

**Comment by jpic** [comment]
Ok et pour les superviseurs on laisse comme c'est ou alors est-ce-qu'on enlève des droits ?
