### ISSUE TITLE
Indiquer les fichiers téléchargés en erreur

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#105]
Dans le formulaire de saisie, l'ajour d'un fichier autre qu'une image ou ayant un volume trop important ne provoque pas d'affichage d'avertissement ou d'erreur.

![mes remboursements simplifies - google chrome_2018-01-22_09-32-32](https://user-images.githubusercontent.com/32330644/35212766-8470795c-ff5b-11e7-8ced-90a3e053854e.png)
![mes remboursements simplifies - google chrome_2018-01-22_09-32-17](https://user-images.githubusercontent.com/32330644/35212787-969a93ce-ff5b-11e7-8dd7-0e90d891dab3.png)

après avoir cliquer sur Soumettre:
![mes remboursements simplifies - google chrome_2018-01-22_09-45-12](https://user-images.githubusercontent.com/32330644/35212800-a42d704c-ff5b-11e7-9680-acc6ce289d47.png)
![mes remboursements simplifies - google chrome_2018-01-22_09-45-23](https://user-images.githubusercontent.com/32330644/35212807-a9b5a8d6-ff5b-11e7-9b02-784f63bbfbf0.png)

**Comment by notmoebius** [comment]
Propositions:
- si le fichier est trop volumineux: "Taille du fichier transmis doit être inférieur à 10 Mo"
- si le format de fichier est incorrecte: "les formats de  fichier acceptés sont: jpg, png, pdf, `(...reprendre la lsite du dev)`"

**Comment by jpic** [comment]
https://stackoverflow.com/a/20260869

**Comment by notmoebius** [comment]
Effectivement, le stackoverflow est instructif.

J'ai vu que dans mrs/src/mrs/static/js/upload.js il y a bien des messages mais dans les faits, ils n'apparaissent pas.
On se tient ua courant des updates/fix à faire.

**Comment by jpic** [comment]
On va pas sembeter et rajouter un check avant le data.submit() dans notre callback add()

**Comment by jpic** [comment]
Fix en cours de déploiement staging.
![mrs-form-error](https://user-images.githubusercontent.com/94636/35265503-8f855d7e-0020-11e8-8d47-46b7732a2c37.png)
