### ISSUE TITLE
Nouvelle FAQ à ajouter

### ISSUE THREAD

**Issue by Natacha1974** [betagouv/mrs#107]
Qu'est-ce que des transports itératifs ?

Les transports itératifs sont des transports réguliers, fréquents et de proximité, de distance identique (même lieu de départ, même lieu d'arrivée). Le nombre de transports itératifs est défini par le médecin sur la prescription médicale de transport. 

Le transport en série est un transport itératif particulier qui nécessite une Demande d'Accord Préalable (DAP). Il correspond à au moins 4 transports de plus de 50 kilomètres aller, sur une période de 2 mois, au titre d'un même traitement. A ce stade, les demandes de remboursement via une DAP ne sont pas **encore** possibles, ce sera l'objet d'une prochaine version.

**Comment by notmoebius** [comment]
Mises à jour faite, en attente de pullrequest

**Comment by jpic** [comment]
Bravo @notmoebius on a mit en prod ce matin
