### ISSUE TITLE
Accès impossible à la base école

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1075]
les liens https://ecole.mrs.beta.gouv.fr/  et https://ecole.mrs.beta.gouv.fr/admin ne fonctionnent plus. Sous Chrome, il m'affiche:
![image](https://user-images.githubusercontent.com/32330644/63507806-deb69b00-c4d8-11e9-93a6-8729d7451062.png)

Peut-être un problème de certificat.
Sous IE11, j'ai en plus une erreur 404 si je force.

**Comment by jpic** [comment]
L'instance ecole est de retour, le serveur de mail : https://mailcatcher.ecole.mrs.beta.gouv.fr/

**Comment by notmoebius** [comment]
Oui c'est okpour l'accès
