### ISSUE TITLE
BUG - le bouton action sur une demande n'est activable (IE11)

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1076]
L'accès a été rétabli et fonctionne. Les identifiants sont ok après tests.

Il reste une scorie: sous IE11 uniquement, le menu "hamburger" sur une demande ne s'active plus.
En conséquence, les actions ne s'affichent plus et donc les formateurs ne peuvent plus montrer les fonctions du menu.

J'ai testé sous Chrome Version 76.0.3809.100 et Firefox 68.0.2 et cela fonctionne correctement.

**Comment by notmoebius** [comment]
Un pbl js ?

**Comment by jpic** [comment]
Oui, est-ce-que tu peux nous mettre un screenshot de l'erreur en console IE11 stp ?

Mon windows n'est pas fonctionnel a ce moment

**Comment by jpic** [comment]
Fixé en staging
