### ISSUE TITLE
BUG Calcul du km en décimal

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1084]
- [x] Suite à l'issue #1007 il faudrait faire un calcul de la division au dixième.
Exemple pour une division: 5 A/R pour une distance de 99km, il faut par trajet A/R afficher 19.9 km et non la partie entière.
- [x] Dans le placeholder, mettre "Indiquer le nombre de km parcourus lors de vos x trajets aller-retour" en cas de plusieurs trajets a/r, "Indiquer le nombre de km parcourus lors de vos x trajets aller simple" en cas de plusieurs trajets allers simples, "Indiquer le nombre de km parcourus lors de votre trajet aller-retour" en cas de trajet unique AR, "Indiquer le nombre de km parcourus lors de votre aller simple" en cas de trajet unique aller simple, 
- [x]  Enlever "Attention: Motif de rejet fréquent !" et "Par exemple..."
- [x]  Modifier "Votre déclaration..." par "Votre déclaration correspond  à une moyenne de xxx.y km par trajet A/R"  avec la même police et font sauf le nb de km en gras.

En cas de trajet unique, on masque le bloc.

**Comment by sebroussel** [comment]
Fait référence à la PR #1082

**Comment by jpic** [comment]
> Enlever "Attention: Motif de rejet fréquent !" et "Par exemple..."

Je trouve dommage de ne pas alerter l'utilisateur sur le fait qu'on essaye de faire baisser ce taux de motifs de rejets

**Comment by jpic** [comment]
"par A/R" il est possible que "aller + retour" sera plus clair pour une partie de la population

**Comment by jpic** [comment]
Neanmoins j'ai integré les changements demandés sur http://distancevp-preview.test.staging.mrs.beta.gouv.fr/demande
