### ISSUE TITLE
ETQ admin local, je peux visualiser l'ensemble des utilisateurs des caisses

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1085]
Fini quand un admin local peut consulter un agent d'un autre organisme dans le cas des activités mutualisées entre plusieurs caisses.

**Comment by sebroussel** [comment]
@notmoebius @fb86 l'admin local peut-il consulter les agents d'autres organismes ayant le profil admin local ? (et donc leur affecter des droits sur sa caisse ?)

**Comment by fb86** [comment]
Oui




Télécharger Outlook pour Android







On Wed, Sep 25, 2019 at 5:37 PM +0200, "Sébastien Roussel" <notifications@github.com> wrote:












@notmoebius @fb86 l'admin local peut-il consulter les agents d'autres organismes ayant le profil admin local ? (et donc leur affecter des droits sur sa caisse ?)
