### ISSUE TITLE
supprimer la possibilité d'indiquer une CPAM "autre" dans le formulaire de la page Contact

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1087]
Aujourd'hui, dans le formulaire contact, un assuré peut selectionné comme CPAM 'autre".

L'issue est terminée lorsque l'assuré ne peut plus selectionner "autre" comme CPAM

**Comment by fb86** [comment]
@sebroussel peux tu me donner le lien pour tester ? merci

**Comment by sebroussel** [comment]
@fb86 https://www.newcontactform.test.staging.mrs.beta.gouv.fr/contact

**Comment by fb86** [comment]
ok pour moi, RAS au regard des tests
