### ISSUE TITLE
Modifier adresse mail envoi accusé de reception, validation, rejet et contact

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1089]
Aujourd'hui lorsqu'on adresse un mail lors du traitement d'une demande (mail d'accusé reception d'une demande, mail de rejet, mail de contact, mail de validation) le mail est envoyé depuis l'adresse mail contact@mrs.beta.gouv.fr.

Lorsque les assurés répondent à ce mail, le mail arrive sur la boite au lettre mrs.cpam-toulouse@assurance-maladie.fr

l'issue est terminée lorsque le mail de reponse fait par l assure part sur l'adresse de messagerie de la CPAM ayant traitée le dossier.

**Comment by fb86** [comment]
@notmoebius peux tu valider avant de mettre en to do ?

**Comment by jpic** [comment]
Je precise: on ne peut pas faire partir le mail depuis la CPAM sans que ca ne soit consideré comme SPAM ou qu'on puisse faire des changements sur la zone DNS des expediteurs. 

Par contre on peut utiliser le mail de la caisse dans le Reply-To du mail envoyé facilement.

**Comment by fb86** [comment]
@jpic cela signifie que les mails partent de contact mais que les reponses a ces mails arriveront sur l adresse mail de la cpam de l assuré ?

**Comment by fb86** [comment]
on a voulu tester sur la branche.
une erreur 500 lorsque qu 'on clique sur détail de la demande, donc impossible de faire un mail de rejet ou contact.

Test ok à partir de la page de contact et demande

**Comment by fb86** [comment]
test ok à partir d'une nouvelle demande; le routage de mail est ok

reste problème du renvoi de l'erreur sur demande 201805020001 et 201810310000

**Comment by sebroussel** [comment]
@fb86 effectivement il y a bien une erreur 500 sur les "anciennes" demandes de test sur cette branche ainsi que sur les autres branches générées par la CI.

L'erreur renvoyée est "No such file or directory: '/mrsattachments/1x1.png'" : il manque pour ces demandes la pièce-jointe fictive 1x1.png associée, il ne peut donc pas afficher la demande. Je crée une issue pour ce bug.

**Comment by sebroussel** [comment]
OK le bug des erreurs 500 (pour pièce-jointe image 1x1.png manquante) est désormais résolu sur cette branche (et le sera sur toutes les autres branches de test une fois mergée sur master), merci à @jeanbaptistemora pour son aide !

**Comment by fb86** [comment]
test positif sur l'envoi des mails lors de la création d'un utilisateur ou la réinitialisation d'un mot de passe.   Ok pour mise en prod dès qu'on aura résolu le problème des BAL CPAM.
