### ISSUE TITLE
BUG pas de visualisation des stats pour les utilisateur multi-profil

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1101]
Bonjour,

l'utilisateur VANDERDONCKT  de la CPAM de l'Isère n'arrive pas à consulter les stats. Elle a bien le profil mais les chiffres sont à 0:

J'ai testé avec mon profil et j'ai bien des données:

Si je prend un utilisateur qui a uniquement le profil Stats, c'est OK.

Si je prend un utilisateur qui a plusieurs profil (UPN+Stat), c'est KO, rien ne s'affiche.

C'est peut-être normal mais cela m'a échappé si tel est le cas.
Exemple que j'ai testé:

**Comment by sebroussel** [comment]
@notmoebius cela devrait être résolu avec la PR https://github.com/betagouv/mrs/pull/1091 de James, qui n'est pas encore en prod.

**Comment by jpic** [comment]
@notmoebius est-ce bien resolu ?
