### ISSUE TITLE
BUG - erreur sur la sélection d'une région

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1103]
sur la saisie du formulaire, une fois la région choisie, certaines régions affiches des département fantaisistes. Par exemple, la région Corse affiche:
![image](https://user-images.githubusercontent.com/32330644/66384746-99cec100-e9bf-11e9-9955-426dde0a11fc.png)

Nous allons vérifié le régions qui bug.

Régions KO:
- [ ] Auvergne Rhone alpes
- [ ] Centre-val de loire
- [ ] Corse
- [ ] Grand Est

**Comment by sebroussel** [comment]
OK le problème vient du fait que pour afficher ou masquer une caisse dans la liste déroulante, on utilise un indexOf sur l'attribut région pour déterminer si l'identifiant de la région sélectionnée s'y trouve.
Dans le cas des 3 régions sélectionnées, les identifiants concernés sont 4/5/6, et indexOf a renvoyé les identifiants 14/15/16 comme positifs (car 4, 5 et 6 sont bien présents dans la chaine de caractère), et donc affiché les caisses des régions 14/15/16.
Je modifie donc cet indexOf pour qu'il découpe au préalable les ids correctement, et qu'il vérifie la présence sur les identifiants dans leur ensemble et pas uniquement sur la chaîne de caractère.
