### ISSUE TITLE
ANOMALIE pbl d'affichage des régions sur iphone

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1107]
Lorsque l’on utilise un IPHONE pour entrer sur le site nous n’arrivons pas à sélectionner notre région. Si nous sélectionnons une région elle se modifie automatiquement ce qui rend l’utilisation de l’outil impossible.
L’information m’a été remontée par un agent d’accueil qui a eu le cas lors de l’accompagnement d’un assuré à l’utilisation de MRS.
Sur tous le IPHONE tester nous avons rencontré le même problème.
J’ai pu récupérer les informations de 3 IPHONE testés.

Version 6S+ => iOS  13.1.2
Version 8 => iOS  13.1.2
Version 7+ => iOS  13.1.2

**Comment by sebroussel** [comment]
@notmoebius peux-tu préciser les navigateurs utilisés ? (Safari ?) et tester avec d'autres navigateurs sur iPhone ? (Chrome idéalement)
Peux-tu également me fournir des screenshots de ce qu'il se passe à l'écran avant et après la sélection d'une région ? (je ne comprends pas la phrase "elle se modifie automatiquement")

Ça va être compliqué à reproduire de mon côté, il n'y a pas d'iphone dans mon entourage, on va donc essayer à l'aveugle. 

Pour info, ça fonctionne sur Safari sous MacOS chez moi, le problème viendrait peut-être d'iOS ?

**Comment by sebroussel** [comment]
Après analyse avec Johan (qui a pu tester avec son iphone), il s'avère que le problème se présente pour Safari et Chrome sous iOS : la sélection de la région fonctionne, mais celle de la caisse est complètement hasardeuse (lente, difficile de cliquer, clic sur la caisse A aboutit à la sélection de la caisse B).

Il semblerait que materializecss (qu'on utilise pour notre interface) fasse des siennes sous iOS : il est possible que ça provienne du fait que j'ai "tordu" materializecss pour masquer les caisses qui ne sont pas dans la région sélectionnée.

Je vais repousser la première solution region qui n'avait pas ce hack de materializecss pour vérifier si le problème vient effectivement de là.

**Comment by sebroussel** [comment]
Ok le problème semble limité aux utilisateurs sous iOS13 uniquement, et le problème est connu de materializecss : https://github.com/Dogfalo/materialize/issues/6444
