### ISSUE TITLE
BUG pbl d'accès à la page du profil admin local 

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1111]
Si un agent a le profil admin local, il est à une page page et un refresh provoque:
![image](https://user-images.githubusercontent.com/32330644/66741917-cc246680-ee76-11e9-9a90-448d2acc3506.png)

J'ai pu reproduire en "devenant" le profil utilisateur admin local et j'ai eu la même erreur 403.

**Comment by jpic** [comment]
Fixé en 2d0c80fdac913c5497b275d1510690cdc4db4b22

**Comment by notmoebius** [comment]
Le bugfix semble "tomber", l'admin local est bloqué.
En prenant lecompte de BARROUMES-GARATIN qui a le profil admin local, j'ai une page blanche et erreur 403.
Merci de reprendre ce point bloquant pour communiquer vers nos publics.

**Comment by jpic** [comment]
Sur quelle URL svp ?

**Comment by notmoebius** [comment]
Sur  https://www.staging.mrs.beta.gouv.fr/admin/ cela fonctionne. Mais sur la prod https://www.mrs.beta.gouv.fr/admin/, je choisis un user (Barroumes-Garatin ou Rossi) qui dispose du profil admin local, j'ai une page blanche et c'est bloqué.

**Comment by jpic** [comment]
Ok merci je vois ca, j'essaye de reproduire en local.

**Comment by jpic** [comment]
Ok c'est la version qui supporte le nom de groupe "Admin Local" a ete mise en prod et le groupe n'a pas ete renommé en base.
C'est reglé en prod.
