### ISSUE TITLE
BUG Doublons perseon_person depuis 19/10/2019

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1129]
Constat: 
Depuis le 19/10/2019, des assurés sont créées sans demande associé.
Ce génère un décompte erroné des assurés.

**Comment by sebroussel** [comment]
OK résolu/expliqué : ces 412 assurés résultent d'un import legacy de mars 2018, auxquels aucune demande n'était associée. 

Lors de la migration associée à l'ajout du champ Person.creation_datetime, le script cherchait la première demande associée à la personne pour en déduire la date de création et ainsi peupler la base. Si le script ne trouvait aucune demande, il renseignait la date par défaut timezone.now, à savoir le 31/10 21h38, date d'exécution du script.

Afin de garder une trace, et ne pas polluer les statistiques du mois d'octobre 2019, les creation_datetime de ces 412 associés ont été modifiées au 1/1/2000.
