### ISSUE TITLE
Item sécu et UX mrsrequest_form file and person

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1132]
Suite issue #1131 
Formulaire de remboursement de transports

* File upload:  
                verifier double extensions ,
                rename file (ALWAYS),
                ...
                voire (https://www.owasp.org/index.php/Unrestricted_File_Upload)

* Prenoms, Noms: < 70 characters,
                 uniquement des lettres (plus accents, ç, et - (noms composé) )
                 voir "https://www.senat.fr/questions/base/2004/qSEQ040813407.html"

**Comment by jpic** [comment]
> verifier double extensions

on ne garde que l'extension finale

> rename file (ALWAYS)

c'est le cas
