### ISSUE TITLE
item sécu et ux mrsrequest_form trip

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1133]
suite issu #1131 

Formulaire de demande :
* Date voyages..: toujours fournir un exemple.

* Combien de trajets itératifs: Limiter pour éviter de cracher le navigateur !!

* Distance: instaurer une limite : fixer une limite maximum raisonnable ( 200 000 euro ?)

* Frais péage, parkings, transports : fixer une limite maximum raisonnable ( 200 000 euro ?)

**Comment by jpic** [comment]
Je viens de voir quune limite est déjà fixée a 150 voyages

**Comment by jpic** [comment]
La limite est actuellement fixée à 150 voyages.
La demande validée avec le plus de voyages comporte 124 voyages date du 5/8/2019, c'est la sixième demande avec le plus de voyages.201908050021
Les 5 demandes avec le plus de voyages ont été rejetée, sauf une avec 150 voyages qui a été soumise le 14/11/2019 et qui n'a pas éte traitée 201911140167
Les 4 autres: 201911050283 201805140012 201805140012 201812270023
Du coup, est-ce-qu'on garde 150 en max ?

**Comment by fb86** [comment]
la demande 201911140167 (150 trajets) va être rejeté (la Prescription a été réalisé pour 20 trajets )
Est ce qu'il y aurait un gain réel à limiter le nombre de trajets (voyage) à 100 trajets ?

Par contre tu peux largement diminué la limite pour la Distance. je mettrais 10 000 € . 

10 000€ permet de déclarer plus de 33 333 kilomètres soit  150 voyages avec un trajet aller retour de 110 km 

idem pour stationnement, péage, autres transports (10 000 €)

**Comment by jpic** [comment]
Pour info les plus gros montants en base de prod sont de 9020€ pour les dépenses ATP et de 8800€ pour les dépenses VP.

**Comment by notmoebius** [comment]
150 trajets max

**Comment by jpic** [comment]
Ok tout était déjà bien configuré.
