### ISSUE TITLE
[US] ETQ qu'équipe MRS, je valide une demande de plus de 10Mo

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#114]
Dans l'interface admin, lors de la validation d'un demande,  il faudrait scinder la demande en plusieurs envois (1 envoi = 1 bloc <=8Mo).
Exemple: une demande qui a 5 PJ qui font au total 20Mo pourrait être scinder en 3 mails pour être en dessous des  8 Mo par mail.

Autre piste: réduire la taille des PJ et inciter les utilisateurs à faire des photos en qualité moyenne et pas haute-qualité. L'objectif étant de réduire le poids des PJ (actuellement 10 Mo, faudrait peut-être passé à 2 Mo par PJ).

**Comment by jpic** [comment]
mdr mais ok bien sur

**Comment by jpic** [comment]
Un nouveau deploiement sur https://fred.staging.mrs.yourlabs.org est configure pour envoyer les mails via le sendmail local. L'adresse utilisee pour la liquidation est celle de l'equipe mrs@cnamts, et non remboursement_mrs@cnamts contrairement a l'instance de production.

Vous pouvez donc tester le serveur de mail en validant des demandes sur l'instance de fred. Si les demandes arrivent bien avec tous les attachements sur mrs@cnamts alors on peut router les mails de liquidation vers le sendmail local en production, et au lieu d'une solution palliative on a une solution preventive encore moins intrusive en terme de code: 6296fa5ef2800ba7e881ba1ad7b8a6a33872ad29

**Comment by jpic** [comment]
Aucune modification 'nest prevue pour l'instant.
