### ISSUE TITLE
Actualiser la liste des régimes spéciaux

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#1169]
ETQ assuré je peux demander à être contacter lorsque mon organisme d'assurance maladie aura déployé MRS.
La liste des régimes spéciaux viennent d'être mise  jour.
L'issue est terminé lorsque  la iste des régimes spéciaux est expurgé de toutes les AMO fermées ou reprises au Régime Général, soit : Ministère des anciens combattants, Banque de France, Port autonome de Bordeaux, MFPS (SLI Fonctionnaires), et le RSI.

**Comment by sebroussel** [comment]
OK, les caisses avec identifiants 110, 116, 121, 123 et 128 ont été supprimées en base, et n'apparaîtront plus sur le formulaire de demande. Hormis les adresses emails laissés par les assurés pour ces caisses (objets Email), aucun objet en base ne sont associés à ces caisses. 

@fb86 j'ai fait un backup de ces adresses mails, si vous souhaitez les récupérer.
