### ISSUE TITLE
[Erreur 500] constat d'une erreur sur un demande

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#1178]
Sur la demande n°202001150248, unique dossier pour l'instant,  nous avons une erreur 500 quand on clique sur le n° de la demande. L'état de la demande est soumise.
Si j'utilise le menu hamburger, l'item détail provoque aussi une erreur 500.
L'utilisation de l'item modifier fonctionne et l'on constat qu'il manque des infos dans la demande: nb de km, le nom de famille et l'adresse mail...
Est-ce que le nouveau front n'aurait pas un petit bug qui permet d'envoyer une demande incomplète ? Mon analyse n'est surement pas la bonne mais c'est un ressentie.

**Comment by jpic** [comment]
En approche
![2020-01-23-175928_634x207_scrot](https://user-images.githubusercontent.com/94636/73006211-89c1dc80-3e0a-11ea-9824-edde17d72f74.png)

**Comment by jpic** [comment]
J'ai implémenté un palliatif en prod et la page s'ouvre bien.

Le problème se situe ici: `{{ '%.2f'|format(object.distancevp * 0.3 + float(object.expensevp)) }} €TTC`. Cela n'était pas évident à la vue du traceback: trouvé en divide & conquer sur le template en local.

Le problème de cette demande est d'avoir une distancevp null, mais on est dans un if modevp !

@notmoebius est-il normal qu'une demande vp puisse ne pas avoir de distance ?

D'avance merci
