### ISSUE TITLE
Rebasculer tous les services techniques (sentry, netdata...) sur *.prod/staging.mrs.beta.gouv.fr

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#122]
- [x] sentry.mrs.beta.gouv.fr
 - [x] netdata.prod.mrs.beta.gouv.fr
 - [x] netdata.staging.mrs.beta.gouv.fr
 - [x] mailcatcher.staging.mrs.beta.gouv.fr
 - [x] passbolt.staging.mrs.beta.gouv.fr
 - [x] demander l'ajout de james.pic@beta.gouv.fr a la ML MRS 
 - [x] mettre a jour la variable dans le repo d'inventaire

**Comment by jpic** [comment]
Des difficultes sont a prevoir avec passbolt car le plugin navigateur ne supporte qu'un seul domaine il faut donc le desinstaller et le reinstaller.
