### ISSUE TITLE
ETQ établissement de santé, je peux intégrer MRS dans mon espace patient (cas pour clinique Pasteur)

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#123]
L'objectif est de pouvoir intégrer le formulaire MRS sous forme d'iframe sur un autre site.

Impact formulaire :
- [x] Pouvoir charger le formulaire MRS sous forme d'iframe est pré-renseignant les certains champs (*Nom*, *Prénom* , *Date de naissance* de la personne transportée, *NIR* et *Email* de l'assuré) : 
- [x] le seul paramètre obligatoire *institution=310783048* est le numéro FINESS de l'établissement de santé (champ sur 9 chiffres qui commence par 310 _forcément_ ex: 310783048). 
- [ ] Il est aussi possible de passer un champ *hidePmt=1* pour masquer le champ d'upload PMT.
- [ ] Après chargement de l'iframe, il est possible de pré-remplir la PMT en postant à partir de l'UUID **id_mrsrequest_uuid**. En cas d'échec de l'upload, afficher le champ à l'utilisateur pour qu'il puisse l'ajouter manuellement.
- [x] Formulaire fonctionne uniquement pour les organismes identifiés par l'équipe MRS. le type autres est exclus du champ.

Impact BO :
- [x] Enregistrer à la soumission du formulaire le champ *institution* en plus des autres champs.
- [x] Afficher dans le BO le champ *institution* d'une demande.
- [x] Pouvoir filtrer les demandes par *institution* (vide, ou numéro FINESS) dans par statut (sur le côté)

API :
- [x] Ajouter un end-point **GetStatus** pour retourner le statut (Soumise, Validée, Refusée) et éventuellement la raison du refus (type de refus du *select*) à partir d'un *UUID MrsRequest* et d'un numéro FINESS *institution=XXXXXXXXX*. S'il manque un ou l'autre, retourner une erreur selon le cas (Demande introuvable, impossible de répondre à la demande, établissement inconnu).

- [x] Formaliser l'appel de l'API et l'exemple d'intégration dans une page du wiki avec exemple d'appel et des paramètres obligatoires/optionnels. (doc utilisateur à disposition des établissements de santé)

**Comment by fjg** [comment]
@jpic @notmoebius je veux bien vos retours avant qu'on la priorise.

**Comment by notmoebius** [comment]
OK pur moi. Juste ajuster le nom et prénom de la personne transportée.

**Comment by jpic** [comment]
C'est clair pour moi

**Comment by jpic** [comment]
> ￼ Après chargement de l'iframe, il est possible de pré-remplir la PMT en postant à partir de l'UUID id_mrsrequest_uuid. En cas d'échec de l'upload, afficher le champ à l'utilisateur pour qu'il puisse l'ajouter manuellement.

C'est a dire en JS ou cote serveur ?

**Comment by fjg** [comment]
En JS par l'établissement de santé qui intègre l'iframe. Après le chargement de l'iframe, ils peuvent charger la PMT pour éviter à l'assuré de le faire. Plus clair ?

**Comment by jpic** [comment]
Absolument, donc ca veut dire que l'etablissement de sante va devoir exposer son fichier en HTTP a la session du patient pour l'envoyer en JS et donc c'est bon ;)
Merci <3

**Comment by jpic** [comment]
Est-ce-qu'il peut cacher le champs PMT en CSS au lieu de faire un param GET ?

**Comment by fjg** [comment]
dans quel cas ? pour interroger le statut d'une demande ?

**Comment by jpic** [comment]
Dans le formulaire, si l'institution a deja le PMT, l'institution cache le champs en CSS et lance l'upload, en cas d'echec l'institution n'a qu'a afficher le champs ?

**Comment by fjg** [comment]
Ca peut, si c'est documenté en ce sens.

**Comment by jpic** [comment]
D'acc de toutes facons je fais un exemple en HTML ;)

**Comment by fjg** [comment]
top, ca permettra de valider la story en plus :)

**Comment by jpic** [comment]
> ￼ Formulaire fonctionne uniquement pour les organismes identifiés par l'équipe MRS. le type autres est exclus du champ.
ca va pas dans l'issue #127 par hasard ?

**Comment by notmoebius** [comment]
Oui, tu as raison. Je vais regarder cela pour compléter l'US #127 !

**Comment by fjg** [comment]
roohhhhhh 👍

**Comment by jpic** [comment]
Bravo pour votre reactivite sur github !

**Comment by jpic** [comment]
WIP deployee, en cours

**Comment by jpic** [comment]
Serait-il possible de demander si il faut bien une iframe ou si c'est pas une frameset par hasard pour la clinique Pasteur ?

**Comment by jpic** [comment]
@fjg 
> Ajouter un end-point GetStatus pour retourner le statut (Soumise, Validée, Refusée) et éventuellement la raison du refus (type de refus du select) à partir d'un UUID MrsRequest et d'un numéro FINESS institution=XXXXXXXXX. S'il manque un ou l'autre, retourner une erreur selon le cas (Demande introuvable, impossible de répondre à la demande, établissement inconnu).
 
Cela implique que la clinique recupere l'uuid depuis l'iframe, se l'envoie sur un nouveau endpoint de son site pour le stocker, pour recuperer le statut via l'API MRS.

Cela s'ajoute donc a l'envoie de la PMT apres avoir recupere l'uuid de l'iframe pour executer un download navigateur de la PMT du server de la clinique, enchaine d'un upload navigateur de la PMT.

La clinique doit implementer:

- page qui affiche l'iframe,
- script qui gere la pmt,
- endpoint qui sauvegarde l'uuid,

Avant de se lancer dans ce hack JS, pouvons-nous comparer cette specification alternative ?

- poste du finess et eventuellement la pmt du client sur un endpoint MRS qui renvoie une uuid (qu'il stocke) et une url de formulaire
- affiche le formulaire dans une iframe,

MRS ajoute donc un endpoint qui permet a un finess de recuperer un uuid et de poster une PMT dedans dans la foulee si dispo.

Concernant le formulaire en iframe, on doit donc accepter que l'utilisateur passe son uuid, on va de toutes facons matcher le numero de finess puisqu'on l'a et verifier que pour cet uuid il n'existe qu'un pmt en base avant de permettre l'ecriture a l'utilisateur.

**Comment by jpic** [comment]
Je coche la partie API en faveur #142

**Comment by jpic** [comment]
Reste la partie PMT, je ferme cette issue en faveur de #145
