### ISSUE TITLE
ETQ Equipe MRS, je peux enregistrer une CPAM et lui affecter une adresse mail de routage 

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#126]
Je peux enregistrer une CPAM dans le BO et lui affecter une adresse mail de routage des demandes mrs validées.

Sur le BO, une CPAM aura :
- code CPAM - (Les codes organismes sont construit selon un champs alpha numérique de 9 car.)
- libellé de CPAM - (champ texte 50 caract.) - (ex: CPAM de la Haute-Garonne)
- adresse mail de remboursement MRS servant au routage vers le service de liquidation.
Tous les champs sont obligatoires.
L'adresse mail de routage visible uniquement par Equipe MRS.

Créer une CPAM "Autres" : Code = "Autre", Libellé = "Autre organisme", Mail = "contact@mrs.beta.gouv.fr".

Provisionner la liste des caisses (101 items). La caisse n'est pas dans la cible de l'expérimentation, alors affichez "Votre caisse ne fait pas partie des organismes participant à l'expérimentation. Le service sera prochainement ouvert. Pour rester informer, indiquez votre adresse mail."

Le formulaire propose la liste des caisses hors cible MRS. Puis :
- champ adresse mail assuré (saisie facultative)
 -bouton OK valide la demande et compte pour un vote.

```
Caisse* : [ Autre   v ]
Votre caisse* : [ 75 Paris    v ]
Email : [      @      ]
[ OK ]
```

~~Si le code CPAM est "Autre", dans ce cas, s'affiche sur le formulaire "Votre caisse ne fait pas partie des organismes participant à l'expérimentation. Merci d'indiquer vos coordonnées et votre caisse de rattachement"->lien vers form contact. Cela permet la saisie d'un commentaire par l'assuré à la place du formulaire MRS Ouverture d'un popup (ouvre une page en fait) qui indique que "l'organisme n'est pas accessible" pour l'instant et qu'ils peuvent faire une demande via un formulaire de contact~~ :

Le contenu du formulaire est envoyé à la bal contact@mrs.beta.gouv.fr. 
L'équipe MRS pourra dénombrer le nombre de demande pour une caisse et proposer le service.

[caisses.zip](https://github.com/betagouv/mrs/files/1788490/caisses.zip)

**Comment by jpic** [comment]
Merci pour cette belle issue c'est plutot clair pour moi à ce stade après bien entendu des questions pourront arriver en cours de developpement ;)

**Comment by notmoebius** [comment]
01311XXXX pour Toulouse
01091YYYY pour Foix
01161ZZZZ pour Angoulème etc...
le 01 indique la sécurité sociale
02 MSA, et..
le code à 3 chiffres le code caisse: 311 pour Toulouse.
Autre exemple : 016420000 pour Bayonne et 016410000 pour Pau un département mais deux caisses.

**Comment by jpic** [comment]
Merci !

Donc [01311 doit devenir 0131100000](https://github.com/betagouv/mrs/blob/ebe9aa7fcf80b12e4755a26dac01392f061292d3/src/mrsrequest/migrations/0008_add_cpam_fk.py#L12).

Question importante pour le tri:

La description du ticket indique:

> code CPAM - (Les codes organismes sont construit selon un champs alpha numérique de 9 car.)

Ca serait pas plutot juste numerique au lieu de alphanum par hasard ?

C'est peut etre un detail pour vous mais pour une db ca veut dire beaucoup :joy: :joy: :joy:

**Comment by notmoebius** [comment]
@jpic J'ai uploadé le fichier des caisses avec num, description et code organisme à 9 caract.

**Comment by jpic** [comment]
@notmoebius 
> code CPAM - (Les codes organismes sont construit selon un champs alpha numérique de 9 car.)

Mais la troisieme colonne du CSV est sur 10 chars, est-ce-que c'est normal ? Faut-il tronquer le dernier caractere du CSV ?

**Comment by jpic** [comment]
Suite a la discussion sur le chatops on envoie en staging la version avec 1 zero de droite en moins sur le csv, soit le code normal a 5 chiffres plus 4 zeros.

**Comment by jpic** [comment]
Les dernieres modifs pour "enregistrer une CPAM et mail de routage" sont dispos pour review en staging ( #177 #178 #179 ) pour le reste j'ai cree d'autres issues a jour normalement n'hesites pas a editer en direct si besoin #191 #189 #190 Une issue par nouveau champs ;)
