### ISSUE TITLE
ETQ assuré, je peux déclarer ma caisse de rattachement lors de ma demande de remboursement.

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#127]
Lors de la saisie du formulaire MRS :
- l'assuré commence par déclarer sa caisse de rattachement lors de sa demande de remboursement. Il doit choisir dans une liste déroulante la caisse de rattachement (libellés des code CPAM disponibles + Autre).
Ce champ sera le premier à être renseigné par l'assuré avant de charger sa PMT.

Affichage de la page:
"Quel est votre organisme de rattachement ?' (--> liste déroulante).
Si "Autre" (l'organisme n'est pas identifié), ouvrir formulaire de l'issue #126.
---------------------------------------------------------------------------------------------------

En cas de formulaire intégré par l'établissement, c'est l'outil de l'établissement qui affiche ou pas le formulaire en fonction de l'organisme de rattachement.
SI service ouvert à l'assuré (car organisme rattaché à MRS) ALORS le formulaire MRS apparaît.

En clair, l'établissement doit savoir à quel organisme est ouvert MRS.

**Comment by fb86** [comment]
Les codes organismes sont construit selon un champs alpha numérique de 9 CARACTÈRES.

**Comment by jpic** [comment]
Faut-il sauvegarder aussi la premiere colonne du CSV @notmoebius ?

**Comment by jpic** [comment]
On a une mise a jour sur #191 #189 #190 pour suivre les avancements car on va deployer au fur et a mesure ;)
