### ISSUE TITLE
L'identifiant des demandes n'est pas remis à 0 chaque jour

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#131]
Chaque jour on devrait repartir à 0 les compteurs de demandes.
Exemple : 201802010105 devrait surement être 20180201004...

**Comment by jpic** [comment]
J'ai implemente ce qu'il manquait dans django-dbdiff pour passer les tests sous pg debloquant ainsi l'implementation d'un test anti regression sur cette feature, a release sous peu ;)

**Comment by jpic** [comment]
J'ai envoye un bugfix, l'implementation est maintenant en python et soumise aux limitations suivantes:

- possible que deux demandes simultanees aient le meme id,
- si on supprime la derniere demande alors la suivante aura le meme id que celle qu'on vient de supprimer,

Si on veut repasser sur le trigger cela demande plus de travail, 1 jour ou 2.

**Comment by jpic** [comment]
@notmoebius ping pour voir le comment ci-dessus ;)
