### ISSUE TITLE
ETQ assuré, je peux accéder aux mentions légales du site MRS

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#133]
Lors de la navigation sur le site MRS, l'assuré doit pouvoir accéder aux mentions légales du site MRS.
Les mentions légales seront accessibles : 

- à partir du footer,
- en cliquant sur le mot "MENTIONS LEGALES" (placé à droite de la mention "©2017 - CNAM - CPAM DE LA HAUTE-GARONNE"
- cela ouvrira une nouvelle page HTML
- le design du site sera intégré à cette page (lors de l'integration)
- le rédactionnel est disponible en attache files
[mentions_legales_def.docx](https://github.com/betagouv/mrs/files/1699262/mentions_legales_def.docx)

**Comment by jpic** [comment]
En cours

Template: https://github.com/betagouv/mrs/blob/tbinetruy/src/mrs/templates/legal.html
Url: https://tbinetruy.mrs.yourlabs.org/mentions-legales

**Comment by jpic** [comment]
J'ai intégré le DOCX en HTML: https://jpic.mrs.yourlabs.org/mentions-legales

Il suffit maintenant de faire le webdesign.

**Comment by jpic** [comment]
Je merge en master dans la big bang release qu'on prepare.
