### ISSUE TITLE
ETQ Assuré, je peux consulter la page des stats

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#147]
Une page HTML avec CSS et IMG a été réalisée.
Il faut déposer ces livrables sur un site permettant la consultation des stats KPI de MRS.
Exemple: https://mrs.beta.gouv.fr/stats/ affiche les indicateurs (carte trello pour les livrables)

**Comment by jpic** [comment]
Decalage du deploiement a demain suite a la discussion sur le chat ;)
