### ISSUE TITLE
Image manquante sur lol.mrs

### ISSUE THREAD

**Issue by Natacha1974** [betagouv/mrs#16]
En ouvrant le site lol.mrs.beta.gouv.fr depuis mon mobile Android, la photo d'ouverture n'apparaît pas. Tout le reste est ok !

**Comment by notmoebius** [comment]
En mobilité, l'image n'apparait pas, ni sur iOS, ni sur android.

**Comment by jpic** [comment]
@tbinetruy ping ;)

**Comment by jpic** [comment]
@tbinetruy y-a-t-il un polyfill ?

**Comment by tbinetruy** [comment]
Hello !!

Alors j'ai regarde et le probleme viens du fait d'utiliser l'image en background-img sur body. En effet, en mobile, si je positionne ce bg avec les styles 'background-size: cover' et 'position: fixed', le bug est documente sur safari [0].

J'ai enfin acces a un mac et donc a un debugger pour mon iphone.

Je vais dans un premier temps positionner l'image non plus en bg de body, mais en 'position: absolute' sur tout le viewport avec 'object-fit: cover' sur l'img pour la cadrer.

[0] https://stackoverflow.com/questions/36686654/fixed-background-images-disappear-on-iphone-ipad

**Comment by tbinetruy** [comment]
patch: https://github.com/sgmap/mrs/commit/2cfe5d9ec80f97618327bdf7feb28a6429c58cd4
