### ISSUE TITLE
[page] [desktop] Intégrer et séparer la SPA en différentes pages cf. PSD

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#173]
Différents pages :

- /contact : avec le formulaire de contact
- /mentions-legales : avec les mentions légales
- /demande ou /formulaire : pour le formulaire
- /faq : pour la foire aux questions

![pagedesktop](https://user-images.githubusercontent.com/91435/37029791-e5bd0424-2138-11e8-9293-0c9a4d7326de.png)

**Comment by FrancoisPhilippe** [comment]
@tbinetruy @jpic https://framadrop.org/r/qp57Fl08xS#3ka/0wcT+9ZKdOe7mDcQx1lHyT11FE5DNjHjMJuEYgA=
ci dessus le lien vers le psd de la page FAQ pour la version mobile tout le contenu à la suite sur 1col au lieu de 2
bon courage les gars
