### ISSUE TITLE
Manque la mention Nous contacter en bas de page fonctionnement

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#198]
Supprimer la saisir nous contacter:
![image](https://user-images.githubusercontent.com/32330644/37589224-e56819f6-2b64-11e8-9ff7-c591a564482b.png)

**Comment by notmoebius** [comment]
Je pense que c'est un relicat qu'il faut enliver vu que le menu contact renvoi bien sur la page adéquate

**Comment by jpic** [comment]
Je comprends pas l'issue en fait il faut changer quoi exactement stp ?

**Comment by tbinetruy** [comment]
Alors on a rajoute la mention nous contacter en bas de la page fonctionnement. Je ferme pour le moment (Cf titre de l'issue) mais n'hesitez pas a reouvrir ou creer une autre issue pour retirer le formulaire si necessarire (cf 2eme com de @notmoebius
