### ISSUE TITLE
Favicon 

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#220]
Intégrer le favicon créé par François. Testé sur IE11 et non intégré.

**Comment by tbinetruy** [comment]
Effectivement, je m'en occupe. Malhereusement, je ne trouve pas la favicon, savez vous ou je peux me la procurer ?


Merci,

Tom

**Comment by jpic** [comment]
Dans le PDF qui va arriver d'une minute a l'autre sur ce ticket, il y a une section favicon, avec deux versions tu peux choisir celle qui t'inspire.

**Comment by fjg** [comment]
Voici la charte avec la favicon (v1 ou v2 au choix de ce qui t'inspire)

**Comment by fjg** [comment]
[charte_mrs.pdf](https://github.com/betagouv/mrs/files/1829967/charte_mrs.pdf)

**Comment by tbinetruy** [comment]
top, merci !

**Comment by jpic** [comment]
Je la voie pas sur ta branche en fait

**Comment by jpic** [comment]
[pictoMRS.zip](https://github.com/betagouv/mrs/files/1852271/pictoMRS.zip)
les favicons sont ci jointes

**Comment by tbinetruy** [comment]
https://github.com/betagouv/mrs/commit/f9c2116e9e319cf717524e5f97a99fc4f87f3e3c
