### ISSUE TITLE
Désign mentions légales

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#222]
Reformater le texte pour le mettre à l'image du reste du site.

Harmoniser les tailles de texte.

Un tableau à faire disparaitre dans le texte cf. capture

**Comment by fjg** [comment]
![img_1432](https://user-images.githubusercontent.com/91435/37665691-1db52746-2c5e-11e8-8df4-7708a1b9d7b6.PNG)
![img_1433](https://user-images.githubusercontent.com/91435/37665692-1de0093e-2c5e-11e8-8b17-34bb7250f0ae.PNG)

**Comment by tbinetruy** [comment]
Un truc du style comme pour la FAQ ?

**Comment by fjg** [comment]
oui l'idée est d'homogénéiser les pages avec texte simple (type article...)

**Comment by jpic** [comment]
Nice <3
