### ISSUE TITLE
Faire rentrer le menu sur la largeur de page

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#228]
Contact déborde à droite sur desktop

<img width="1093" alt="capture d ecran 2018-03-20 a 17 04 05" src="https://user-images.githubusercontent.com/91435/37666841-cf0e5bf0-2c60-11e8-9f87-ebe9d081d7a0.png">

**Comment by tbinetruy** [comment]
Merci.

Alors la difficulte provient du fait que la largeur du header est definie de maniere absolue, alors que le corps de la page est fonction de la largeur de la page [0].

Une solution serait de garder le comportement actuel, mais de contraindre la largeur minimale du corps a celle du header. Puis de calibrer le tout pour que la version mobile du menu se mette en place sur les largeurs d'ecrans inferieures a celle du menu (*i.e.* quand la largeur du navitgateur ne permet pas au header d'etre entierement visible).

[0] moins un padding definie absolue en mobile et fonction de la largeur de l'ecran en desktop:

| Commentaire | Capture 1 | Capture 2|
|--|--|--|
| La marge du corps en desktop est function de la largeur ecran | ![screenshot from 2018-03-22 12-51-16](https://user-images.githubusercontent.com/19936648/37785271-20098f50-2dd0-11e8-87b0-a6b68d23b588.png) |  ![screenshot from 2018-03-22 12-51-23](https://user-images.githubusercontent.com/19936648/37785274-25d015f8-2dd0-11e8-9e54-36ad78b17ad1.png) |     
| La marge du corps en mobile est definie en absolue | ![screenshot from 2018-03-22 12-51-56](https://user-images.githubusercontent.com/19936648/37785313-3bd82c14-2dd0-11e8-937b-a1ae0cb03af3.png)  |     ![screenshot from 2018-03-22 12-52-03](https://user-images.githubusercontent.com/19936648/37785354-503d25b0-2dd0-11e8-982d-d9ae8f8f7b65.png)|

**Comment by fjg** [comment]
ok tu peux rogner les marges oui et même un peu le right-margin du logo qui n'est pas équilibré (plus de blanc à droite).

**Comment by tbinetruy** [comment]
pour la marge du logo, effectivement je n'avais pas vu: https://github.com/betagouv/mrs/commit/9b3bce64aed7b7e7daed5650f096d5c49e806c28

et pour le reste, c'est deja pushe en master ;)
