### ISSUE TITLE
crée mail type rejet (PMT absente)

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#230]
Dans la page : https://www.mrs.beta.gouv.fr/mrsrequest/1d193a80-be80-4eb4-b08e-4006006177de/reject/

crée un nouveau mail type de rejet 

A: mail assuré
de : contact@mrs.beta.gouv
sujet : Demande invalidée pour absence de prescription médicale de transports.
reponse : mrs@cpam-toulouse.cnamts.fr

_Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter car vous n'avez pas transmis votre prescription médicale de transport. La prise en charge des transports est soumise à prescription médicale.

Nous vous invitons à renouveler votre demande en joignant ce document.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS_

**Comment by Johan1983** [comment]
Propal V2

_Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter car vous n'avez pas transmis votre prescription médicale de transport. La prise en charge des transports est soumise à prescription médicale.

Nous vous invitons à renouveler votre demande en joignant ce document.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS_
