### ISSUE TITLE
Texte temoignage se chevauche sur internet explore 11

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#235]
sur la page d'accueil de MRS, sous internet explore 11
https://www.mrs.beta.gouv.fr/

le texte de témoignage assuré se chevauche (voir image exemple)
![us 235](https://user-images.githubusercontent.com/34480111/37684288-7c417a52-2c87-11e8-986e-a50cabef960b.GIF)

**Comment by tbinetruy** [comment]
Oulala, je regarde, grand merci !!
