### ISSUE TITLE
Balise meta

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#236]
Je viens de faire un test sur le referencement Google et les mentions legales sont présentes dans la description du site ainsi que les retours utilisateurs . Il faudrait le supprimer et je proposerai une description dans la foulée.

![mrs beta gouv _ index](https://user-images.githubusercontent.com/34479425/37716903-dc3e1b02-2d1f-11e8-934d-06961ba28d9e.jpg)

**Comment by jpic** [comment]
Justement, question SEO, j'ai besoin du titre, et de la description, pour chacune des pages exposées. Est-ce-que tu peux me bichonner cela stp ?

**Comment by Johan1983** [comment]
Je m'en occupe, j'essaye avant mardi mais pas sûr...

**Comment by fjg** [comment]
* Page Accueil

Titre : Découvrez MRS | MRS
Description : Mes Remboursements Simplifiés (MRS) est un service innovant de l'Assurance Maladie pour accélérer et faciliter le remboursement des frais d’utilisation du véhicule particulier ou du transport en commun suite à une prescription médicale. MRS permet de déclarer directement en ligne et d’être remboursé en une semaine.

* Page Formulaire
Titre : Déclarez vos frais de transports personnels | MRS
Description : Avec Mes Remboursements Simplifiés (MRS), sous réserve d’une prescription médicale, vous pouvez déclarer directement en ligne vos frais de transports personnels. C’est simple et rapide : vous prenez en photo vos justificatifs et en une semaine vous êtes remboursé.

* Page FAQ
Titre : Une question sur Mes Remboursements Simplifiés | MRS
Description : Découvrez les réponses à vos questions sur les modalités d’utilisation du service Mes Remboursements Simplifiés (MRS) ainsi que les différentes situations de prise en charge.

* Page Contact
Titre : Contactez MRS | MRS
Description : Vous souhaitez contacter Mes Remboursements Simplifiés (MRS) ? Vous pouvez poser une question sur le service MRS ou nous faire part de vos remarques à travers le formulaire de contact.

* Page Mentions Légales | MRS
Titre : Mentions Légales | MRS
Description : MRS est un service innovant de simplification des démarches de remboursement des frais de transports personnels à l’initiative de la CPAM de la Haute-Garonne.

* Page Statistiques
Titre : Statistiques | MRS
Description : Découvrez les statistiques d’utilisation du service Mes Remboursements Simplifiés (MRS).

**Comment by fjg** [comment]
Revue. GO Dev
