### ISSUE TITLE
Interruption Transfert demande validé vers bal remboursement-mrs@cpam-toulouse.cnamts.fr

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#237]
Aucune demande validée sur mrs n'est parvenu sur la bal remboursement_mrs@cpam-toulouse.cnamts.fr depuis le dimanche 18 mars. 
a t on une idée de l'origine du problème ? MRS, CNAM,.....

**Comment by notmoebius** [comment]
Le problème venait de la BAL qui était saturée. 
Quota augmentée et contenu épuré: j'ai gardé un mois de profondeur.
Les dossiers ont été archivés sur un espace de stockage Contrôle-MRS local.
