### ISSUE TITLE
[US] ETQ équipe MRS, je peux valider et suivre les demandes de remboursement

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#24]
Une demande a un **statut** qui peut être soit :
* SOUMISE : l'état d'une demande reçue 
* VALIDEE : l'état de la demande est traité lorsqu'elle est envoyé au service PN
* REJETEE : l'état de la demande est rejetée pour non conformité.

Chaque demande est identifiée de manière unique par un numéro respectant le format : **AAAAMMJJ9999** où AAAA est l'année, MM le mois, JJ le jour et 9999 id séquentiel de 0 à 9999.

Formalisation des actions possibles sur cet écran première itération.

Sur la liste des demandes, je peux :

- [x] Je peux rechercher sur le champ NIR ou Nom ou n° de la demande
- [x] Je peux filtrer les demandes sur l'état 
- [x] Je peux cliquer sur un n° de demande et le système m'affiche le détail de la demande
- [x] Je peux trier l'affichage de la liste par n° de demande, nom-prénom et l'état de la demande.

Sur une demande, je peux :
- [x] Je peux cliquer sur l’image de la PMT pour la consulter
- [x] Je peux cliquer sur l'image Justificatif(s) pour afficher les PJ.
- [x] Je peux valider une demande qui est alors envoyée au service liquidation pour traitement. Un mail est donc envoyé :

````
From: mrs@cpam-toulouse.cnamts.fr
To: remboursement_mrs@cpam-toulouse.cnamts.fr
Subject:
Attachment(s): ajouter les pièces jointes fournies (PMT, justificatifs...)
Body:
Bonjour, 
 
veuillez trouver ci-joint une demande de remboursement via MRS n°AAAAMMJJ9999 :

- Reference : AAAAMMJJ9999
- Prescription Médicale de Transport : IMG_20171218_164214.jpg
- Prénom : Patricia
- Nom de famille : Kanitzer
- Date de Naissance : 13/10/1966
- Numéro de Sécurité Sociale : 2661097414101
- Adresse email : damien.kanitzer@sfr.fr
- Date du trajet aller : 18/12/2017
- Date de trajet retour : 18/12/2017
- Kilométrage total parcouru en voiture : 50
- Montant total des frais : 2,40
- Justificatifs : IMG_20171218_164357.jpg
 
Cordialement,
L'équipe MRS
````

- [x] Je peux rejeter une demande. Je dois alors choisir la raison parmis l'un des 3 cas suivants :

* Pièce(s) justificative(s) manquante(s)
* Justificatifs illisibles (PMT ou frais) 
* Rejet (raison réglementaire)

Selon la raison un mail différent est envoyé :

* Pièce(s) justificative(s) manquante(s)
````
From: mrs@cpam-toulouse.cnamts.fr
To: <adresse mail de la demande>
Subject: Accusé de réception Demande de remboursement frais de transport Véhicule Personnel du………
Body:
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport en véhicule personnel.
Vous ne nous avez pas transmis le justificatif de paiement de :
-	Vos frais de stationnement ou de péage (au choix selon la situation)

Nous vous invitons à nous les adresser par retour de mail sous une semaine. A défaut, nous procéderons à votre remboursement en excluant vos frais de  péage ou stationnement (au choix selon situation).
 
Bien cordialement,
L'équipe MRS
````

* Justificatifs illisibles (PMT ou frais) 

````
From: mrs@cpam-toulouse.cnamts.fr
To: <adresse mail de la demande>
Subject: Accusé de réception Demande de remboursement frais de transport Véhicule Personnel du………
Body:
Bonjour,

Nous avons détecté un problème lors de la soumission de votre demande de remboursement. 

Nous ne pouvons toutefois pas y donner suite pour le motif suivant :
- Indiqué la nature du document illisible ou erroné (pièces en rouge)
Nous vous invitons à renouveler votre demande en y joignant les documents manquants.

Nous vous invitons à nous les adresser par retour de mail.
 
Bien cordialement,
L'équipe MRS
````

* Rejet (raison réglementaire)

````
From: mrs@cpam-toulouse.cnamts.fr
To: <adresse mail de la demande>
Subject: Accusé de réception Demande de remboursement frais de transport Véhicule Personnel du………
Body:


````

**Comment by notmoebius** [comment]
@jpic nous avons quasi finalisé le back office. Il manque un body de mail à finaliser car celui que l'on a par défaut ne me semble pas approprier au contexte. On voit cela rapidement pour compléter mais tu devrais avoir assez de matières pour cette nuit :wink:

**Comment by notmoebius** [comment]
J'ai testé le back office mais il manque le "wording". Pour l'instant, c'est brut de fonderie. Je n'ai pas réellement mis d'adresse mail donc, pas testé les mails, uniquement l'interface. Cependant, on voit arrivé les demandes sur le BO et les PJ. On reparle en janvier.

**Comment by jpic** [comment]
Pour l'instant tout est implémenté sauf l'envoie de mail.

Auxquelles "pièces en rouges" se réfère le mail de justificatif illisible ?

**Comment by jpic** [comment]
![2018-01-16-011507_1330x534_scrot](https://user-images.githubusercontent.com/94636/34966257-c9decb66-fa5a-11e7-8e51-9f8794636ea3.png)
![2018-01-16-011457_1305x448_scrot](https://user-images.githubusercontent.com/94636/34966258-c9f63e86-fa5a-11e7-9e5e-792402e41301.png)
![2018-01-16-011449_1302x603_scrot](https://user-images.githubusercontent.com/94636/34966259-ca0d9338-fa5a-11e7-95c9-8b1f7cedf8d2.png)

**Comment by jpic** [comment]
Mail reçu avec attachements (qu'on ne peut pas tester sur mailcatcher, donc staging, testable sur jpic.mrs.yourlabs.org)
![2018-01-16-102124_952x526_scrot](https://user-images.githubusercontent.com/94636/34981245-3ae94b32-faa7-11e7-8ea6-b89ded3d34da.png)
