### ISSUE TITLE
Enrichir le statut lorsque rejet

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#240]
ajouter le motif du rejet (sujet du mail de rejet) dans l'info statut de la demande lorsque la demande a été rejeter 
![statut demande](https://user-images.githubusercontent.com/34480111/37862215-40dfd514-2f41-11e8-8987-7f65092a85c6.GIF)
:+1: 

en cas de réclamation, cela nous permettra de savoir pourquoi l'on l'a rejeté sans revenir à l'étude du dossier.

**Comment by fjg** [comment]
* Lié (relation modèle - fk) le rejet le au mail utilisé pour le rejet.

* Afficher dans la liste des mails de rejet, les statistiques de rejet.

* Ne pas pouvoir supprimer un mail, mais ajouter un flag activé/désactivé.

* Afficher sur une demande rejeté le titre du mail de rejet utilisé : exemple "Statut : rejetée par fred le XX mars 2018 09:39 pour raison : *titre du mail utilisé*"

**Comment by fjg** [comment]
revue. GO dev
