### ISSUE TITLE
Séparer les frais en deux saisies : frais de parking, frais de stationnement

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#241]
Pour limiter les incompréhensions des assurés : séparer dans le formulaire de demande la rubrique frais en 2 sous rubriques ou l'assuré pourra indiquer un montant distinct :
- Frais de stationnement  
- frais de péage
![frais de stationnement](https://user-images.githubusercontent.com/34480111/37903781-b5d27cac-30e8-11e8-825a-ab446e435be4.GIF)

En conservant bien sur la possibilité de mettre une pj

a noter, entraine une modification sur la qualification des cpam (vir issues 242)

**Comment by jpic** [comment]
Affirmatif

**Comment by Natacha1974** [comment]
#242 supprimée car pour l'instant ouverture qu'aux caisses de l’Occitanie donc frais de stationnement pris par toutes. De même issue #241 utile surtout pour les organismes hors CPAM d’Occitanie.
Si on sépare les frais de stationnement et les frais de péage, il faudrait créer une 3ème sous-rubrique pour les frais de transport en commun qui sont annoncés. 
Ces précisions pourraient finalement attendre le développement très prochain du multi-mode de transports.

**Comment by notmoebius** [comment]
Je confirme la clôture pour mettre cette issue en standby
