### ISSUE TITLE
selectionner pour une caisse si elle prend en charge les frais de parking

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#242]
a la suite de US #241 :

la prise en charge des frais de stationnement est une option laissé à la main de chaque CPAM. 
la prise en charge des frais de stationnement et de péage ayant été dissocier par us 241, il faudrait que la rubrique frais de stationnement ne s'affiche que si la caisse prend en charge ce type de frais. pour cela,
il faudrait pouvoir faire un top frais de stationnement (à la main de l'administrateur ) à activé dans le tableau de configuration de la CPAM, au même titre que l'adresse mail. Ce top entrainant la possibilité ou non pour l'assuré de déclaré ses frais de stationnement selon la prise en charge octroyer par la CPAM.

**Comment by fjg** [comment]
Pas nécessaire sur le périmètre actuel donc à voir le moment venu.
