### ISSUE TITLE
Créer un profil liquidateur pour permettre à des techniciens de validés les demandes MRS

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#243]
Dans l'attente de la mise en œuvre de l'interfacage avec diademe, créer un profil liquidateur permettant à des techniciens de liquider les demandes MRS. 
Liquider les demandes MRS veut dire : Valider ou rejeter les demandes MRS pour son organisme depuis https://www.mrs.beta.gouv.fr/admin/mrsrequest/mrsrequest/

User - has many Caisses
User - has many Groupes (Administrateur / Liquidateur)
Group - has many Permissions (CRUD)

Liée à #244

**Comment by jpic** [comment]
Recherche dans le domaine : https://medium.com/dailyjs/what-is-casl-or-how-can-you-build-a-castle-around-your-application-4d2daa0b1ab4

**Comment by jpic** [comment]
Progres: j'ai passe cette migration en manuelle qui permetra d'assigner une caisse a un utilisateur: b6fc51e356bf32
