### ISSUE TITLE
Permettre aux profils admnistrateur d'affecter un profil liquidateur aux techniciens

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#244]
Dans la continuité 
https://github.com/betagouv/mrs/issues/243
permettre aux profils administrateur d'affecter un profil liquidateur aux techniciens. le profil est affecté pour un technicien sur une ou plusieurs CPAM.
Affecter un profil liquidateur veut dire donner aux techniciens un mail/identifiant et un mot de passe.
Ce profil permet au technicien de voir les demandes relevant de son/ses organisme(s), traiter les demandes et visualiser les demandes traités.

**Comment by jpic** [comment]
En staging sur /newadmin
