### ISSUE TITLE
Export/Import pour calcul des stats

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#252]
A partir de MRS, avoir un module pour importer les données suivantes, par caisse. 

En tant qu'administrateur, je me connecte au BO. Un nouvel écran **Stats** permet d'exporter les demandes validées, et non déjà importées (sans Date de mandatement).

Ne sont exportées que les demandes validées. Les colonnes suivantes sont présentes et remplies :

- Caisse de l'assuré(e)
- n° de la demande
- NIR assuré
- date de naissance de la pers. transportée
- prénom et nom de la pers. transportée
- date du premier trajet (date la plus ancienne)

au format CSV.

Le fichier CSV contient aussi 6 colonnes vides.
- Date de mandatement (JJ/MM/AAA)
- Base de Remboursement (Montant en euros)
- Montant remboursé (Montant en euros)
- Assuré qui bascule (1 pour basculé/0 pour non basculé)
- n° finess du prescripteur (9 caractères)
- n° adeli du prescripteur 
Ces colonnes supplémentaires sont alimentées en retour par un système interne.

La partie import va reprendre les mêmes données alimentées par le système de requêtes Assurance Maladie pour les colonnes ci dessus.

A l'import dans MRS :
- la colonne *Date de mandatement* peut être vide (soit pas encore traitée, soit parce que rejetée au paiement)

Après l'import, le système calcule 3 indicateurs supplémentaires pour chaque demande :
- Coût théorique du trajet en taxi = (((nb de kilomètre parcourus total * 1.62) + (1.9 * 2 * Nbre de trajet itératif de la demande)) * 0.91
- Economie calculée selon la règle (Montant en euros) :
``
  SI 'Assuré qui bascule' est 1 ALORS Economie = Coût théorique du taxi - Base de Remboursement SINON =0 FINSI
``
- Délai de paiement (en jour décimal) = Date de mandatement - Date de la demande

**Comment by notmoebius** [comment]
Suite aux travaux de ce jour, il apparaît que l'export n'est plus nécessaire. J'ai reformulé avec le groupe, l'issue pour cette US

**Comment by notmoebius** [comment]
rollback de l'issue US avec une MAJ de la formule sur le cout théorique taxi.
Rollback après consultation de FJ

**Comment by jpic** [comment]
vous etes certains de vouloir importer/exporter des csv, plutot que de remplir directement un tableau sur une page ?

**Comment by jpic** [comment]
du coup en csv de sortie j'obtiens ceci:

```
CAISSE FOIX,201806010000,1111111111111,30/04/2014,jamesy pic,30/03/2016,,,,,,
CAISSE TOULOUSE,201805010001,2333333333333,30/04/2018,uea ue,29/04/2018,,,,,,
CAISSE FOIX,201805010000,1111111111111,30/04/2018,aoeu aoeu,29/04/2018,,,,,,
```

est-ce-que ca correspond a vos attentes ?

**Comment by jpic** [comment]
![2018-06-06-210813_1289x765_scrot](https://user-images.githubusercontent.com/94636/41059829-fd20c0e6-69cd-11e8-948d-172d031fff66.png)

**Comment by notmoebius** [comment]
Oui, cela correspond. J'ajouterai le nom des colonnes sur la premières lignes.
Le rapport d'import est bien, c'est une bonne feature.

**Comment by jpic** [comment]
Effectivement j'en ai mis depuis:

```
caisse,id,nir,naissance,nom,transport,mandatement,base,montant,bascule,finess,adeli
CAISSE FOIX,201806010000,1111111111111,30/04/2014,jamesy pic,30/03/2016,,9,8,1,,oaseuthaosent
CAISSE TOULOUSE,201805010001,2333333333333,30/04/2018,uea ue,29/04/2018,30/04/2018,12,13,0,,123124aojeu
CAISSE FOIX,201805010000,1111111111111,30/04/2018,aoeu aoeu,29/04/2018,,6,7,1,1234aoeui,blaoblaoeu

```

Question: pour le numero adeli on cree une nouvelle relation ou on stocke dans une nouvelle colonne ? (c'est pour affichage ou filtrage ?)

**Comment by jpic** [comment]
![2018-06-07-123618_579x705_scrot](https://user-images.githubusercontent.com/94636/41094752-b00d5490-6a4f-11e8-87e6-89a9d30d896f.png)

**Comment by notmoebius** [comment]
Concernant le comment ci-dessus, je ne souhaite pas de retouche dans le pavé Transports avec le Montant des KM parcourus, la base de remboursement et montant remboursé. Ce pavé sert au liquidateur pour l'instant, dans une future feature pourquoi pas quand on aura automatiser la saisie.

**Comment by notmoebius** [comment]
n° adeli et finess c'est pour recherche et affichage. Ça permettra d'identifier les cliniques ou médecins

**Comment by jpic** [comment]
@notmoebius quelle est la relation entre adeli et finess ? Est-ce-que on cree une nouvelle table de prescripteurs avec une relation depuis la table de demande et une vers la table d'etablissements ?

**Comment by jpic** [comment]
premiere iteration en cours de deploiement en staging pour retours
boutons import et export dans le menu principal

reste a faire:
- [ ] gestion adeli (a voir ou dans la structure db)
- [ ] affichage des donnees dans la page de detail d'une demande (qui voie quoi et ou)

**Comment by jpic** [comment]
Nouvelle version import/export en staging pour retour :dancer:

**Comment by jpic** [comment]
nouvelle version en staging pour nouveaux retours :dancer:

**Comment by jpic** [comment]
Question relative au calcul des delais:
> Délai de paiement (en jour décimal) = Date de mandatement - Date de la demande

On part de la date de mandatement a quelle heure ? 12AM ou 12PM ?

**Comment by fb86** [comment]
retour apres le test :
- dans l'export il faudrait dissocier le nom et prénom.
- le format de séparation par une virgule nous met en difficulté par rapport à la saisie des montants et  base de remboursement qui s'alimentent en chiffre avec virgule,
- nous ne sommes pas parvenu à effectuer l'import, il a envoyé deux erreurs (cf slack).

**Comment by jpic** [comment]
Fait:
-    dans l'export il faudrait dissocier le nom et prénom.
-    le format de séparation par une virgule nous met en difficulté par rapport à la saisie des montants et base de remboursement qui s'alimentent en chiffre avec virgule,
-   nous ne sommes pas parvenu à effectuer l'import, il a envoyé deux erreurs (cf slack) -> detection automatique de charset
Plus:
dans la nouvelle version en staging, vous pouvez voir les calculs de cout theoriques en taxi, economie generee, et delais dans la page de detail de demande
Merci d'ouvrir de nouveaux tickets pour rapporter les bugs.
