### ISSUE TITLE
ETQ internaute je peux voir les stats MRS 

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#253]
Accessible via /stats (remplace dont l'iframe actuelle).

Statistiques affichées (peuvent être calculées qu'une fois par jour) :

* nombre de demandes traitées (validées + rejetées) cumulé depuis le début
* durée moyenne de paiement (en jours) - calculé sur toutes les demandes validées depuis le début
* nombre de bascule de TAP (Taxi/VSL) vers véhicule personnel (en demandes) correspondant à une économie sur le risque équivalent à XXXX € (utiliser la formule #252) 

Ces statistiques peuvent être filtrées par Caisse active.
Mettre la source des données (MRS), afficher "Données provenant de MRS" et la date de mise à jour des données affichées, afficher "MAJ le dd/mm/aaaa" en haut à droite.

Mockup du dashboard de stats pour le public :

![public](https://user-images.githubusercontent.com/91435/40059202-c61d9302-5853-11e8-8055-5585f71e9d78.jpg)

**Comment by fjg** [comment]
@notmoebius @fb86 pour relecture, modifications... à vous de jouer et d'enlever le tag "En préparation" :)

**Comment by notmoebius** [comment]
Mes remarques cosmétiques:
![image](https://user-images.githubusercontent.com/32330644/42085342-7327e872-7b90-11e8-9542-9caea610be1b.png)

**Comment by notmoebius** [comment]
le label des sélecteurs de dates sont en EN, possible de les avoir en FR ?
![image](https://user-images.githubusercontent.com/32330644/42085407-9e70cf08-7b90-11e8-91c4-a655ee31f945.png)

**Comment by jpic** [comment]
@notmoebius merci pour les remarques mais vont-elles vraiment dans cette issue ? :thinking: 
aussi si vous pouviez a l'avenir faire une issue par feature au lieu d'une issue par page avec toutes ces features, ca serait plus simple en terme de specs parce que je m'emmele pas mal les pinceaux, la je dois refaire encore du code j'avais pas compris parce que j'essaye de tout faire en meme temps

**Comment by jpic** [comment]
Fermeture en faveur de #463
