### ISSUE TITLE
Update RTM sur readthedocs

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#260]
Dans la tuto iframe, § Pré-requis: Ajouter un lien vers https://www.mrs.beta.gouv.fr/contact.

Ne pas connecter les mots vers le glossaire resdthedocs mais vers le glossaire github (https://github.com/betagouv/mrs/wiki)

**Comment by jpic** [comment]
Je sais pas comment faire pour lier le glossaire au wiki.

J'ai qu'a mettre, dans toutes les definitions de la page  de [glossaire](http://mrs.readthedocs.io/en/latest/glossary.html), "voir sur le wiki" ?

C'est assez triste :joy:

**Comment by fjg** [comment]
- lien vers la docs de l'iframe sur la cette page : https://github.com/betagouv/mrs/wiki/Int%C3%A9gration-du-formulaire-sur-site-tiers
- supprimer glossaire en double sur RTFD, et ajouter une phrase/lien vers github

**Comment by jpic** [comment]
Et voila le resultat ;)

![2018-07-09-154751_1162x660_scrot](https://user-images.githubusercontent.com/94636/42454425-cd1469ee-838f-11e8-943d-5f0cdb565c3d.png)
![2018-07-09-154659_1016x258_scrot](https://user-images.githubusercontent.com/94636/42454426-cd3a5a96-838f-11e8-810f-7f8c8fd17be8.png)
