### ISSUE TITLE
Progress bar not showing upon uploading file in '/demande'

### ISSUE THREAD

**Issue by angelo510** [betagouv/mrs#270]
When upload a file in /demande the progress bar is now showing because it's z-index is -1.
![issue-1](https://user-images.githubusercontent.com/23502859/38472005-348842ee-3b2e-11e8-9fab-57c31f28425e.png)

**Comment by jpic** [comment]
The screenshot is after upload, do you see the progress bar during upload ?

Is your issue on IE or all browsers ?

**Comment by fjg** [comment]
Same on desktop (chrome/firefox)

**Comment by jpic** [comment]
Pour moi c'est bon en staging !
![2018-04-14-035748_1014x385_scrot](https://user-images.githubusercontent.com/94636/38763270-27a4a554-3f98-11e8-916d-ab0db77ca565.png)
