### ISSUE TITLE
Bug affichage page formulaire en PWA

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#273]
sur IOS11 et avec Safari, lors de l'ouverture de mrs.beta.gouv.fr en mode PWA la page formulaire s'ouvre en mode "Lecture" du navigateur. Du coup, plus d'affichage du formulaire.

**Comment by jpic** [comment]
Je ne dispose pas du materiel, peux tu essayer la version sur l'instance jpic et me dire si c'est mieux stp ?

Merci

**Comment by Johan1983** [comment]
yes tcheck sur contact@mrs.beta.gouv.fr j'ai envoyé 2 captures

**Comment by Johan1983** [comment]
meme comportement sur l'instance jpic

**Comment by jpic** [comment]
Aucune erreur JS ne remonte.

**Comment by fjg** [comment]
ce n'est pas un pb JS mais un mode de navigation sur Safari. Je regarde si je trouve une solution, sinon je modifierai le manifest.json pour laisser afficher la barre d'adresse (afin que l'utilisateur puisse sortir du mode lecture de Safari).

**Comment by jpic** [comment]
@fjg feba47b ajoute une barre de navigation minimale, on la voie sur le screenshot aussi.

**Comment by jpic** [comment]
@fjg sur le screenshot le formulaire est hidden, c'est le js qui doit le display apres initialisation:

https://github.com/betagouv/mrs/blob/master/src/mrs/static/js/mrsrequest.js#L226

Si le js ne charge pas, ou qu'il y a une erreur JS, le formulaire ne s'affiche pas, c'est l'une des causes possibles.

**Comment by jpic** [comment]
Une piste ?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_scripts

**Comment by jpic** [comment]
@Johan1983 est-ce-que tu peux re-essayer vite fait sur jpic ? Merci <3

@fjg N'hesites pas a pusher sur la branche jpic, ca deploiera.

En cours, un deploiement avec un essai dans content_scripts

Ci joint les deux screens envoyes par @Johan1983, j'en deduis que le deuxieme c'est avec la conf display: minimal-ui (utilisee par soundslice.com):

![image1 1](https://user-images.githubusercontent.com/94636/38566387-d7597a18-3ce3-11e8-946c-7c258d57a7a9.png)
![image2](https://user-images.githubusercontent.com/94636/38566388-d78a4d6e-3ce3-11e8-80ae-938bc3f5ea2b.png)

Mais on peut essayer avec display: browser aussi

**Comment by fjg** [comment]
le 2nd est fait depuis safari directement, pas en mode pwa.

A priori, ca pourrait être une config de @Johan1983 et donc pas la config standard. A creuser avant de changer le code donc.

**Comment by jpic** [comment]
Si je comprends bien il faut mettre la main sur un deuxieme iphone avec les
versions de Johan ..

**Comment by fjg** [comment]
correct :)

**Comment by jpic** [comment]
Piste: https://developer.apple.com/documentation/safariextensions/safariextension/1635517-addcontentscript

**Comment by fjg** [comment]
Clos (ca fonctionne désormais)
