### ISSUE TITLE
Anomalie design dans le staging

### ISSUE THREAD

**Issue by Natacha1974** [betagouv/mrs#277]
A la page d'ouverture, fonctionnement, la phrase "3 étapes pour accélérer le remboursement..." n'est pas centrée dans l'encadrement blanc.
Je suis sur téléphone portable Android. 

![screenshot_20180413-205151](https://user-images.githubusercontent.com/94636/38754716-35ec5880-3f63-11e8-8eeb-67e50310f1e0.png)

**Comment by jpic** [comment]
Fix en staging: 
![2018-04-14-130528_517x242_scrot](https://user-images.githubusercontent.com/94636/38767600-a342fa98-3fe4-11e8-83a7-42af4fc652f8.png)

Concernant le Aujourd'hui, j'ai bien un fixe mais ca changera tres legerement le design:
![2018-04-14-130628_501x423_scrot](https://user-images.githubusercontent.com/94636/38767609-c3aeb164-3fe4-11e8-81f7-a4a4d3791fcf.png)

Est-ce-que c'est acceptable pour vous ou est-ce-que vous voulez qu'on cherche mieux ?

**Comment by Natacha1974** [comment]
Pour moi c'est bon !

**Comment by jpic** [comment]
![2018-04-17-054018_339x565_scrot](https://user-images.githubusercontent.com/94636/38847461-01adcf58-4202-11e8-9b02-8d51eb6ee57d.png)
