### ISSUE TITLE
Modifications dans le texte des mentions légales 

### ISSUE THREAD

**Issue by Natacha1974** [betagouv/mrs#278]
Dans la partie 2 "Objet du site internet mrs.beta.gouv.fr" : il faut mentionner à la fin : "... des assurés de la Haute-Garonne et de l'Ariège."

Dans la partie 3 "Données collectées", il faut rajouter : "...sont la prescription medicale  (volet 2) ou la demande d'accord préalable  (volet 3)...".

Dans la partie 7 "Obligations de l'utilisateur", il est fait mention que des modifications peuvent être faites mais qu'une date sera précisée si c'est la cas, donc créer cette date.
(Copies écran mises dans le slack)

**Comment by jpic** [comment]
Facile sauf pour la date, il faudra que je termine cette issue au dernier moment
