### ISSUE TITLE
[US] ETQ assuré, je peux saisir une demande de remboursement itérative

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#29]
Voici l'UX attendue/proposée pour cette version. Le texte sera revue avant la mise en prod évidemment, c'est indicatif à ce stade.

![img_5327](https://user-images.githubusercontent.com/91435/34718170-f50dd680-f535-11e7-80fa-2219a48c3774.JPG)

Reprendre comme base le formulaire de l'issue #11 et ajouter le champ à cocher après le champs de Date de trajet retour :

- Avez-vous des transports itératifs à déclarer ? [ ]

Si coché, ouvrir un panneau avec la question suivante :

- Combien de trajets itératifs souhaitez-vous déclarer ? [_____] (nombre entier positif, défaut: 1)

Lors de la modification de la valeur du champs "Combien de trajets...", construire *N-1* champs :

- date aller n°i [_______]
- date retour n°i [_______]

Lors de la modification du champs date aller, préremplir la valeur du champs date retour avec la valeur du champs date aller.

* En bas, modifier le champ *Distance (km) / Kilométrage total parcouru* en Distance *total* (km) de tous les trajets. 

Le modèle de données qui évolue pour gérer n trajet sur une demande.

**Comment by notmoebius** [comment]
@jpic Je reste à ta disposition pour répondre à toute question, je te laisserai mes coordonnées en DM sur slack.

**Comment by fjg** [comment]
Impacts Front :

* voici l'UX attendue/proposée pour cette version. Le texte sera revue avant la mise en prod évidemment, c'est indicatif à ce stade.

![img_5327](https://user-images.githubusercontent.com/91435/34718170-f50dd680-f535-11e7-80fa-2219a48c3774.JPG)

Impacts BO :

- [ ] voir les trajets itératifs (dates A/R) d'une demande qui en contient
- [ ] le mail envoyé à la liquidation devra contenir tous les documents comme pour une demande classique en pièces jointes avec les dates Aller/Retour des trajets itératifs
- [ ] pas de modification sur le refus et les mails de refus

Modèle de données qui évolue pour gérer n trajet sur une demande :

![img_5328](https://user-images.githubusercontent.com/91435/34718171-f543fd1e-f535-11e7-8de2-941106c91081.JPG)

**Comment by jpic** [comment]
@notmoebius Tu peux me dire ci tu penses que ça irait comme ça stp ?

![2018-01-16-180551_887x400_scrot](https://user-images.githubusercontent.com/94636/35001836-0d46ae36-fae8-11e7-9e46-c5db139250f5.png)
![2018-01-16-180501_697x390_scrot](https://user-images.githubusercontent.com/94636/35001837-0d68550e-fae8-11e7-90da-cef5fb655202.png)
![Uploading 2018-01-16-180450_788x494_scrot.png…]()

**Comment by jpic** [comment]
![2018-01-16-180450_788x494_scrot](https://user-images.githubusercontent.com/94636/35001868-257fce42-fae8-11e7-836d-ecdbeeff8921.png)
