### ISSUE TITLE
ETQ je peux traiter une demande : création du statut "en cours" évolution statut "validée"

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#292]
ETQ liquidateur : Lors du traitement d'une demande en statut "soumise" je peux faire évoluer le statut vers  :
- "en cours"  : la demande est en cours de liquidation par la caisse.
-"rejetée" : demande rejetée

Statut "**en cours** "
- Cette évolution nécessite la création d'un statut "en cours" pour le suivi des demandes.

Comme pour tous les changements de statut (action je traite, je valide, je rejette), l'historique est loggué et visible sur la vue d'une demande. On logue : qui, date, action (transition de vers) et le motif de rejet.

Le statut "en cours" peut évoluer vers le statut "validée" ou "rejetée"

Statut "**validée**" : le passage au statut validée entraine l'envoi du mail vers assurée pour confirmer paiement.
A : mail de l'assuré
De : contact@mrs...
Sujet : demande de remboursement "N° de la demande" traitée
Corps :
``````
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport en véhicule particulier concernant le(s) trajet(s) suivant(s) :
- " date des transports" 
Votre demande a été traité. le règlement vous sera versé dans quelques jours sur votre compte bancaire.

Pour toutes réclamations nous vous invitons à vous rapprocher de votre caisse d'assurance maladie : https://www.ameli.fr/assure/adresses-et-contacts/vos-paiements-vos-remboursements.

Cordialement,
L'équipe MRS - Assurance Maladie
``````

**Comment by jpic** [comment]
Si je comprends bien, l'utilisateureuse va saisir la demande dans le logiciel interne PROGRES et ensuite passer le statut de la demande à "en cours".

Est-ce-qu'on demande une info a l'utilisateureuse à ce moment là ? Par exemple, une info qui proviendrait de la saisie de la demande dans PROGRES (un autre ID peut-être ?)

**Comment by jpic** [comment]
![2018-04-25-190923_1198x256_scrot](https://user-images.githubusercontent.com/94636/39261313-5fe67852-48bc-11e8-861c-4f0baba9b11e.png)
Me reste juste qu'a changer une ligne de code pour avoir le motif de rejet mais la je cours pour le train ^^

**Comment by jpic** [comment]
Terminé par #314
