### ISSUE TITLE
tri par statut

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#300]
Sur IE 11 : le tri par statut ne fonctionne pas 

https://staging.mrs.beta.gouv.fr/newadmin/mrsrequest?q=&status=0&institution=&caisse=

**Comment by jpic** [comment]
Est-ce-qu'on peut avoir un peu plus de niveau de detail sur l'issue stp ?

**Comment by fb86** [comment]
sur Firefox lorsque tu selectionne un statut sur le menu déroulant (voir ci apres) cela entraine la selection automatique de toutes les demandes répondant à ce statut. Par exemple soumise.

et sur IE ca fonctionne pas. On peut choisir le statut mais l'ensemble des demandes restent affichées.

![issue statut](https://user-images.githubusercontent.com/34480111/39046690-8b8502b0-4486-11e8-9d9e-3a4f96e53b9a.GIF)

**Comment by jpic** [comment]
In progress
Tests d'anti regression multi navigateur, notamment IE, en cours sur yourlabs/crudlfap#45

**Comment by jpic** [comment]
Fixed #313
