### ISSUE TITLE
Bug affichage IE

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#308]
quelques bug d'affichages sous IE sur le front. J'ai fait des captures
- 3 etapes pour acceler... pas centrer en hauteur dans le bloc blanc
+ différence de taille de typo entre chaque bloc "Une semaine pour etre remboursé" " bloc "Hier/ aujourd'hui"
=> en gros harmoniser la taille de police dans tout les blocs.
- le texte des retours utilisateurs se chevauchent (+ grossir typo)
- le bloc "nous contacter"  est tout petit et le texte du bouton envoyer est pas centré
![decouvrez mrs mrs - internet explorer_2018-04-24_11-56-13_webdesign](https://user-images.githubusercontent.com/34479425/39182326-da99efa8-47bc-11e8-8234-7a3654d73f63.jpg)
![decouvrez mrs mrs - internet explorer_2018-04-24_11-56-47_verbatim](https://user-images.githubusercontent.com/34479425/39182327-dabe9c22-47bc-11e8-8b55-e72a6e1cefbb.jpg)
![decouvrez mrs mrs - internet explorer_2018-04-24_11-57-30_webdesign_contact](https://user-images.githubusercontent.com/34479425/39182328-dae6196e-47bc-11e8-8ac6-2c9b93179d96.jpg)

**Comment by Johan1983** [comment]
il y a les mentions legales aussi 
![mentions legales mrs - internet explorer_2018-04-24_11-32-34](https://user-images.githubusercontent.com/34479425/39238221-0083bf20-487e-11e8-90f1-159985a72b3a.jpg)

**Comment by jpic** [comment]
Ca m'a l'air tout bon
