### ISSUE TITLE
Redirection après connexion d'un agent007/bonjour31

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#316]
mauvaise redirection après login (depuis la page login après identification)

Login en liquidateur, voici la page qui s'affiche après connexion :

![capture d ecran 2018-04-26 a 12 03 32](https://user-images.githubusercontent.com/91435/39299809-eff498ec-4949-11e8-817f-9f6c25396733.png)

**Comment by jpic** [comment]
En staging
