### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#317]
Problème de détection de locale ? Voir toutes les captures ci-dessous

Pb de localisation de l'heure aussi cf. :

<img width="230" alt="capture d ecran 2018-04-26 a 15 49 16" src="https://user-images.githubusercontent.com/91435/39309972-7cc06354-4969-11e8-8d4e-f487b3932f4e.png">

**Comment by fjg** [comment]
![capture d ecran 2018-04-26 a 11 58 39](https://user-images.githubusercontent.com/91435/39299554-4042e610-4949-11e8-9ef1-a0192ca2dd0c.png)
![capture d ecran 2018-04-26 a 11 59 32](https://user-images.githubusercontent.com/91435/39299568-4dd42712-4949-11e8-87b6-7e6fd2b2b8fb.png)
![capture d ecran 2018-04-26 a 11 59 48](https://user-images.githubusercontent.com/91435/39299579-574905ec-4949-11e8-8fba-df65c591d9e8.png)

**Comment by notmoebius** [comment]
Bouton pour la déco
![image](https://user-images.githubusercontent.com/32330644/39299667-932abccc-4949-11e8-8e98-313125dc569d.png)

**Comment by notmoebius** [comment]
List en Liste,
Search en rechercher:
![image](https://user-images.githubusercontent.com/32330644/39299705-adb5d932-4949-11e8-82bc-d0aa2578fb6d.png)

**Comment by notmoebius** [comment]
Dans la mise à jour des caisses:
![image](https://user-images.githubusercontent.com/32330644/39299762-ce077eb6-4949-11e8-9bf8-154fdb29b997.png)

**Comment by notmoebius** [comment]
Bouton update:
![image](https://user-images.githubusercontent.com/32330644/39299789-de00bdc8-4949-11e8-82ad-4b48d8e614d8.png)

**Comment by notmoebius** [comment]
Menu en EN:
![image](https://user-images.githubusercontent.com/32330644/39299851-095c4104-494a-11e8-953b-68188bb8b122.png)

**Comment by notmoebius** [comment]
Idem pour les boutons du menu:
![image](https://user-images.githubusercontent.com/32330644/39300270-6d78ff5a-494b-11e8-9b92-076f09b3a1a1.png)

**Comment by notmoebius** [comment]
Idem pour les boutons actions:
![image](https://user-images.githubusercontent.com/32330644/39300408-dd801e0a-494b-11e8-8042-ffb7c21d0abc.png)

**Comment by jpic** [comment]
EN staging
