### ISSUE TITLE
ETQ liquidateur ne pas pouvoir filtrer les demandes sur d'autres caisses

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#322]
Le liquidateur étant associé à une caisse, ne peut voir que les demandes de sa caisse. Donc ne pas lui donner de possibilité de filtrer sur une caisse

![capture d ecran 2018-04-26 a 12 35 25](https://user-images.githubusercontent.com/91435/39301110-54b63494-494e-11e8-847f-f1df1cea55dd.png)

**Comment by jpic** [comment]
Cette demande est elle vraiment compatible avec la demande https://github.com/betagouv/mrs/issues/244 qui permet d'affecter un utilisateur a plusieurs caisses ?

**Comment by fjg** [comment]
Bonne remarque.
Effectivement je ne me souvenais pas que les utilisateurs pouvaient avoir plusieurs caisses. Donc fait au plus simple, si tu as masqué le filtre, laisse comme ca, sinon laisse le visible.

**Comment by jpic** [comment]
Honnetement je ne sais pas a quel besoin ca repond mais j'avais tellement de backlog je l'ai juste fait.

**Comment by jpic** [comment]
Je parlais d'assigner plusieurs caisses a un utilisateur.
