### ISSUE TITLE
Mettre en popin toutes les actions (validation/rejet) en agrandissant la popin/modal pour utiliser la largeur de la vue d'une demande

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#325]
- [ ] cas de la validation
- [ ] cas du rejet

**Comment by jpic** [comment]
Est-ce-qu'on peut avoir la version "user story" de cette demande stp pour voir si il n'y pas une autre meilleure option technique stp ?

**Comment by fjg** [comment]
Homogénéiser toutes les actions de confirmation (changement d'état, ...). Actuellement certaines sont en popin, les autres pas, certaines ont les boutons d'action visibles, d'autres il faut scroller...

Donc en résumé :

- confirmer les actions (passer en cours de liquidation, rejeter, valider, ...)
- la confirmation doit permet de lire le descriptif de l'action et les informations associées, elle doit aussi afficher la possibilité d'annuler l'action ou de la confirmer. L'action doit être facilement visible et accessible.
- homogénéiser les comportements pour ne pas avoir deux comportements différents sur des actions similaires (risques d'erreur...)

Plus clair ?

**Comment by jpic** [comment]
Les pages qui ont des boutons d'actions visibles sans scroll sont plus courtes que les pages qui ont besoin qu'on scroll pour voir le bouton d'action, si c'est un probleme on peut bien sur fixer le bouton d'action en bas de page, cependant si l'utilisateur rate la moitié de la page parce qu'il ne pense pas a scroller alors ca sera contre production.

Je ne comprends pas, je croyais que tu voulais qu'on fasse des modals plus grande, tu veux qu'on scroll a l'interieur de la modal ? L'UX va etre encore pire.
Si il faut scroller dans une page sans modal, comment est-ce-que mettre la dite page dans un espace encore plus restreint que celui de la modal pourra empecher le scroll je ne sais pas.

Sur internet, on scroll pour voir le contenu qui depasse, et y'a rien qu'on ne puisse faire pour l'empecher si ce n'est reduire les espaces blancs et les tailles de polices.

**Comment by fjg** [comment]
Dis nous ce qui est le mieux pour l'utilisateur ou le code. Ton avis compte. Donc si c'est modal, on part sur modal, sinon sur des pages.
Le principale c'est que le comportement soit homogène et pas un coup modal, un coup page. Trop de risque d'erreur.
En dehors de ca on teste et on verra. J'ai pas de religion ;)

**Comment by jpic** [comment]
Si c'est pour homogeneiser, autant retirer les modals. C'est pas encore pret, j'ai pas eu le temps de bien faire les redirects.

**Comment by jpic** [comment]
C'est toujours en cours en staging.

**Comment by jpic** [comment]
En staging.
![2018-05-15-190255_1914x953_scrot](https://user-images.githubusercontent.com/94636/40072028-c4547134-5872-11e8-9bf8-0a4ce833b773.png)
![2018-05-15-190357_1896x936_scrot](https://user-images.githubusercontent.com/94636/40072068-e510f302-5872-11e8-84a1-62327605e907.png)
