### ISSUE TITLE
Statut (groupe) des utilisateurs

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#328]
Il n'y a que 2 types d'utilisateurs du BO : 

- Super utilisateur => Admin
- Statut Équipe => UPN

Ne pas afficher "Statut" dans le header, juste le nom du profil :

<img width="466" alt="capture d ecran 2018-04-26 a 14 29 18" src="https://user-images.githubusercontent.com/91435/39305699-4598a59a-495e-11e8-97c3-6f999b6ce501.png">

**Comment by jpic** [comment]
Fixé en staging
