### ISSUE TITLE
Inversion des item de menu dans l'admin

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#330]
les items de menu ne sont pas dans le même ordre:
![image](https://user-images.githubusercontent.com/32330644/39306562-c9845bcc-4960-11e8-9e4a-6fcf71b9c979.png)

et l'autre item, create et list sont inversés:
![image](https://user-images.githubusercontent.com/32330644/39306585-ddf170a4-4960-11e8-9b3c-3fc12f59646d.png)

**Comment by jpic** [comment]
Groupe est parti
