### ISSUE TITLE
Historique d'une demande : ajouter l'état de création

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#335]
Dans la vue d'historique d'une demande, on ne voit pas la création (étape soumise par l'assuré), l'ajouter

**Comment by jpic** [comment]
J'ai tout mis sur la premiere ligne de la page demande
![2018-04-30-184447_1334x858_scrot](https://user-images.githubusercontent.com/94636/39439101-bf63bf2c-4ca6-11e8-88b2-985789be8687.png)
