### ISSUE TITLE
Affichage en EN

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#350]
Sur l’interface d’admin, lors de l’absence validation, rejet ou suppression, la fenêtre modale affiche les labels en anglais ainsi que le bouton d’action.
![ca28e750-24a7-49e8-9828-851e7c4aabdd](https://user-images.githubusercontent.com/32330644/39468303-a82e07c2-4d32-11e8-8326-f48742eed886.jpeg)

**Comment by jpic** [comment]
Desole pour moi template c'etait un terme francais, je m'occuppe de ca et je te fais un courriel :joy:
