### ISSUE TITLE
Calcul automatique de la base de remboursement 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#372]
ETQ  liquidateur je peux voir la base de remboursement sur la demande de l'assuré.
Le calcul se fait en multipliant le nombre de km par 0,30 centimes.

**Comment by notmoebius** [comment]
Je joins un modèle pour afficher le montant des kilomètres parcours soit nb km total * à 0,30€ TTC.
![image](https://user-images.githubusercontent.com/32330644/40044980-5852aecc-5829-11e8-911d-9725636bea59.png)

**Comment by notmoebius** [comment]
"Montant des KM parcourus" est juste le calcul du nb de km par 0.30€.
Montant total des frais est la somme des PJ (donc différent de montant KM+ montant des PJ).
Les liquidateurs ont besoin du calcul pour faciliter leur saisie.
