### ISSUE TITLE
Le visualiseur d'image ne s'ouvre pas pour les PDF

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#375]
En prod, les documents PDF ne s'ouvrent pas mais  pour les images c'est OK.
Toutes les images jpeg ou autre fonctionnent ainsi que la rotation mais les PDF ne s'ouvrent pas et c'est en attente de chargement.
![image](https://user-images.githubusercontent.com/32330644/40050783-be4a9730-5838-11e8-887f-1f8c968d3b58.png)

**Comment by fjg** [comment]
pour cette version ne pas convertir les pdfs, juste les exclure du visualisateur JS et laisser le navigateur les ouvrir.
