### ISSUE TITLE
Ajouter adeli au vocabulaire

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#400]
coucou !

est-il possible d'ajouter adeli au wiki de vocabulaire svp ?

merci <3

**Comment by notmoebius** [comment]
Job Done

**Comment by jpic** [comment]
Merci !

Du coup il peut y avoir plusieurs ADELI differents pour un FINESS ?

**Comment by jpic** [comment]
Aussi, il y a bien un seul ADELI par CPS ?
