### ISSUE TITLE
[issue 252] Wrong target

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#403]
La cible à exporter est toutes les demandes dans le statut est **validée**. hors dans le staging, il y a des demandes rejetées: exemple demande n° 201801150002 ou 201801150004 !
Il faut appliquer le filtre demande validé (voir issue #252 , c'est précisé).

**Comment by jpic** [comment]
#252 precise aussi:

    la colonne Date de mandatement peut être vide (soit pas encore traitée, soit parce que rejetée au paiement)

Donc, validees ou en cours de liquidation ?
