### ISSUE TITLE
Bug sur calcul délai moyen et économie

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#435]
En date du 23/01/2018 : il ne faut tenir compte que des demandes validées (4 demandes ce jour là) pour ces deux métriques

<img width="1352" alt="capture d ecran 2018-06-26 a 12 38 55" src="https://user-images.githubusercontent.com/91435/41906442-24925638-793e-11e8-935c-e1814b7bc3eb.png">

**Comment by jpic** [comment]
A priori ca serait corrige en staging (#447)
