### ISSUE TITLE
Bug calcul montant d'économie entre 2 dates

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#436]
Entre le 23/01/2018 et 23/01/2018, le calcul de l'économie est à 0 alors qu'il devrait tenir comptes des 4 demandes validées et liquidées.
Il faut intégrer les heures 0:00 sur la borne mini, et 23:59 sur la borne maxi.

<img width="1352" alt="capture d ecran 2018-06-26 a 12 38 55" src="https://user-images.githubusercontent.com/91435/41906346-ed30e574-793d-11e8-9088-70eff6287c01.png">

**Comment by jpic** [comment]
Corrigé par #447
