### ISSUE TITLE
Migration : statut final manquant sur les demandes historiques

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#440]
Avant le statut 'en cours de liquidation', on ne logguait pas les changements de statut. Sur cette demande (cf. capture), l'interface semble indiquer qu'elle est **Soumise** alors que la demande est validée.
Ajouter un statut Validée/Rejetée pour les anciennes demandes.

<img width="1281" alt="capture d ecran 2018-06-26 a 14 05 38" src="https://user-images.githubusercontent.com/91435/41910534-3c92470a-794a-11e8-8a9d-b989a8760d13.png">

**Comment by jpic** [comment]
Elles y sont deja, sauf pour les demandes pour lesquelles on a pas de date de validation (avant qu'on mette la colonne status_datetime).

**Comment by jpic** [comment]
Du coup, pour les demandes tellement anciennes qu'on a pas de date de validation, comment tu veux que je procede ? Serait-il possible de recuperer les dates / heures de validations a partir de la boite mail d'envoie ?
D'avance merci

**Comment by fjg** [comment]
@notmoebius ou @fb86 vous pensez qu'on peut récupérer ces dates, nécessaire, intéressant, ca impacte les stats ou pas ?

**Comment by jpic** [comment]
J'ai un script temporaire qui les ajoute, j'ai appliqué en staging, j'appliquerais en prod apres la MEP.

**Comment by jpic** [comment]
Mis en prod, livre dans le repo secret d'inventaire avec l'autre script d'injection de data one-shot (pour le concours de beaute de code on repassera :joy:)
