### ISSUE TITLE
Ajouter une licence au projet

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#449]
Choisir et clarifier la licence du code du projet MRS

**Comment by jpic** [comment]
Je ne comprends pas, je dois choisir la license ?

**Comment by fjg** [comment]
Non, l'idée est d'en discuter et de préciser la licence retenue.

**Comment by notmoebius** [comment]
Choix AGPLv3 préconisé par beta.gouv me semble convenir.
@jpic utilises-tu des produits qui ont une licence particulière
