### ISSUE TITLE
Le dépôt git ne peut pas être cloné sous Windows

### ISSUE THREAD

**Issue by marmoko** [betagouv/mrs#454]
Sous Windows 10 avec git-bash, le dépôt ne peut pas être cloné :

[clone.txt](https://github.com/betagouv/mrs/files/2156416/clone.txt)

C'est dû à la présence de caractères spéciaux dans le nom de certains fichiers.

Serait-il possible d'utiliser des noms de fichiers compatibles avec NTFS ?
https://docs.microsoft.com/fr-fr/windows/desktop/FileIO/naming-a-file#naming-conventions

J'ai pu installer sans problème les dépendances de MRS, mais j'ai été surpris de bloquer au niveau du clonage de répo :-)
De la même manière, télécharger et extraire l'archive zip pose des problèmes.

Merci !

**Comment by jpic** [comment]
Merci pour le retour, le logiciel n'est pas encore testé sous windows faute de contributeureuse, effectivement c'est stupefiant !

Pour info, c'est du aux fichiers de tests automatiquements generé par le crawler de django-responsediff. Celui ci traverse le site et enregistre les requetes / responses ainsi que quelques metadonnees telles que le nombre de requetes executees. Et bien entendu, il reproduit chaque url sur le systeme de fichier. Visiblement, une telle opération est rendue impossible par windows qui a decidé d'exclure certains caracteres arbitrairement.

Du coup, je ne voie pas de solution immediate, si ce n'est utiliser une VM Linux, ou peut etre une partition ext (le driver est libre pour windows) qui passera peut-etre au travers des conventions de nommages enforcees par windows. Cela dit, maintenant qu'on a connaissance du probleme on peut commencer a y reflechir, mais sauf si on decide de retirer tous ces tests qui couvrent une belle partie du code automatiquement, il faudra ouvrir un ticket sur django-responsediff, proposer une solution et un patch.

Nous evoquerons le pb en standup demain et vous tiendrez au courant, d'avance merci pour toute nouvelle idee / piste que vous pourrez proposer.

**Comment by jpic** [comment]
Est-ce-que ca marche avec un sparse checkout en excluant src/mrs/tests/response_fixtures ?

**Comment by jpic** [comment]
Je pense qu'un replace la dedans devrait permettre de supporter les limitations de Microsoft Windows:

https://github.com/yourlabs/django-responsediff/blob/a6147678515bde39e9cfd04a5799ee5156a56014/responsediff/response.py#L133-L144

Si vous voulez proposer un patch la dedans y'a aucun probleme pour le merger. Il faudra surement ajouter un test avec un chemin qui contient `?`. Suite au merge je ferais la release, et je mettrais a jour les fixtures dans le repo mrs.

**Comment by jpic** [comment]
A tout hasard voici la liste des dossiers du repo sans le dossier responsediff, au cas ou ce soit possible de configurer le sparse en texte:

```
$ find * -type d | grep -v response_fixtures
docs
src
src/mrsattachment
src/mrsattachment/templates
src/mrsattachment/templates/material
src/mrsattachment/templates/material/fields
src/mrsattachment/templates/mrsattachment
src/mrsattachment/migrations
src/mrsattachment/tests
src/caisse
src/caisse/templates
src/caisse/templates/caisse
src/caisse/migrations
src/institution
src/institution/templates
src/institution/templates/institution
src/institution/migrations
src/institution/tests
src/contact
src/contact/templates
src/contact/templates/contact
src/webpack_mock
src/webpack_mock/templatetags
src/person
src/person/migrations
src/person/tests
src/mrsemail
src/mrsemail/templates
src/mrsemail/templates/admin
src/mrsemail/templates/admin/mrsemail
src/mrsemail/migrations
src/mrsuser
src/mrsuser/migrations
src/mrsrequest
src/mrsrequest/jinja2
src/mrsrequest/jinja2/mrsrequest
src/mrsrequest/templates
src/mrsrequest/templates/mrsrequest
src/mrsrequest/migrations
src/mrsrequest/tests
src/mrs
src/mrs/jinja2
src/mrs/jinja2/crudlfap
src/mrs/management
src/mrs/management/commands
src/mrs/locale
src/mrs/locale/fr
src/mrs/locale/fr/LC_MESSAGES
src/mrs/templates
src/mrs/static
src/mrs/static/sass
src/mrs/static/img
src/mrs/static/img/3-etapes
src/mrs/static/img/logos
src/mrs/static/img/icones
src/mrs/static/js
src/mrs/static/js/controllers
src/mrs/static/js/components
src/mrs/tests
src/mrsstat
src/mrsstat/jinja2
src/mrsstat/jinja2/mrsstat
src/mrsstat/management
src/mrsstat/management/commands
src/mrsstat/migrations
```

**Comment by jpic** [comment]
Microsoft me le paiera un jour :joy:
https://github.com/yourlabs/django-responsediff/commit/a5604c1a69b9d300e02f55a6110412ecd46e4c05

**Comment by jpic** [comment]
Question soumise en upstream : https://answers.microsoft.com/en-us/windows/forum/windows_7-files/allowed-caracters-on-filesystem/881a9fa0-9fd4-484b-a03b-2ccada77ae0b?tm=1548714710658
