### ISSUE TITLE
ETQ admin, voir le nbre cumulé de demandes soumises

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#455]
Sous le graph actuel, ajouter un graph pour voir le cumul de demandes soumises correspondant aux filtres saisies (date début/fin, caisse, établissement).

**Comment by jpic** [comment]
Faut il que ce soit sur la meme page ?

Merci

**Comment by fjg** [comment]
oui si possible, sinon 2 pages si c'est plus simple ou nécessaire (perf ou autre contrainte...)
