### ISSUE TITLE
Filtre plante sur la page utilisateurs

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#458]
Sur la page utilisateurs, il est possible de rechercher et de filtrer. Le filtre par caisse plante (sentry se déclenche).
En fait, il ne peut pas filtrer sur la caisse, rien ne se déclenche à l'affichage et provoque une erreur sentry.
![image](https://user-images.githubusercontent.com/32330644/42218394-b618f064-7ec8-11e8-93f2-ff9f08874527.png)

**Comment by notmoebius** [comment]
En revanche, si je filtre en premier par la statut puis par la caisse, c'est bon.

**Comment by jpic** [comment]
@notmoebius merci pour cette precision, si je m'en etais servi j'aurais trouvé bcp plus vite .... mais je cherchais ailleurs comme un perdu et au final c'etait ca, la fonction de filtre par statut retournait rien quand aucun statut n'etait selectionne, elle aurait du retourner la queryset originale.
