### ISSUE TITLE
ETQ internaute je peux voir les stats MRS (was: #253)

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#463]
Sur l'URL /stats:

- [ ] enlever l'iframe
- [ ] afficher: nombre de demandes traitées (validées + rejetées) cumulé depuis le début
- [ ] afficher: durée moyenne de paiement (en jours) - calculé sur toutes les demandes validées depuis le début
- [ ] afficher: nombre de bascule de TAP (Taxi/VSL) vers véhicule personnel (en demandes)
- [ ] afficher: correspondant à une économie sur le risque équivalent à XXXX € (utiliser la formule #252)
- [ ] afficher: selection de Caisse pour filtrer les resultats ci dessus
- [ ] afficher: libellé: "Données provenant de MRS"
- [ ] afficher: date / heure du calcul des statistiques

**Comment by notmoebius** [comment]
dans le pavé NB de dem traitées, il manque la décomposition (en légende): (validées/Rejetées).
![image](https://user-images.githubusercontent.com/32330644/42379868-7be5d04a-812c-11e8-9f36-81769de388a6.png)

**Comment by notmoebius** [comment]
A mon sens, mais nous l'avions pas mis dans les specifs, il manque le nombre d’utilisateur du service.
![image](https://user-images.githubusercontent.com/32330644/42380013-c6d8010e-812c-11e8-8e56-2fd071d4f23e.png)
Il me semble que c'est la table "person", à confirmer. Cela correspond au nombre distinct de personnes ayant fait une demande.

**Comment by jpic** [comment]
les specs indiquaient clairement un chiffre validees + rejettees, et non deux chiffres un pour les validations et un pour les rejets. Est-ce-que tu peux faire des nouvelles issues stp ?

![2018-07-06-145512_858x101_scrot](https://user-images.githubusercontent.com/94636/42380058-eef06fd2-812c-11e8-86de-368ccdd3ec39.png)
![2018-07-06-145507_461x350_scrot](https://user-images.githubusercontent.com/94636/42380059-ef1376da-812c-11e8-82d5-d9efc8eae5b8.png)

**Comment by notmoebius** [comment]
Oui, je suis d'accord. Je parle de  la légende à ajouter (Validées/Rejetées) pas les chiffres en eux mêmes.
