### ISSUE TITLE
Bug affichage en résolution écran 2560X1440pix

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#473]
J'ai testé le site en plein écran navigateur et les textes de la promesse (cartouche vert) ne sont plus lisibles. J'ai fait des captures écrans. Aussi bien sur Chrome version 67 que sur Safari 11.1.1.

Il faudrait revoir le web design de ce bloc afin qu'il soit plus lisible et adaptable à tous les formats.
(intégration dans bloc du dessous, bloc spécifique qui fait toute la lar
![capture-chrome67-2560x1440pixels](https://user-images.githubusercontent.com/34479425/42443442-c17799f2-836d-11e8-9a18-09779bfd4270.png)
geur)

A discuter sur un mardi

**Comment by jpic** [comment]
C'est commencé, je m'en sors ;)

**Comment by jpic** [comment]
on a ca dans le pipe, pour aujourd'hui ;)
![2018-10-01-174501_1082x458_scrot](https://user-images.githubusercontent.com/94636/46299759-579bc400-c5a2-11e8-8e2c-6eb9cf4bb7d3.png)
![2018-10-01-174446_1206x801_scrot](https://user-images.githubusercontent.com/94636/46299760-579bc400-c5a2-11e8-8828-6e71b1c457be.png)

**Comment by notmoebius** [comment]
ok pour grand écran
