### ISSUE TITLE
Amélioration affichage de stats internaute #463

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#476]
Refaire une passe sur les libellés
Valider les chiffres
Revoir l'esthétique de présentation

**Comment by Johan1983** [comment]
voici le nouveau modèle de présentation des stats défini ce mardi 
la photo en pj pour la présentation.
Les libellés sont les suivants :

1. Nombre d'assurés
2. Nombre d'assurés ayant basculé vers le véhicule personnel*
3. Nombre de demandes traitées (validées/ rejetées)
4. Nombre de demandes d'assurés ayant basculés
5. Délai moyen de traitement
6. Economies réalisées**

*Assuré utilisateur de Transport Assis Professionnalisé (TAP) ayant basculé vers le Véhicule Particulier (VP) depuis la mise en oeuvre de MRS
** Différence entre le coût théorique d'un TAP et le montant pris en charge au titre du VP pour les assurés ayant basculés.

![img_4367](https://user-images.githubusercontent.com/34479425/42828871-4a732ca4-89e9-11e8-957b-8263847692be.JPG)

**Comment by jpic** [comment]
Merci, que representent les fleches et les numeros en fait ?

**Comment by jpic** [comment]
Mais il faut faire quoi en fait ? Merci

**Comment by Johan1983** [comment]
@jpic : en fait il s’agit d’une reorganisation de la présentation des stats côté utilisateurs.
Ainsi qu’une précision des termes à utiliser.
Le schéma est un croquis de la presentation souhaitée. Comme il y a eu des modifs (les fleches) j’ai ajouté des numeros (en rouge) ainsi qu’une grille indiquant le placement de ces numéros

**Comment by jpic** [comment]
Petit problème: les longs libellés ne vont pas loger dans les carrés, je passe à une stat par ligne plutot ?

**Comment by jpic** [comment]
- [ ] changer: libellés
- [ ] changer: ordre de présentation
- [ ] ajouter: légendes (étoiles)
- [ ] ajouter: nombre de demandes d'assurés ayant basculés
