### ISSUE TITLE
US Créer un profil d'accès STATS

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#483]
ETQ agent des stats de la caisse : 
- [x]  j'ai accès **uniquement** au menu Stats.
- [x] j'exporte un fichier de stats MRS au format CSV avec les attributs issue #252 
- [x] j'importe le fichier alimenter par mon service stats avec les éléments : Date de mandatement (JJ/MM/AAA), Base de Remboursement (Montant en euros), Montant remboursé (Montant en euros), Assuré qui bascule (1 pour basculé/0 pour non basculé), n° finess du prescripteur (9 caractères), n° adeli du prescripteur
- [x] il n'est pas possible de créer un compte utilisateur avec le rôle Stats sans 1 ou plusieurs caisses de rattachement. Il faut rejeter la demande en demandant à l'utilisateur (admin qui crée le compte ou met les droits) de préciser la ou les caisses de rattachement. I.e. seul un admin peut ne pas avoir de caisse de rattachement.

Le profil Stats permet d'importer uniquement les données de la ou les caisses auxquelles il est rattaché.

Les items du menu Stats disponibles sont :
- Import/Export cette [page](https://www.mrs.beta.gouv.fr/admin/stat/importexport)
- List affiche les stats de ma caisse (pas de filtre de caisse à afficher) cette [page](https://www.mrs.beta.gouv.fr/admin/stat/importexport)
- le menu home
- la page de connexion et déconnexion

**Comment by notmoebius** [comment]
@fjg @fb86 si vous voulez avoir une relecture attentive ! Merci d'avance.

**Comment by jpic** [comment]
@notmoebius pour l'instant, nous sommes parti sur une relation many to many entre utilisateur et caisses. Donc a priori, il faut partir du principe que l'utilisateur peut être dans plusieurs caisses. Donc, afficher les stats de ses caisses ?

Aussi pour l'instant, 1 met le flag bascule, 0 l'enleve, et chaine video ne touche pas. Est-ce-qu'il faut changer ?

Merci

**Comment by notmoebius** [comment]
J'ai pas compris 

> "chaine video",

 c'est quoi ?

Je comprends bien le many to many mais lors de la création de l’utilisateur, on demande un choix de caisse. Peut-être tu peux utiliser cette information pour poser un filtre (que l'agent Stats ne voit pas) et affiche uniquement les stats de sa caisse. Est-ce possible ?

**Comment by fjg** [comment]
pour le 1/0 ou 1/vide on ne change pas. Actuellement c'est 1/vide.

**Comment by fjg** [comment]
Pour la caisse, ca signifie que pour un rôle Stats, il faudra forcément définir la caisse de rattachement. Pas d'utilisateurs Stats sans caisse, c'est bien ca @notmoebius ?

**Comment by jpic** [comment]
Je crois qu'il faut qu'on ait une petite discussion sur la structure de la base de données, afin qu'on parle de la même chose.

Aujourd'hui, il n'est pas possible d'assigner seulement une caisse a un utilisateur, on peut lui en assigner plusieurs. Mais c'est pas grave, je me débrouillerais avec. A moins que vous ne vouliez selectionner les permissions par caisses auquel cas c'est un autre problème d'une autre envergure.

Pour les bascules, c'est actuellement implémenté comme j'ai dis: https://github.com/betagouv/mrs/blob/master/src/mrsrequest/crudlfap.py#L334-L339

- 1 active la bascule
- 0 desactive la bascule
- vide ne touche pas

**Comment by fjg** [comment]
1 ou plusieurs ne change pas la question que je posais. Faut-il forcément avoir une caisse pour un utilisateur avec le rôle Stats tel que défini ?
0 caisse possible ou pas ?
1 caisse (ou +) forcément ou pas ?

A @notmoebius de décider.

**Comment by notmoebius** [comment]
HI,
@fjg Je reformule pour bien comprendre: un profil/rôle stats, tu lies une caisse et un utilisateur. Oui, c'est ça. Cas d'usage: un agent stats d'Auch, je lui donnes un rôle/profil stats, il importe et exporte les données de sa caisse uniquement (filtre sur sa caisse) et voit les stats de sa caisse. C'est comme actuellement pour la consultation des stats avec un filtre sur la caisse.
![image](https://user-images.githubusercontent.com/32330644/42554338-c9cf0158-84e4-11e8-8d9d-335ad2d0f0e7.png)

Je suis dispo vers 9h30-10h pour en rediscuter.

**Comment by notmoebius** [comment]
Concernant many to many pour assigner un utilisateur à une caisse, c'est à notre main et à nous d'être vigilant. Ce cas de plusieurs caisses par utilisateur peut éventuellement se rencontrer dans des caisses qui mutualisent des activités. Pas en Occitanie.

**Comment by notmoebius** [comment]
@fjg @jpic 
Faut-il forcément avoir une caisse pour un utilisateur avec le rôle Stats tel que défini ? **OUI**
0 caisse possible ou pas ? **NON**
1 caisse (ou +) forcément ou pas ? **OUI**, oui un utilisateur doit forcément avoir une caisse, du moins en admin, nous lui associons au moins une caisse.

**Comment by notmoebius** [comment]
@jpic Pour les bascules: 
1 active la bascule
0 ou vide ne touche pas
Vu avec Fred ce jour.

**Comment by jpic** [comment]
Est-ce-que c'est possible d'avoir un ticket séparé pour le changement de spec sur l'import svp ?

**Comment by fjg** [comment]
Où est-ce que ca change qq chose sur l'import ?
En l'état ce que tu as fait est ok avec ce qui est demandé dans la milestone Stats.
Par contre le rôle Stats introduit par cette nouvelle US changera cf ce qui est discuté/décrit ici non ?
Pkoi un autre ticket ? (dsl j'ai probablement raté qqch)

**Comment by jpic** [comment]
Est-ce-qu'on decide d'assigner des roles par caisses ?

**Comment by fb86** [comment]
Que veux tu dire par assigné des rôles au caisses ? 




Télécharger Outlook pour Android







On Wed, Jul 11, 2018 at 8:14 PM +0200, "∞" <notifications@github.com> wrote:












Est-ce-qu'on decide d'assigner des roles par caisses ?

**Comment by fjg** [comment]
A ce jour, 1 utilisateur = 1 rôle dans 1 caisse

**Comment by fjg** [comment]
A ce jour, le besoin est le suivant dans les relations :

1 utilisateur = peut avoir 1 seul rôle pour plusieurs caisses.

Exemple type : un utilisateur technicien de Toulouse avec le rôle "relation client" peut pouvoir regarder les demandes du 31 et du 09.

**Comment by fjg** [comment]
US mise à jour avec ces éléments

**Comment by jpic** [comment]
c'est deja principalement sur staging, on va pouvoir terminer auj :joy:

**Comment by jpic** [comment]
In staging ;)
