### ISSUE TITLE
Erreur en filtrant la colonne statut - accès admin Ecran utilisateur/list

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#484]
Sur la page : https://www.mrs.beta.gouv.fr/admin/user?sort=status en triant par statut (en colonne)
![image](https://user-images.githubusercontent.com/32330644/42557955-26c6e5a0-84f0-11e8-9b73-31ba88c96e42.png)

J'ai une erreur 500 sur la prod, même erreur en staging.

**Comment by jpic** [comment]
Et oui, on ne peut pas trier sur une colonne qui n'existe pas en db ;)

**Comment by notmoebius** [comment]
Dac, je viens de comprendre que c'est pas implémenté.
Ya moyen de la trappée pour éviter le '500' ?

**Comment by jpic** [comment]
Oui il suffit de marquer la colonne custom comme non sortable a mon avis, ou implementer un sort mais je sais pas ce que ca va donner, je te tiens au courant des que je termine de proprer la data de prod ;)

**Comment by jpic** [comment]
Fixed, c'est triable avec le nouveau champs de profil ;)
