### ISSUE TITLE
Placeholder en cas d'erreur du formulaire

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#485]
Constat des caisses en base école ou en prod: si le formulaire (cette [page](https://www.mrs.beta.gouv.fr/demande)) a une erreur après avoir tenté de le soumettre, le message d'avertissement pour la PMT/DAP manquante n'est pas mis en surbrillance rouge.

Pour les autres champs, c'est bien mis en évidence et surbrillance:
![image](https://user-images.githubusercontent.com/32330644/42558869-cbe6b388-84f2-11e8-9103-dd5cf19810c8.png)

Est-il possible de le mettre en évidence ?
Le retour utilisateur: il n'ont pas su voir quel champ de saisie posé problème. Merci.

**Comment by jpic** [comment]
Contribution upstream: https://github.com/Dogfalo/materialize/pull/6033
