### ISSUE TITLE
US création d'un profil "relation client"

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#486]
Objet: le profil "relation client" permet aux utilisateurs bénéficiant de ce profil de se connecter à MRS admin et de pouvoir suivre le traitement des dossiers. Il s'agit d'un profil similaire à profil liquidateur sans la capacité de modifier (valider/rejeter...) un dossier.

A faire : 
- [x] 1- créer un profil permettant à l'utilisateur de pouvoir voir l'ensemble des demandes (soumise, en cours, validée ou rejetée) de l'organisme de l'utilisateur (1 ou plusieurs caisses). Attention ce profil ne permet pas de traiter les demandes (en cours de liquidation/valider/rejeter/supprimer/modifier...) - i.e. *lecture seule*.
- [x] 2- permettre à un administrateur d'attribuer un login et mot de passe à l'utilisateur et le profil RC (Relation client) ainsi que la ou les caisses de rattachement.
- [x] il n'est pas possible de créer un compte utilisateur avec le rôle Stats sans 1 ou plusieurs caisses de rattachement. Il faut rejeter la demande en demandant à l'utilisateur (admin qui crée le compte ou met les droits) de préciser la ou les caisses de rattachement. I.e. seul un admin peut ne pas avoir de caisse de rattachement.

Le profil "relation client" permet de voir uniquement les demandes de la ou les caisses auxquelles il est rattaché.

Cas d'usage:
- permettre de rechercher une demande 'plain text' avec le champ "Rechercher"
- filtrer par statut de la demande
- filtrer par établissement
- filtrer par période de date à date (utile pour les contrôleurs)
![image](https://user-images.githubusercontent.com/32330644/42562543-484549f4-84fc-11e8-9728-0ce50f5f58a2.png)

- [x] Le menu sandwich doit ouvrir uniquement le détail:
![image](https://user-images.githubusercontent.com/32330644/42563056-95be41bc-84fd-11e8-967e-4eb354eb4945.png)

- [x] Les cases à cocher ne sont plus nécessaires.

**Comment by jpic** [comment]
en staging
