### ISSUE TITLE
Erreur 500 sur l'export - AttributeError: 'NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#492]
Depuis la dernière maj, l'export ne fonctionne plus.

**Comment by jpic** [comment]
Ne fonctionne plus alors ?

**Comment by jpic** [comment]
Ah bin c'est la spec qui n'est plus compatible avec les datas qu'on a inseré la semaine derniere.

**Comment by fjg** [comment]
Idem en staging pour info

**Comment by jpic** [comment]
Ah bin c'est normal puisque j'ai fais tout ce qu'il fallait pour qu'on bosse en staging et au lieu de direct en prod.

**Comment by jpic** [comment]
Ah bin ca c'est sur, "None" n'a pas d'attribut strptime :joy:

**Comment by jpic** [comment]
Du coup vous voulez gerer ce cas comment exactement ?

**Comment by fjg** [comment]
on avait corrigé les dates de départ non ? Il y a encore des dates de départ non correctes ?

**Comment by fjg** [comment]
Normalement, pas de demandes validées sans date de départ, ca n'est pas possible fonctionnellement. Il y avait des dates non valides (années KO...) qu'on avait corrigé. Tu te souviens ?

**Comment by jpic** [comment]
Ce sont les demandes qu'on a inserer manuellement sans date de depart qui date d'avant django.

**Comment by fjg** [comment]
Celles de formsite ? vous les avez ré-importé ? (je n'étais pas au courant)

**Comment by jpic** [comment]
Oui, on les a re-importé la semaine derniere, je l'ai annoncé en staging, et sur #general apres la mise en prod jeudi, c'etait d'ailleurs prevu.

**Comment by fjg** [comment]
ok, donc effectivement faudrait les ignorer du coup dans l'export celles-ci :/

**Comment by jpic** [comment]
Aucun soucis
