### ISSUE TITLE
Affichage des stats (filtre caisse)

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#493]
Entre un affichage sans caisse sélectionnée
<img width="1416" alt="capture d ecran 2018-07-17 a 14 59 07" src="https://user-images.githubusercontent.com/91435/42818813-29f9fec4-89d2-11e8-949e-4425371283e9.png">

et avec sélection (CPAM 31)
<img width="1416" alt="capture d ecran 2018-07-17 a 14 59 17" src="https://user-images.githubusercontent.com/91435/42818822-2e2967e6-89d2-11e8-93f3-9785ab3a5b6d.png">

on voit des chiffres différents, minorés en plus sans sélection. Etrange non ? (pb lors d'un import de données ?)

**Comment by jpic** [comment]
Parce que des stats etaient en cours de calcul peut etre ? Ca n'est plus le cas en tout cas, merci de reouvrir si le probleme se reproduit ;)
