### ISSUE TITLE
Nouveau profil d'admin non-tech

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#504]
Actuellement, le modèle de sécurité que nous utilisons est ainsi:

- [toute vue demande à son router si elle a le droit de s'executer](https://yourlabs.io/oss/crudlfap/blob/master/src/crudlfap/route.py#L118-163),
- [tout router répond par défaut Oui, si et seulement si le profil de l'utilisateur est au dessus de tous les autres profils](https://yourlabs.io/oss/crudlfap/blob/master/src/crudlfap/router.py#L319-337), actuellement ["admin"](https://github.com/betagouv/mrs/blob/master/src/mrsuser/models.py#L44-L46)

Par exemple, [MRSRequestRouter.allowed()](https://github.com/betagouv/mrs/blob/master/src/mrsrequest/crudlfap.py#L732) définie les noms de profils nécessaires pour chaque vue qu'il autorise.

Autre exemple, [MRSRequestValidateView.get_allowed()](https://github.com/betagouv/mrs/blob/master/src/mrsrequest/crudlfap.py#L165) rajoute à la consultation des droits niveau routeur, l'obligation pour l'objet MRSRequest d'avoir un status "inprogress".

Concernant la justification technique de l'horreur en question, l'instance de view est censée être provisionnée par le developpeur et hydratée avec un objet de requete HTTP (contenant notamment de l'utilisateur de la session donc de son profil), ainsi que les autres attributs dont la vue aurait besoin (un objet de demande pour une vue qui agirait sur une demande par exemple). L'instance de Router existe sans l'existence de requete HTTP, par conséquent son attribut "allowed()" est necessairement une methode qui prend une vue pleinement hydratée en attribut, car la vue appelle self.router.allowed(self) par défaut - d'où l'importance de l'appel à super() lorsqu'on veut *ajouter* des conditions.

Actuellement dont les admins utilisent le profil de superadmin, qui ouvre tous les droits, dont le tech a besoin. Toute nouvelle classe de vue, doit arriver uniquement entre les mains du plus haut niveau de permissions c'est à dire du tech.

Par conséquent, il faut créer un nouveau profil pour les admins, et donc, renommer le profil admin actuel, et mettre à jour l'attribut dynamique MRSUser.is_superuser.

C'est sur ce nouveau profil, d'admin non-tech, qu'il faut fixer les vues. En l'occurence, leur donner accès dans chaque router suffira car leurs vues respectives en hériteront.

**Comment by fjg** [comment]
@vindarel ok pour dev

**Comment by jpic** [comment]
Le seul "hic" c'est que dans notre modèle de sécurité nous avons un utilisateur qui a tous les droits.
Cet utilisateur, actuellement, est admin.
Il faut donc le renommer en "tech", ou autre si on arrive à trouver un meilleur nommage pour indiquer que ce profil à tous les droits (superadmin ? root ?).
Ensuite ajouter un profil "admin" qui a accès à un nombre fixé de vues.

**Comment by jpic** [comment]
J'ai ré-écrit l'issue, et viré mon précédent commentaire.

Pour moi c'est prêt à dev.

Des questions techniques ?

3615 BICHON
A votre disposition pour toute discussion technique 24/7

**Comment by vindarel** [comment]
- superadmin: tous les droits ("tech")
- admin: Fred, Brice etc

**Comment by jpic** [comment]
Faut-il aussi retirer le droit d'effacer des demandes au profil admin ?

**Comment by fjg** [comment]
Bonne idée, effectivement c'est une action **superadmin** uniquement. Fred confirme pour info.

**Comment by jpic** [comment]
Faut-il aussi retirer le droit d'effacer des demandes au profil admin ?

**Comment by jpic** [comment]
Le modele de sécurité a évolué dans la derniere version de crudlfap. N'étant pas rétro-compatible, je procèderai aux upgrades dans la nuit.

- Non-db model support has been greatly improved, using the lookupy module that
  implements a QuerySet interface for python objects, we just added support for
  models that have managed=False,
- You can now browse your list of registered `Routers` and `Routes` in
  CRUDLFA+, these are auto-generated during runtime into
  `crudlfap.models.Controller` and `crudlfap.models.URL`,
- By doing so, you can authorize groups that should have the view permission in
  each view's detail page, refer to the new documentation about security model
  for details,
- As such, the poor urls debug view is gone in favor of the above,
- Django permission API is now the default way of dealing with permission,
- BC Breaks listed below

BACKWARD COMPATIBILITY BREAKS

So, basically this will make your 0.5 CRUDLFA+ project start correctly on 0.6::

    find src/ -type f | xargs sed -i 's/from crudlfap import crudlfap/from crudlfap import shortcuts as crudlfap/'

BUT all your views will be invisible to non-superusers. Follow these steps to
upgrade:

- `from crudlfap import crudlfap` should now be `from crudlfap import shortcuts
  as crudlfap`,
- `allowed` is gone, in favor of `has_perm()`, that checks django permission by
  default, that means views are not open to staff users by default but to
  superusers
- as such, to open a view to all, replace `allowed=True` with
  `authenticate=False`,
- `Router.get_objects_for_user(user, perms)` is gone in favor of
  `Router.get_queryset(view)`, which returns all models by default.
- `Router.get_fields_for_user(user, perms, obj=None)` becomes
  `Router.get_fields(view)`,
- `Route.short_permission_code` becomes `Route.permission_shortcode`,
- `Route.full_permission_code` becomes `Route.permission_fullcode`,

**Comment by fjg** [comment]
Sur staging, il semble qu'un "admin" doive avoir une caisse alors qu'actuellement admin peut avoir la visibilité sur toutes les caisses.

<img width="945" alt="capture d ecran 2018-11-13 a 09 49 35" src="https://user-images.githubusercontent.com/91435/48401482-92f4eb00-e729-11e8-8851-e34cfa87a38d.png">
