### ISSUE TITLE
Mise à jour faq : durée de conservation des pj

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#507]
Mettre à jour le texte de la FAQ sur la durée de conservation des pj :

texte suivant à modifier :

![faq pj](https://user-images.githubusercontent.com/34480111/43777304-e162d174-9a41-11e8-8688-7b344ec989ee.JPG)

modifié par :

Oui, vous devez conserver vos pièces justificatives (prescription médicale de transports, tickets de transports en commun, de péage,.....) pendant 33 mois. En cas de contrôle par l'Assurance Maladie, vous avez l'obligation de transmettre les originaux de ces documents sous peine de devoir rembourser les montants perçus.

**Comment by jpic** [comment]
Design sur large ecran a revoir (centrage)

**Comment by jpic** [comment]
Wrong issue ^^
