### ISSUE TITLE
Modification page acceuil : info durée de conservation PJ

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#509]
enrichir la page d'accueil MRS ( https://www.mrs.beta.gouv.fr/) d'une information sur la durée de conservation des PJ.

Placer l'info suivante :
les originaux des pièces justificatives (prescription médicale de transport, justificatif de paiement de transports en commun et ou péage) doivent être conservé. Ils peuvent vous être demander par l'Assurance Maladie durant un période de 33 mois suivant le règlement dans le cadre d'un contrôle.

A placé avec une* sous le pavet suivant
![page accueil pj](https://user-images.githubusercontent.com/34480111/43778603-aaaedd72-9a45-11e8-8226-f4fb79ae320a.JPG)

**Comment by jpic** [comment]
![2018-08-21-153455_955x676_scrot](https://user-images.githubusercontent.com/94636/44404815-0981b280-a558-11e8-80d6-a84d91a8fe84.png)

**Comment by fb86** [comment]
Hello, 




Il y a eu une inversion du texte entre issue 509 et 507. 




Le texte n est pas le bon. 






A plus




Télécharger Outlook pour Android







On Tue, Aug 21, 2018 at 3:55 PM +0200, "∞" <notifications@github.com> wrote:












Closed #509 via 61333aa.

**Comment by jpic** [comment]
Design a revoir sur écran large ^^

**Comment by jpic** [comment]
Si c'est bon @notmoebius je veux bien fermer et re-ouvrir specifiquement pour l'issue de design. Merci !

**Comment by fb86** [comment]
pour moi c bon, on peut fermer
