### ISSUE TITLE
modification possibilité saisie date retour 1er transport

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#510]
Dans le formulaire de saisie, le champs date retour est obligatoire
![a](https://user-images.githubusercontent.com/34480111/43779072-e9f52c2e-9a46-11e8-9a55-5e6e05d3ab9d.JPG)

le trajet est parfois limité à un aller simple (notamment le cas de sortie d'hospitalisation avec une entrée en ambulance et une sortie en vp)

Modifications demandées :

1- Ajouter un radio button pour sélectionner **Aller simple** ou **Aller-Retour** (coché par défaut). La sélection de ce mode impacte aussi la construction du formulaire itératif. On peut par exemple faire une demande de remboursement pour un trajet itératif composé de 3 aller-simples. 
<img width="212" alt="capture d ecran 2018-09-04 a 11 27 01" src="https://user-images.githubusercontent.com/91435/45028863-f9350180-b046-11e8-8525-aed9ac8201f4.png">
2- Masquer le champ date de retour si l'utilisateur coche **Aller simple**
3- Dans le cadre d'un trajet Aller-Retour, pensez à remplir la date de retour. Mettre un contrôle + msg d'alerte en cas d'absence de saisie de date de retour : "Vous n'avez pas saisie de date de retour".

**Comment by notmoebius** [comment]
Vu avec @fb86 . Ok pour moi.

**Comment by jpic** [comment]
est-ce-que c'est pas plus simple d'ajouter une case a cocher aller simple avant les dates comme sur oui.sncf ?

si l'utilisateur coche pas de dates de retour

d'avance merci pour votre retour

**Comment by fb86** [comment]
Oui pas mal comme idée mais est ce que ca va pas trop surcharger le questionnaire ? 




Télécharger Outlook pour Android







On Wed, Aug 29, 2018 at 2:44 AM +0200, "∞" <notifications@github.com> wrote:












est-ce-que c'est pas plus simple d'ajouter une case a cocher aller simple avant les dates comme sur oui.sncf ?


si l'utilisateur coche pas de dates de retour


d'avance merci pour votre retour

**Comment by fjg** [comment]
J'ai bien l'idée de la case à cocher aussi.
