### ISSUE TITLE
Export de stats en erreur

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#511]
Il semble que les stats importées étaient à un moment fausse.
Exemple :

<img width="477" alt="capture d ecran 2018-08-07 a 15 55 43" src="https://user-images.githubusercontent.com/91435/43780300-87f1782a-9a5a-11e8-996b-1970c91f3432.png">
<img width="482" alt="capture d ecran 2018-08-07 a 15 55 29" src="https://user-images.githubusercontent.com/91435/43780301-882121f6-9a5a-11e8-9d21-62fe094c238c.png">

On voudrait donc un export avec toutes les demandes pour lesquelles la base de remboursement ( Base de remboursement 46.30€ dans l'exemple) est différent du montant total affiché sur la demande (Montant total (Base de remboursement) 23.10€ TTC dans l'exemple).

Le CSV doit contenir : 
 * le NIR
 * le numéro de demande
 * la date du transport
 * la date de mandement
 * le montant total affiché
 * la base de remboursement (importée)

Avec ce fichier, on pourra creuser les écarts et valider les stats.

**Comment by jpic** [comment]
Quelle action reste-t-il à prendre ? Est-ce qu'il faut reformuler peut être ? Merci ;)

**Comment by fjg** [comment]
faire un export csv

**Comment by jpic** [comment]
Entendu merci !

**Comment by fjg** [comment]
Après vérification, payé en double. 2 demandes, 1 pour 23,10 et 1 pour 23,20. => ca rejoint #481.
Je clos.
