### ISSUE TITLE
enrichir les mails : accusé reception depot de demande + confirmation de paiement

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#512]
**Sujet** : durée de conservation des pièces justificatives (PJ)
**objectif** : informer les assurés de l'obligation de conserver 33 mois les PJ transmises lors du dépôt du dossier

**action** : compléter les mails d'accuser de réception de dépôt de demande sur MRS et confirmation de paiement.

**Modalités** : rajouter la phrase ci dessous en fin de mail avant les formules de politesses.

" Il vous appartient de conserver 33 mois les originaux des pièces justificatives (prescription médicale de transport, justificatif de paiement de transports en commun et ou péage) . Ces documents pourraient vous être  demandées dans le cadre d'un contrôle de l'Assurance Maladie."

**Comment by fb86** [comment]
@notmoebius on se voit demain pour faire la correction est cloturé ?

**Comment by notmoebius** [comment]
ok pour moi. Je fais la modifie si t'es ok.

**Comment by fb86** [comment]
Ok pour moi




Télécharger Outlook pour Android







On Thu, Sep 6, 2018 at 9:55 AM +0200, "notmoebius" <notifications@github.com> wrote:












ok pour moi. Je fais la modifie si t'es ok.

**Comment by jpic** [comment]
Go pour modifs sur master ;)

**Comment by notmoebius** [comment]
add footer
