### ISSUE TITLE
transport iteratif, classement automatique de la date de transport la plus ancienne

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#513]
Lorsqu'un assuré déclare plusieurs dates pour un transport itératif, notre formulaire retient la date du 1er trajet déclaré lors de l'extraction même si l'assuré déclare des dates antérieurs par la suite (voir exemple ci dessous). 

Lors de l'export du fichier stat, c'est la date du trajet déclaré en 1er qui ressort.
Toutefois, et c'est là le fond du problème : Lors de la liquidation , le technicien liquide d'abord la date la plus ancienne. En faite il indique le nombre de trajet et la date du 1er et la date du dernier de la série.

Ainsi quand Darnelle interroge la base de données de l'Assurance Maladie elle ne retrouve pas le dossier.

Dans notre exemple  ( demande 201807310009)  la 1er date de trajet saisie est le 30 juillet, la 2eme le 2 juillet.....
le technicien a liquidé avec la date du 2 juillet comme début de la série.
la requête en export indique la date du 1er trajet au 30 juillet.

Lorsque 'on compare la requête export et notre base de données de paiement (erasme) , on ne trouve aucun remboursement pour cette assuré car il y a une distorsion dans la date.

**Solution** : Peut on, en cas de trajet itératif, retrier les dates pour mettre la date la 1plus ancienne en date de 1er trajet (date ressortant dans l'export) ?

**Comment by fjg** [comment]
Magnifique @fb86 👏  Le genre de bug sympa à creuser...

**Comment by fb86** [comment]
On voit cela la semaine prochaine, 

profite de tes vacances

**Comment by fjg** [comment]
Pas de bug constaté en staging sur une nouvelle demande, reste à confirmer la qualité des données (date) en production sur ce cas.

**Comment by fjg** [comment]
Pas de bug donc, pb de données saisies par l'assurée sur la demande **201807310009**.

@jpic : il faudra modifier l'année du premier trajet de 2015 en 2018 pour que cette demande ne ressorte plus en erreur dans l'export/import stat.

**Comment by jpic** [comment]
pas de soucis ! direct sur la db de prod ?

**Comment by jpic** [comment]
Done !
