### ISSUE TITLE
ETQ assuré je recois un mail d'excuse si mon dossier n'est pas traité dans les 7 jours

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#517]
**Demande** : envoi de mail automatique si délai de traitement est supérieur à 7 jours
**Modalités** : prévoir un envoi hebdomadaire en fin de journée ( 18h) vers les dossiers dont le delai de traitement est supérieur à 7 jours.
**définition du délai de traitement** : (date du jour)-(date de statut soumis ou en cours de liquidation) supérieur à 7 jours.
** mail type à envoyer** :

**Comment by fjg** [comment]
Pas de fan de cette automatisation. Les motifs de dépassement peuvent être multiples. Et l'effet de recevoir 1 mail peut être sympa la 1ère fois, en revanche, à la 2ème, je vois que c'est un robot qui m'écrit... et là ca perd tout son charme :)
Travaillons à ne pas avoir de demandes traitées en + de 7 jours.

**Comment by notmoebius** [comment]
Je propose d’envoyer le mai une seule fois. D'accord pour faire en sore de traiter en moins de 7j. les dépassements restent rares et permettrait de rassurer l'utilisateurs et de couvrir toute l'Occitanie.

**Comment by fjg** [comment]
A priori géré par #515
