### ISSUE TITLE
Modification mail archivage

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#529]
il faudrait modifier et ajouter une data dans le mail d'archive. J'ai indiqué les modifs et l'ajout en gras.

Le contenu souhaité serait :

- En début d'objet : ajouter "**Archive //**"
- Dans le corps du message : 

> Bonjour,
>
> **Voici l'archive de la demande de remboursement via MRS n°201808210005 :**
> 
> - Référence : 
> - Prescription Médicale de Transport (PMT) : Prescription Medicale de Transport (9).jpg
> - Prénom : 
> - Nom de famille : 
> - Date de naissance : 
> - NIR : 
> - Adresse email :
> - Date du trajet aller 1: 
> - Date de trajet retour 1:
> - Kilométrage total parcouru en voiture : 60
> - **Base théorique de remboursement** : <montant> €
> 
> Cordialement,
> L'équipe MRS

La **base de remboursement** est celle calculée par MRS et affichée dans sur la demande, pas celle importée par les stats.

**Comment by fjg** [comment]
OK pour moi j'ai fait qqs petites modifs cosmétiques et précisé la base.
