### ISSUE TITLE
Sur les stats cumulées

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#559]
En prod et en staging, l'affichage des stats cumulées sans filtre sur caisse et institution, affiche le cumul qu'à partir du 03/09/2018.
Pour avoir le cumul, il faut obligatoirement choisir une caisse, et là, cela fonctionne.
![image](https://user-images.githubusercontent.com/32330644/45156958-ec97e100-b1df-11e8-80c3-37b98a3d90c8.png)

Si je filtre par caisse, c'est ok:
![image](https://user-images.githubusercontent.com/32330644/45156975-ff121a80-b1df-11e8-92c8-84ab27ba2ba2.png)

**Comment by jpic** [comment]
Je viens de generer les stats cumulatives pour afficher sans filtre ni
institution ni caisse qui manquaient.

Cela dit il reste un petite refacto a faire avant de fermer ce tiquet, car
actuellement le calcul de stat ecrit 99% de stats a 0 au final, il vaudrait
mieux les creer dans la vue a l'affichage ou voir si eventuellement c3js
peut s'en passer.

**Comment by jpic** [comment]
![2018-09-06-143331_1354x341_scrot](https://user-images.githubusercontent.com/94636/45157591-e276e200-b1e1-11e8-9c8d-920f50c7e122.png)

**Comment by notmoebius** [comment]
Vérif ok. Je clôture l'issue.
