### ISSUE TITLE
Estimation du cout en tax multiplie toujours par 2 meme pour les aller simples

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#569]
Relicat d'avant le support de l'aller simple.

**Comment by notmoebius** [comment]
Oui, justement. On se poser la question de l'impact sur l'estimation du coût affiché

**Comment by jpic** [comment]
Peut-être vérifier les chiffres sur une demande en staging ?

Vous inquiêtez pas on va refactoriser si y'a des formules qui sont arrivées dans des templates :joy:
