### ISSUE TITLE
Evolution fin septembre gestion circuit réclamations / formulaire contact assuré

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#579]
Une fois le profil relation client déployé et testé dans les organismes, faire évoluer le circuit de gestion des réclamations.
Pour ce faire, modifier la page contact du site MRS de la sorte 

Ajouter après la phrase "Nous ne pouvons traiter..." 
"Pour toutes réclamations sur votre demande de remboursement, veuillez nous contacter 
- par mail : connectez-vous sur votre compte ameli, rubrique « Ma messagerie ». (lien sur votre compte ameli : https://assure.ameli.fr/PortailAS/appmanager/PortailAS/assure?_somtc=true)
- par téléphone : appelez un conseiller de l'Assurance Maladie au 36 46*, à votre écoute du lundi au vendredi. (*service 0,06 €/min + prix appel)

![img_7544](https://user-images.githubusercontent.com/34479425/45358971-745c6180-b5cb-11e8-9243-a65c45e40ff8.JPG)

**Comment by vindarel** [comment]
scinder en deux:

- une pour le front,
- en back: modifier le contenu des modèles de mail

**Comment by notmoebius** [comment]
Type de motif vu en atelier:
-Nous demander une information
-Signaler un problème
-Erreur dans votre dossier
-Réclamation sur un dossier clos
-Annuler une demande
-Feedback produit

**Comment by jpic** [comment]
Continuation sur #804
