### ISSUE TITLE
ETQ assurée je suis averti lorsqu'une demande de date de transport a déjà été réalisée

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#581]
Objectif : limiter les doubles déclarations (**2 fois la même date de trajet peu importe si c'est l'aller ou le retour**) et donc les risques de double traitement/remboursement.

Demande : signaler à l'assuré lorsqu'il sollicite un trajet pour une date ayant déjà fait l'objet d'une prise en charge.

On détecte les demandes de l'assuré sur les champs **NIR**, **date de naissance**, **date transport** aller ou retour.

Modalités : lorsque l'assuré soumet sa demande, lancer une requête de contrôle pour vérifier que les dates de transports n'ont pas déjà été sollicitées (même date pour une demande en statut **soumis**, **en cours de validation** ou **validé**).

* si la double déclaration porte sur une demande en statut **soumis** ou **en cours de liquidation**, faire apparaître le message suivant :
"Votre demande de prise en charge concernant le(s) trajets du date n°1, date n°2, .......... est en cours de traitement. Merci de modifier si nécessaire votre déclaration avant de valider votre demande. "
puis permettre à l'assuré de corriger sa demande ou de la valider (on ne bloque pas).

* si la double déclaration porte sur une demande en statut **validé**, faire apparaître le message suivant :
"Votre  trajet du date n°1, date n°2, .......... vous a été réglé lors de demande du [date de la demande] n° [n° de la demande]. Merci de modifier si nécessaire votre déclaration avant de valider votre demande."
puis permettre à l'assuré de corriger sa demande ou de la valider (idem on ne bloque pas).

PS : à mettre en lien avec US #585 signaler au liquidateur que la date de transport a déjà fait l'objet d'une demande + US mettre en place un compteur de signalement.

**Comment by fb86** [comment]
Messieurs une petite relecture svp

**Comment by notmoebius** [comment]
Juste une remarque: pourquoi permettre à l'assuré de valider sa déclaration en cas de date identique ? On pourrait s'éviter l'issue 585, non ?

**Comment by fjg** [comment]
ok pour moi, je passe en todo

**Comment by jpic** [comment]
L'avertissement ne sera lu que par 10% des utilisateurs.

Sans clic de confirmation explicite impossible de s'assurer que l'utilisateur ait lu et comprit.

Du coup je me demande si c'est pas trop implicite pour être utile en l'etat en terme d'ergonomie.

**Comment by jpic** [comment]
branche jpic : tout marche, il faut revoir les couleurs et les libeles

j'ai apporte quelques modifications a l'algo form_confirms:

- optimisation de la requete SQL et de l'algo
- detection des date dupliquées peu importe qu'elles soient en aller ou en retour
- n'ajoute qu'une seule erreur par champs, mais celle ci peut comporter plusieurs numeros de demandes separees par des virgules

manque:

- couleur orange,
- libelés precis,
- tests python !

**Comment by fb86** [comment]
Après présentation des 1ers travaux de vincent, il apparait qu'un contrôle sur les dates aller et retour est inutile. Le contrôle sur les dates aller est suffisant.

**Comment by jpic** [comment]
Peut etre, mais vu que c'est fait, la question est: le controle sur les dates de retour est-il genant ?

**Comment by jpic** [comment]
https://jpic.mrs.yourlabs.org/demande

![2018-11-27-171312_740x851_scrot](https://user-images.githubusercontent.com/94636/49095088-ff163980-f267-11e8-81a8-73e78d9ebfe7.png)

**Comment by jpic** [comment]
Apres un quick bugfix b70c653
![2018-11-27-172815_694x536_scrot](https://user-images.githubusercontent.com/94636/49096088-1524f980-f26a-11e8-854e-52f418a3b028.png)

**Comment by vindarel** [comment]
j'ai repris le relai: messages selon statut de l'ancienne demande, pas de messages en double (lol), modale d'accueil qui demande de vérifier ses transports (pour essayer de coller au mieux à la demande initiale).

![selection_262](https://user-images.githubusercontent.com/3721004/49161746-bd4dc780-f329-11e8-950f-d119d2f51adb.png)

**Comment by vindarel** [comment]
> no space left on device

c'est le moment de retrouver et documenter la commande efficace que j'ai trouvé la dernière fois

**Comment by vindarel** [comment]
rm orphane docker volumes:

> docker volume rm $(docker volume ls -qf dangling=true)

I didn't run it now, can't confirm, but last time we had a LOT of orphanes, like 50GB.

https://stackoverflow.com/questions/27812807/orphaned-docker-mounted-host-volumes

**Comment by fjg** [comment]
<img width="786" alt="capture d ecran 2018-12-04 a 09 52 08" src="https://user-images.githubusercontent.com/91435/49430192-afc19300-f7aa-11e8-83d5-8928cc97a6c1.png">

<img width="793" alt="capture d ecran 2018-12-04 a 09 54 18" src="https://user-images.githubusercontent.com/91435/49430196-b3551a00-f7aa-11e8-8361-00c10629a62f.png">


Revoir les textes des deux messages + ajouter le bouton annuler la demande. @fb86 @notmoebius

**Comment by jpic** [comment]
En staging:
![2018-12-05-134734_1120x672_scrot](https://user-images.githubusercontent.com/94636/49514542-a280d300-f894-11e8-8012-1f8f052d64a0.png)
![2018-12-05-134744_1164x285_scrot](https://user-images.githubusercontent.com/94636/49514546-a44a9680-f894-11e8-8c52-347812ebc002.png)

**Comment by fb86** [comment]
Une question, sur mon portable, il n y a pas d affichage de la mention : attention motif de rejet potentiel détecté..... 




Télécharger Outlook pour Android







On Wed, Dec 5, 2018 at 1:50 PM +0100, "∞" <notifications@github.com> wrote:












Closed #581.

**Comment by jpic** [comment]
C'est mit a jour

**Comment by fb86** [comment]
Cool, j ai rien trouvé de plus et pourtant je l ai super mal traité 




Télécharger Outlook pour Android







On Wed, Dec 5, 2018 at 2:53 PM +0100, "∞" <notifications@github.com> wrote:












C'est mit a jour
