### ISSUE TITLE
ETQ liquidateur je peux voir lorsqu'un assuré à déclaré 2 fois la même date de trajets

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#585]
Cette US est liée à US #581 - alerter un assuré lorsqu'il réitère une demande de prise en charge pour une même date. 

Suite à ce signalement l'assuré a le choix de corriger sa saisie ou de la maintenir (ce n'est pas bloquant, juste informatif).

Objectif : Si toutefois il maintient sa demande, ETQ liquidateur, je reçois/vois un signalement/une alerte pour m'informer d'une demande similaire en cours de traitement ou déjà traité.

Modalité : lors de l'ouverture de la demande faisant état d'un double trajet (même trajet à se faire rembourser qu'une ou plusieurs autre(s) demande(s)), faire apparaître le message suivant :

"Les trajets en dates du [date de trajet n °1], [date de trajet n °2], [date de trajet n °3], ..... ont déjà fait l'objet d'une demande dans la/les demande(s) [n° demande n°1], [n° demande n°2], [n° demande n°3]. Merci de vérifier que les demandes correspondent à des trajets différents afin de ne pas traiter et rembourser plusieurs cet assuré."

Le message est affiché en haut de la demande de manière visible et à attirer l'attention.

**Comment by fb86** [comment]
Une relecture pour validation

**Comment by fjg** [comment]
ok pour moi. @notmoebius et toi ?

**Comment by notmoebius** [comment]
Ok pour moi.

**Comment by vindarel** [comment]
On ne met pas d'indicateur dans la liste des demandes ?

**Comment by fjg** [comment]
Si l'icône sur les demandes en doublons :)

**Comment by vindarel** [comment]
work in progress :)

![selection_263](https://user-images.githubusercontent.com/3721004/49249050-91ab0a00-f41b-11e8-9cac-98cc3eb6e495.png)

**Comment by vindarel** [comment]
évolution:

![selection_263](https://user-images.githubusercontent.com/3721004/49383247-94a64300-f718-11e8-8f8d-151c70e028c1.png)

**Comment by notmoebius** [comment]
En attente d'épurer la dette #765

**Comment by jpic** [comment]
Cette issue est a re-ecrire car les specs ne sont plus d'actualité depuis que nous n'avons justifié la creation d'une nouvelle table de relation denormalisées.

**Comment by jpic** [comment]
Sinon un tableau:

01/01/2000 | 201201010001 (en cours), 201201010001 (soumise)
02/01/2000 | 201201010001 (validée)

etc

**Comment by jpic** [comment]
Autres options:
![2018-12-17-113218_1066x744_scrot](https://user-images.githubusercontent.com/94636/50081835-beb73500-01ef-11e9-80b6-0aa448bd3a3b.png)
![2018-12-17-113151_1065x479_scrot](https://user-images.githubusercontent.com/94636/50081839-beb73500-01ef-11e9-8a8b-be7aa084eef5.png)

**Comment by jpic** [comment]
Optimisons l'"immobilier" de la page
![2018-12-17-114106_1083x400_scrot](https://user-images.githubusercontent.com/94636/50082338-fbcff700-01f0-11e9-868e-fd9cf3486938.png)

**Comment by jpic** [comment]
![2018-12-17-114239_1052x401_scrot](https://user-images.githubusercontent.com/94636/50082409-2ae66880-01f1-11e9-932d-a719eb5be685.png)

**Comment by notmoebius** [comment]
Correctif:
- ouvrir dans une nouvelle fenêtre
- si dates se chevauchent, pas de signalement demande n°201812180002 date 05/12/2018

**Comment by notmoebius** [comment]
Erreur 500 sur compteur caisses/alertes

**Comment by jpic** [comment]
Résolu !

**Comment by fb86** [comment]
MOP utilisateur mis à jour
