### ISSUE TITLE
ETQ admin, je peux connaître, par CPAM, le nombre de signalement fait aux assurés pour "date de trajet dejà sollicité"

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#586]
Enrichissement du module stat : ajouter une nouvelle page pour afficher le nombre (visualiser un compteur) des demandes en doublons. Filtrage via caisse.

ETQ profil stat et admin, je peux visualiser le nombre de signalement ( US #581) réalisé par CPAM.

**Comment by jpic** [comment]
@fb86 qu'est-ce-qui doit compter comme *un* signalement exactement stp ?

**Comment by fb86** [comment]
Signalement = information a l assuré sur une date de trajet deja déclaré.




En cas de plusieurs date deja déclaré sur une meme demande, on ne compte que 1 signalement 




Télécharger Outlook pour Android







On Thu, Nov 29, 2018 at 12:15 PM +0100, "∞" <notifications@github.com> wrote:












@fb86 qu'est-ce-qui doit compter comme un signalement exactement stp ?

**Comment by jpic** [comment]
@fb86 donc on ne doit pas faire les comptes pour les demandes passées ? uniquement sur les nouvelles demandes ? Ou est-ce-que vous voulez ajouter des points sur le graphique correspondant au nombre de demandes avec doublons faites par jour ?

**Comment by jpic** [comment]
Résolu
