### ISSUE TITLE
Bug sur les select de materialize

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#588]
Il semble que le turbolinks cache la version déjà init du HTML select, et l'init à nouveau, causant une duplication de select , dans les pages de list d'admin.

**Comment by jpic** [comment]
On garde le commit mais c'etait pas un close en fait

**Comment by notmoebius** [comment]
Nouvelle version à tester

**Comment by jpic** [comment]
- [hack dans le pipe](https://yourlabs.io/oss/crudlfap/commit/78c8f020688af753698af479396047a0edc13c2d), 
- [issue upstream](https://github.com/Dogfalo/materialize/issues/6156)

**Comment by jpic** [comment]
Fix fonctionne en local mais pas sur serv

**Comment by jpic** [comment]
Je voie que c'est fixed en jpic.

Deblocage de la pipeline en cours :joy:

**Comment by jpic** [comment]
In production :birthday:
