### ISSUE TITLE
Afficher un libellé a coté des champs modifiés

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#589]
ETQ UPN quand je modifie un NIR/naissance, afficher un indicateur à coté de la valeur dans la page de détail

**Comment by vindarel** [comment]
J'ai ajouté un liseré rouge et un *title* qui dit que le champ a changé.

![selection_252](https://user-images.githubusercontent.com/3721004/46750902-5c0a6000-ccb9-11e8-896e-96689fa40351.png)


@jpic il me manque les tests U, on en parle quand tu veux. (et potentiellement refacto le css + css materialize pour le *title*).

**Comment by vindarel** [comment]
tests unitaires, je n'ai pas vu comment quel est le mécanisme des vues, utilisable en tests, qui màj le nir (et crée une logentry). Trouvé `MRSRequest.update_status`, pas convaincu de refaire le même pour `update_nir`.

**Comment by jpic** [comment]
Je croyais qu'on avait deja des TU pour l'existant, je te parlais d'ajouter un test d'acceptation pour ton changemente sur le template tout simplement ;)

**Comment by vindarel** [comment]
et ma nouvelle fonction ? Trop fort si elle se teste toute seule :p (-> tchat ?)

**Comment by jpic** [comment]
L'objectif c'est l'affichage, ce qui est teste par le crawler, a condition que ton use case soit dans le jeu de data de test.
Donc ton test d'acceptation tu pourras toujours le garder et t'auras jamais a le maintenir.
Par rapport a la fonction, je ne comprends pas pk la mettre dans le modele et non dans la vue, alors que pour l'instant il n'y a que la vue qui s'en sert ? Cela permettrait aussi de refactoriser sur la partie requette, car on a deja toute les data dans la vue je ne crois pas qu'on ait vraiment besoin de rajouter une requette a chaque fois qu'on veut verifier un champs. Pourquoi passer par les logentries, n'est-il pas plus judicieux de comparer la valeur de l'attribut du model et dans le JSONField qui contient les donnees originnales ?

**Comment by jpic** [comment]
Doc a jour pour le test dataset
https://mrs.readthedocs.io/en/latest/tutorial.html#jeu-de-data-de-tests
