### ISSUE TITLE
Ne pas faire référencer par les moteurs de recherche les liens iframe/formulaire sur la doc technique

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#596]
- [x] interdire aux robots le référencement des liens vers le formulaire MRS avec institution ou autres paramètres
- [ ] protéger l'accès (authentification)

**Comment by jpic** [comment]
Ok je me souviens pk je l'avais pas jetté après avoir fait la doc MRS: c'est le moyen de tester sans CORS.

Les utilisateurs anonymes tombent bien sur une 404 maintenant.
