### ISSUE TITLE
Backups des logs nginx

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#597]

**Comment by jpic** [comment]
https://yourlabs.io/oss/playlabs/commit/0c69ee444895c0162c6cd9b21dce0fbc49ddc90e

:joy:

**Comment by notmoebius** [comment]
ils sont conservés mais pas en backup

**Comment by jpic** [comment]
exact, on ne perd plus les logs a chaque deploy, absolument genial n'est-ce-pas ? :joy:
