### ISSUE TITLE
Erreur affichage stat portail mrs

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#603]
Il y a un écart entre l'affichage sur la page stat du portail MRS et sur les calcul stat volet admin.

les données ne sont plus mises à jour alors même qu'il indique une mise à jour au 19 septembre sur le site.

Ci dessous les 2 captures d'écran.

PS : avant d'écrire issues j'ai chercher si le bug n'avait pas déjà été identifié mais j'ai rien trouvé........
![capture stat admin](https://user-images.githubusercontent.com/34480111/45745781-1f36d600-bbf1-11e8-8113-98b9bd3162b5.JPG)
![capture stat mrs public](https://user-images.githubusercontent.com/34480111/45745782-1f36d600-bbf1-11e8-9138-0f6d59c37c28.JPG)

**Comment by vindarel** [comment]
uniquement texte qui déborde.

stats: autre ticket.

**Comment by fjg** [comment]
A priori sera réglé avec les 4 dossiers de la #678... A suivre.

**Comment by jpic** [comment]
Est-ce-qu'on ferme cette issue pour duplication de la #678 ?

**Comment by fjg** [comment]
@fb86 à voir avec @jpic sur les 4 dossiers à problème.

**Comment by fjg** [comment]
voir la #678

**Comment by jpic** [comment]
@fb86 l'issue persiste-t-elle suite aux modifications que nous avons effectue mardi dernier?

**Comment by fb86** [comment]
Non, pour moi c est bon




Télécharger Outlook pour Android







On Mon, Nov 26, 2018 at 9:58 PM +0100, "∞" <notifications@github.com> wrote:












@fb86 l'issue persiste-t-elle suite aux modifications que nous avons effectue mardi dernier?

**Comment by fjg** [comment]
Done
