### ISSUE TITLE
erreur traduction

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#609]
Dans le menu le champs créer et liste (create & list) est toujours en anglais, voir affichage ci dessous.

![traduction](https://user-images.githubusercontent.com/34480111/46015348-9a9cf980-c0c1-11e8-8cab-28f7b2dd354d.JPG)

idem sur l'ensemble des champs gérant une list (mail, utilisateur, caisse,...) et la création (mail, utilisateur, caisse,...)

**Comment by fb86** [comment]
Nom, list par liste et creat par creation.... 




Télécharger Outlook pour Android







On Wed, Sep 26, 2018 at 12:21 PM +0200, "∞" <notifications@github.com> wrote:












Tu veux traduire "mail" par "courriel" ? 😂

**Comment by vindarel** [comment]
et voilààà, en live: https://vince.mrs.yourlabs.org/admin/
