### ISSUE TITLE
Contrôle de date pour trajet itératif

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#614]
A traiter: il est possible de saisir des transport au même date X fois:

![image](https://user-images.githubusercontent.com/32330644/49460933-d0154000-f7f2-11e8-8fdc-04fc23805cf1.png)

Il apparaît que l'assuré peut saisir 10 transports itératifs avec la même date (voir copie écran ^^).

Faire: ETQ Assuré, je peux saisir 10 trajets avec 10 dates identiques et **mettre un warning** ou fenêtre modal pour informer de la redondance afin d'éviter de rejeter la demande (profil liquidation).

DOD:
- si je saisie un trajet aller 10/11/2018 et retour 10/11/2018 => pas de signalement et de surbrillance.
- si je saisie un autre trajet, dans la même demande, avec un date au 10/11/2018, faire un signalement en mettant en surbrillance les dates identiques sur des trajet différents.
Inviter l'assuré à corrigé sa saisie lors de la soumission (boucle avec l'issue #581 ).

**Comment by fjg** [comment]
@notmoebius faire une proposition de messages (alerte en haut : "Attention cette demande contient plusieurs trajets sur une même date...")
Préférer une alerte à une fenêtre modale pour avertir l'UPN qui traite la demande.

**Comment by jpic** [comment]
Est-ce-que cette issue est une duplication de #581 ?

**Comment by jpic** [comment]
Ok merci pour la difference, cela dit il faut que la #581 soit cloturee afin de re-utiliser le code ici.

**Comment by fjg** [comment]
C'est #581 mais la #585 (côté liquidateur).

**Comment by fjg** [comment]
C'est pas les mêmes alertes que 585, c'est sur les doublons à l'intéreieur de la même demande !

**Comment by jpic** [comment]
Vincent et moi ne comprennons pas l'issue de la meme maniere.

**Comment by vindarel** [comment]
On discute aussi des besoins de la UI :)

**Comment by jpic** [comment]
> Faire: ETQ Assuré, je peux saisir 10 trajets avec 10 dates identiques et mettre un warning ou fenêtre modal pour informer de la redondance afin d'éviter de rejeter la demande (profil liquidation). 

Ca veut dire que lors de la saisie j'ai une modale que je ferme pour confirmer ?

> Inviter l'assuré à corrigé sa saisie lors de la soumission (boucle avec l'issue #581 ). 

Ca veut dire que l'assuré doit aussi confirmer dans la page suivante ?

**Comment by fb86** [comment]
Yes, l objectif pour l instant c'est le signalement à l assuré. 




Télécharger Outlook pour Android







On Thu, Dec 6, 2018 at 6:28 PM +0100, "∞" <notifications@github.com> wrote:












D'accord donc on choisi l'une ou l'autre des deux solutions par rapport au couts d'implementations estimées ?

**Comment by jpic** [comment]
![2018-12-12-234242_1117x842_scrot](https://user-images.githubusercontent.com/94636/49903580-fc226800-fe67-11e8-9c60-56dbbb0888db.png)

![2018-12-12-234242_1117x842_scrot](https://user-images.githubusercontent.com/94636/49903574-f7f64a80-fe67-11e8-93de-a7043dea44fb.png)

**Comment by jpic** [comment]
![2018-12-13-001149_1079x890_scrot](https://user-images.githubusercontent.com/94636/49904900-0c3c4680-fe6c-11e8-84d6-9eeb8d2ff0e1.png)

**Comment by jpic** [comment]
![2018-12-13-001326_730x890_scrot](https://user-images.githubusercontent.com/94636/49904947-37269a80-fe6c-11e8-84db-e2b50a525e5e.png)

**Comment by jpic** [comment]
![2018-12-13-001627_568x909_scrot](https://user-images.githubusercontent.com/94636/49905071-a4d2c680-fe6c-11e8-8e17-debb684d8620.png)
