### ISSUE TITLE
Ajouter une case à cocher pour utilisation du mail

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#615]
Faire valider par l'assuré qui fait la demande l'usage de sa mail adresse.

Lors de la soumission du formulaire, l'assuré devra cocher : 
- j'atteste sur l'honneur...
- j'autorise le mail pour communiquer avec moi.

**Comment by jpic** [comment]
Est-ce-que tu peux confirmer que cocher cette case est obligatoire, à l'instar de la case de l'attestation sur l'honneur ? Cocher cette case n'est donc *pas* optionnel ?

**Comment by notmoebius** [comment]
@Johan1983 propose une pharse pour nous autoriser à nous envoyer les mails.
La phrase pour le mail:
"J'autorise la caisse primaire à enregistrer...

**Comment by Johan1983** [comment]
Propal de message de consentement optin, répondant au standart RGPD :

En cochant cette case, vous acceptez que Mes Remboursements Simplifiés mémorise et utilise votre adresse email dans le but de vous envoyer occasionnellement des emails d'informations.
Vous pouvez à tout moment, vous désinscrire de ce service. (lien désabonnement mailjet).

**Comment by Johan1983** [comment]
Les mails seront donc shootés par MailJet, il faudra intégrer le lien de désabonnement dans la newsletter + Ajout d'une qualification de l'optin dans la BDD (soit BDD MRS, soit dans BDD MailJet).

**Comment by notmoebius** [comment]
Le lien de désabonnement est inclus de base par mailjet.
