### ISSUE TITLE
Demandes avec des NIR sur 12 chiffres, comment est-ce possible ?

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#617]
Le NIR c'est forcément sur 13 chiffres cf. [Vocabulaire](https://github.com/betagouv/mrs/wiki/Vocabulaire)

- [ ] identifier et corriger le bug (import ? ou formulaire ?)
- [ ] remettre d'équerre les données

Voir les demandes :
201809030003 (même assuré que 201807190004 => les relier en prod sur le même assuré ?)
ou
201808080000 (même assuré que 201804170005 => idem)

**Comment by vindarel** [comment]
on a injecté ces data: https://yourlabs.io/mrs/inventory/tree/master/migrations, tous les NIR sont bien à 13 chiffres.

**Comment by jpic** [comment]
Il est possible qu'on en ait injecté d'autres, mais j'ai essaye de sauvegarder les scripts quand j'en ai eu l'occasion.

Est-ce-qu'on peut ajouter une contrainte pour mettre le NIR a un minimum de 1000000000000 ?

Je suppose que oui, mais la migration ne passera pas tant qu'on aura des NIRs inferieurs en db.

**Comment by notmoebius** [comment]
update du NIR faite sur la demande 201808080000

**Comment by vindarel** [comment]
fait pour la demande 201809030003

**Comment by vindarel** [comment]
À faire: prévention: contraintes sur la BD.

**Comment by jpic** [comment]
On a un bugfix preventif mais pas identifie la source.
