### ISSUE TITLE
Demande avec 310000003 comme institution

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#620]
Je pensais ce bug traité mais je viens de m'apercevoir que des demandes via l'institution 310000003 continuent d'arriver. A voir ce qu'l en est.
![image](https://user-images.githubusercontent.com/32330644/46611727-e1054600-cb0e-11e8-9e99-0e64a5e8dc23.png)

A noter que les demandes sont totalement valables mais par où arrivent-elles ?

**Comment by jpic** [comment]
L'avant dernier resultat de google tombe sur une institution de test : https://www.mrs.beta.gouv.fr/institution/310000003/mrsrequest/iframe/

**Comment by jpic** [comment]
J'ai shooté l'etab 310000003 qui ne servait qu'a l'instance openbar qui servait à l'époque au developpement de l'iframe en collab avec Pasteur. 

Du coup, l'URL d'entrée a priori est maintenant en 404, et devrait dropper des resultats google: https://www.mrs.beta.gouv.fr/institution/310000003/mrsrequest/iframe/

Attention, la mesure que nous avions pris la dernière fois, de bloquer cette page n'était pas suffisante:

https://www.mrs.beta.gouv.fr/institution/310000002/mrsrequest/iframe/example/

En effet, il y a deux URLs:

- celle d'exemple d'intégration d'iframe, qu'on a soft-bloqué avec un script
- celle du formulaire en iframe en lui même !!!!

Là, pour la bloquer c'est autre chose: [proposition de hack](https://stackoverflow.com/questions/8169582/protecting-iframe-only-allow-it-to-work-on-one-domain)

**Comment by jpic** [comment]
Je viens d'avoir le dev de Pasteur en ligne, il est OK pour qu'on teste le hack de stackoverflow a 14h, si ca pete un truc chez lui il nous le dira, sinon on pourra fermer l'issue !

**Comment by notmoebius** [comment]
@jpic cette issue est toujours d'actualité ? As-tu eu Pasteur pour commit cette issue ?

**Comment by jpic** [comment]
Oui, et non :joy:
