### ISSUE TITLE
Bug design mobile

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#621]
Pour fermer cette issue, rendre ce texte lisible sur mobile:
![screenshot_20181004-072828](https://user-images.githubusercontent.com/94636/46653441-56702580-cba6-11e8-8b60-9af2c547f37b.jpg)

**Comment by tbinetruy** [comment]
J'ai change le comportement en mobile (ca reste pareil en desktop):

![mrs-fix-621](https://user-images.githubusercontent.com/19936648/46920339-15847080-cfed-11e8-9167-95412ea27615.png)

J'ai fait le choix de garder les bordures blanches par coherence avec le design desktop mais c'est peut etre mieux sans au finale, une preference ? :)

Ca a l'air de bien se comporter en mobile landscape et tablet portrait / landscape.

Je telecharge une machine virtuelle ie8 pour faire le test sur ce navigateur ;)
