### ISSUE TITLE
Mettre un bouton loupe pour signaler l'update

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#624]
Après màj d'une demande, une ligne "Modification de NIR" montre un historique de modifs, et elle est cliquable.

Or l'utilisateur ne sait pas s'il peut modifier ou consulter la mise à jour.

Positionner une loupe ou bouton ou autre indicateur graphique

**Comment by vindarel** [comment]
Je ne reproduis pas sur ma staging : ( https://vince.mrs.yourlabs.org/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2

**Comment by vindarel** [comment]
Après fixs de la pipeline et re-build: pareil.  Normalement, on voit la loupe après une modif, pour tout type de demande.

![selection_251](https://user-images.githubusercontent.com/3721004/46740594-89e4aa00-cca3-11e8-9c1a-8873783e0341.png)

**Comment by notmoebius** [comment]
J'ai pas pu voir, pas encore en staging je pense.

**Comment by jpic** [comment]
Alors pas de panique les amiches, voila comment je m'y prends dans ces cas la.

- je me connecte sur le serveur de staging
- je balance un `sudo docker exec --user root -it mrs-vince env | grep COMMIT`
- oui parce que maintenant, les images te dropent par defaut en non-root, meme quand tu fais un docker exec, faut juste rajouter l'ingredient --user root a la commande docker exec et c'est bon par contre ;)

Resultat:

GIT_COMMIT=180ecf677bb2e2921f2a3774ba5e0b11f6892883

Humn, ca n'a pas l'air d'etre le bon commit ! Est-ce-que c'est bien l'image que la CI a builde sur ce commit qui est parti dans le deploy ?

Je regarde ta derniere pipeline, elle est [bien sur le commit 4328a](https://yourlabs.io/mrs/web/pipelines/755). Donc a priori gitlab checkout le bon commit.

Je regarde le [job docker-build](https://yourlabs.io/mrs/web/-/jobs/4407), il a bien pousse l'image betagouv/mrs:4328acb431780c7b024002c8349e0eaa947f6e72 !

Alors je regarde le [job de deploy sur ton instance](https://yourlabs.io/mrs/web/-/jobs/4409) et la surprise ! Il passe `betagouv/mrs:master` dans le docker run  au lieu de l'image avec ton commit en tag !

Humn, je regarde le [template de docker-run.sh justement](https://yourlabs.io/oss/playlabs/blob/master/playlabs/roles/project/templates/docker-run.sh#L14), il utilise bien la variable `project_image`.

Ooopsie, je realise que tout est de ma faute, l'update que j'ai fais ne permet plus a l'utilisateur deploy d'ecrire le fichier /home/$service/docker-run.sh, car il a le droit de l'executer en sudo. A la place, deploy a le droit d'ecrire le nom de l'image dans /home/$service/docker-image, et donc docker-run.sh doit le lire, et non utiliser `{{ project_image }}` ici !

En fait, docker-run.sh utilise le project_image de quand j'ai fais la reinstall en root, j'avais specifie image=betagouv/mrs:master. Du coup, tu pouvais deploy autant que tu veux mon pauvre ami, ca allait toujours lancer la meme image ! Confus ? Attends attends je vais y revenir !

Du coup, je fais un `sudo cat /home/mrs-vince/docker-image` et j'obtiens bien la bonne image:

betagouv/mrs:4328acb431780c7b024002c8349e0eaa947f6e72

Bref, y'avait aucune chance que tu trouve tout seul car je venais de le peter et de changer cette spec majeure :joy: 

Dans docker-run.sh, au lieu d'avoir l'image utilisee lors de l'install d'hard-codee, il faudrait un ptit $(<docker-image), car c'est le fichier qui contient le nom de l'image posée par l'utilisateur de deploy en non-root !

Bref, je me teste donc ce patche

```
diff --git a/playlabs/roles/project/templates/docker-run.sh b/playlabs/roles/project/templates/docker-run.sh
index d44673f..afe5d52 100644
--- a/playlabs/roles/project/templates/docker-run.sh
+++ b/playlabs/roles/project/templates/docker-run.sh
@@ -11,7 +11,7 @@ docker run -d --name {{ project_instance }} --restart unless-stopped \
     {% for key, value in project_env.items() %}
     -e {{ key }}='{% if value.replace is defined %}{{ value.replace("'", "\\'") }}{% else %}{{ value }}{% endif %}' \
     {% endfor %}
-    {{ project_image }}
+    $(<{{ project_home }}/docker-image)
 docker network connect {{ project_instance }} {{ project_instance }}
 {% for network in project_networks -%}
 docker network connect {{ network }} {{ project_instance }}
```

Et je relance une install depuis le dossier de mon inventaire mrs:

    playlabs deploy prefix=mrs instance=jpic image=betagouv/mrs:jpic


Ca a l'air de marcher, alors je vais verifier mes petits /home/mrs-jpic/docker-{image,run.sh} a la mano, et je trouve bien dans docker.sh:

```
        $(</home/mrs-jpic/docker-image)
```

Donc a priori c'est bon, il est dynamique a nouveau !

Apres, pour tester l'update, en tant qu'utilisateur deploy comme le fait la CI, je peux utiliser la meme ligne que la CI qui va se resumer a la meme chose avec en plus `deploy@` pour forcer le passage en utilisateur deploy, et `--tags=update` pour n'executer que les taches qui ont le tag update, mais bien sur je veux passer un autre tag d'image rien que pour l'embeter :joy:

    playlabs deploy prefix=mrs instance=jpic image=betagouv/mrs:vindarel deploy@ --tags=update

(playlabs va se demerder pour trouver la clef qui est dans inventory/keys/deploy, et il va aussi consulter ton inventaire, decouvrir que l'user deploy n'est pas dans le groupe sudo, et eviter de faire un sudo a l'execution, gogogadgetotomatisation !)

Donc c'est parti mon kiki, il fait l'update en mode CI, mais en direct, parce qu'on va pas y passer la nuit non plus :joy: :joy: :joy: private joke dedicasse pour les intimes :joy:

Et dans 

```
TASK [project : Execute docker-run.sh] *****************************************
```

Je trouve bien:

```
  - + docker run -d --name mrs-jpic -........ betagouv/mrs:vindarel
```

**IMPORTANT** tu dois etre au courant, mais n'oublies pas que github est public, et que ces commandes leakent des variables secretes, attention donc si tu t'avises de faire des copier coller !

Bref, je vais sur mon instance sur laquelle tourne ton image  et BOUYA ! Je voie la :mag: :joy:

![2018-10-10-164833_963x356_scrot](https://user-images.githubusercontent.com/94636/46745009-886baf80-ccac-11e8-8edd-b58ea2531371.png)

Conclusion, pour appliquer mon patch sur le fichier docker-run.sh qui est reserve a l'ecriture aux roots comme nous, je dois refaire l'install sur toutes les instances, bon comme la tache que je viens de changer a le tag docker-run, donc si je fais que ces taches la ca ira plus vite encore !

    for i in jpic tbinetruy vince staging ecole production; do playlabs deploy prefix=mrs instance=$i image=betagouv/mrs:master --tags=docker-run; done

il faut que je pushe mon patch en master sur yourlabs.io/oss/playlabs. Ensuite, je n'ai qu'a attendre 5 minutes qu'il fasse la pipeline dessus, qui buildera et poussera la nouvelle yourlabs/playlabs:master sur hub.docker.com. Car, notre tache de deploy en ci se fait [dans un container yourlabs/playlabs:master](https://github.com/betagouv/mrs/blob/master/.gitlab-ci.yml#L13-L16). Alors je relance juste [ton job de deploy sur ta branche](https://yourlabs.io/mrs/web/-/jobs/4417) tel qu'il etait maintenant ...  Et je constate bien dans la tache:

```
TASK [project : Execute docker-run.sh] *****************************************
```

Qu'il lance:

```
 docker run -d --name mrs-vince ..... betagouv/mrs:4328acb431780c7b024002c8349e0eaa947f6e72
```

Ce qui est la bonne image !

Et magie magie on voie la :mag: sur ton instance !

![2018-10-10-172935_1009x447_scrot](https://user-images.githubusercontent.com/94636/46747790-73921a80-ccb2-11e8-84d2-1a18896f36ab.png)


@vindarel si tu penses que ca vaut le coup n'hesites pas a creer une nouvelle page de doc, "cookbooks", qui concerne les conseils de la maison mais qui peuvent overlapper avec la doc upstream. Normalement, le reste de la doc ne devrait pas overlapper avec les docs upstreams (ie. la doc "normale" soit "non-cookbook" de MRS n'a pas pour but d'apprendre a utiliser docker en soit, c'est a la doc upstream, mais dans notre page cookbook, on peut partager nos recettes comme des bichons :joy:)

Pour moi, l'enjeu c'est plutot le partage d'un **savoir faire** qu'une liste de commande pour chaque cas d'utilisation possible que l'utilisateur pourrait etre tente de copier coller sans comprendre hihi mais ca passera evidemment par un bunch de commandes tout de meme histoire de get started et d'apprendre en se brulant ce qui est bcp plus fun :joy:

**Comment by vindarel** [comment]
Truc de OUF !!

ok j'agrémente le wiki.

**Comment by vindarel** [comment]
https://github.com/betagouv/mrs/wiki/Cookbook

plus qu'à merger et déployer, je fais une PR.

**Comment by vindarel** [comment]
https://github.com/betagouv/mrs/pull/636
