### ISSUE TITLE
Déplacer la case a cocher transports itératifs avant le premier champs de date

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#626]
Actuellement, l'utilisateur saisi une date, puis déclare cb de transports itératifs, puis, d'autres dates.

Pour fermer cette issue, il faut que l'utilisateur choisisse d'abord si il a des transports itératifs et combien, puis qu'il saisisse toutes ses dates d'un coup.

**Comment by notmoebius** [comment]
Exemple prototypage pour le multi-modal (merci @jpic):
![screencapture-localhost-8000-demande-2018-10-09-19_09_20](https://user-images.githubusercontent.com/32330644/46745491-70e0f680-ccad-11e8-8374-c6c4c287aede.png)
