### ISSUE TITLE
Modification d'affichage des stats

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#630]
L'ajout de la fonctionnalités des transports multi-modal, l'affichage des stats évolue (uniquement en partie back office)

Proposition: ajouter un suivi des demandes de type ATP (autres transports que VP).

- Nb de ATP/ caisse soumises, en-cours de traitement, validées ou rejetées
- de date à date
Pas de comparaison avec le taxi car pas de sens et pas d'économie sur ce mode de calcul.

**Comment by fjg** [comment]
Est-ce les stats publiques ? ou admin ?

Ajouter les libellés des textes de chaque stat pour bien préciser la demande (voir les écrans déjà développés pour s'en inspirer).
Comment calcule-t-on la stat ? Somme de quoi ? Autre formule ?

**Comment by notmoebius** [comment]
Les stats visibles uniquement en admin/profil stats

**Comment by jpic** [comment]
Désolé mais je crois qu'il faudra m'expliquer à l'oral parce que je suis un peu perdu :joy:

**Comment by fb86** [comment]
Ok, on fait un point jeudi avant ou apres le stand-up si tu veux.... Ou demain dans la journée. Milieu apres midi




Télécharger Outlook pour Android







On Tue, Oct 23, 2018 at 5:20 PM +0200, "∞" <notifications@github.com> wrote:












Désolé mais je crois qu'il faudra m'expliquer à l'oral parce que je suis un peu perdu 😂

**Comment by notmoebius** [comment]
Oui, ok pour moi de traiter en atelier, voir en openlab même si cela rsique de ne pas intéresser tout le monde.

**Comment by jpic** [comment]
D'accord avec @fb86 , c'est encore très flou pour moi

**Comment by fb86** [comment]
ISSUE A FERMER POUR EN FAIRE UNE NOUVELLE PLUS EXPLICITE

**Comment by notmoebius** [comment]
Fred va refaire
