### ISSUE TITLE
Faire évoluer la fonctionnalités d'export/import des stats

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#631]
Modification du fichier de sortie CSV

**Ajouter une colonne type de transport**:
- VP pour véhicule particulier
- ATP pour tous les autres types de transports
Attention en cas de cumul VP et ATP sur une meme demande d'assuré, faire 2 ligne : une pour VP, l'autre pour ATP

**supprimer les données inutiles** :+1: 
- nom assuré

### modifier le format de la caisse 
- mettre le numéro ( pour Haute Garonne : 01311, ariége 01091, PO : 01661......)

Une fois le fichier disponible en staging, je ferais mofifier la requete de darnelle

**Comment by fjg** [comment]
Que faut-il faire sur l'export ? On exportera quoi quand le formulaire multi-modal sera fait ?
Est-ce que le fichier CSV change ? Si oui quel sera le nouveau format ?
Est-ce que ca change l'import ?

**Comment by notmoebius** [comment]
> Que faut-il faire sur l'export ? 
**Ajouter une colonne type de transport qui sera valué à deux valeurs: VP ou ATP**
> On exportera quoi quand le formulaire multi-modal sera fait ?
**l'export actuel plus la nouvelle colonne**
> Est-ce que le fichier CSV change ? Si oui quel sera le nouveau format ?
**Non**
> Est-ce que ca change l'import ?
**Oui, une nouvelle colonne est à prendre en compte**

@fb86 ok pour moi

**Comment by jpic** [comment]
in staging

**Comment by fb86** [comment]
Ok, export fonctionne bien. Je propose juste la règle de gestion suivante en cas de date de mandatement differente pour une demandz comportant à la fois du vp et de atp.


Je propose que la date retenu soit la plus ancienne. 


A savoir si une demande en date du 1 octobre comporte un trajet en vp puis en train (atp), si la date de paiement du trajet en vp est le 3 octobre et que le date de paiement de atp est le 4, on retienne la date du 4 pour calculer la délais de paiement.




Ce cas (date de paiement différente pour un vp et un atp sur une demande) est statistiquement peu probable mais possible.




Pourquoi ce choix: on considère que le dossier est clos lorsque tout a été payé donc on prend la date du dernier paiement.




Si pas clair, je peux expliciter plus. 




Télécharger Outlook pour Android







On Thu, Oct 25, 2018 at 12:21 PM +0200, "∞" <notifications@github.com> wrote:












in staging

**Comment by jpic** [comment]
Reverté en staging

**Comment by jpic** [comment]
Fermé en faveur de la nouvelle issue #703 à valider.
