### ISSUE TITLE
MAJ du contenu des mails vers les assurés

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#632]
mails à maj:
- [ ] mail de réception de la demande
- [ ] mail récapitulatif de validation:
   * faire le récap VP
   * faire le récap ATP
   * faire le récap VP et ATP si tel est le cas

**Comment by fjg** [comment]
Contenu à préciser (sujet, texte...) @fb86 et @notmoebius

**Comment by fb86** [comment]
en faite ca change rien, je pense qu'on peut cloturer pour l'instant l US

**Comment by fb86** [comment]
Pour moi , pas de modification des mails

par contre, cela sous entend une modification du MOP car la liquidation n'est plus la meme
