### ISSUE TITLE
bascule non compilé

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#650]
lors de l'import des données du Gers, une assurée qualifiée en bascule a plusieurs demandes. 
Elle a bien été qualifiée en bascule mais une seule demande a été comptabilisée dans les économies.

Ci-dessous la demande 201809270021, l'assurée bien qualifiée en bascule mais l'économie n'apparait pas et elle est pas quantifiéE.

![narran demande 201809270021](https://user-images.githubusercontent.com/34480111/47026449-c01f9f00-d165-11e8-89ec-8c258f0d3b31.GIF)

La demande 201809270024 montre bien "bascule" et la ligne "économie calculée".

Les demandes sans cette "économie" ne sont pas comptées dans les stats, pourquoi ?

Or, on a le cas d'un assuré qui a basculé et dont toutes les demandes sont bien comptées pour l'économie réalisée (xx050036): l'import des stats s'est fait petit à petit (bascule ok, puis autres demandes). Pour le cas pb, l'import s'est fait tout d'un coup.

- [X] fix, unit test
- [X] écrire le script pour màj
- [ ] tester le script sur staging
- [ ] passer le script en prod

**Comment by jpic** [comment]
> Les demandes sans cette "économie" ne sont pas comptées dans les stats, pourquoi ?

Est-il possible de poster les preuves de cette affirmation svp pour comprendre ?

Merci

**Comment by jpic** [comment]
A mon avis il y a deux questions dans cette issue:

- pourquoi ne saffiche pas l'econnomie ici dans cette page,
- pourquoi ne serait-elle pas comptee dans une stat, on a besoin de savoir laquelle (un screenshot fera l'affaire) 

Il faut comprendre que ce sont des conditions independantes dans le code, et donc deux problemes differents.

**Comment by jpic** [comment]
L'economie ne s'affiche que si il y en a, donc si elle est inferieure a 0 on ne l'affiche pas, c'est peut etre un problem: https://github.com/betagouv/mrs/blob/master/src/mrsrequest/jinja2/mrsrequest/mrsrequest_detail.html#L334

Si la demande en question n'a pas ete importee, il n'y a pas de payment_base, donc, rien ne s'affichera non plus: https://github.com/betagouv/mrs/blob/master/src/mrsrequest/models.py#L389

Quand au "comptage dans les stats", il faut savoir de quoi il s'agit exactement, un screenshot fera l'affaire.

**Comment by notmoebius** [comment]
Dac, je vois avec Fred pour faire un screenshot

**Comment by jpic** [comment]
Excellent ! Merci pour le fichier, mais dans quelle(s) stats est-ce-que c'est pas compte exactement ?

**Comment by fb86** [comment]
On fait un atelier demain matin si tu es dispo 




Télécharger Outlook pour Android







On Wed, Oct 17, 2018 at 6:54 PM +0200, "∞" <notifications@github.com> wrote:












Excellent ! Merci pour le fichier, mais dans quelle(s) stats est-ce-que c'est pas compte exactement ?

**Comment by fb86** [comment]
Pas de soucis




Télécharger Outlook pour Android







On Wed, Oct 17, 2018 at 9:27 PM +0200, "∞" <notifications@github.com> wrote:












Merci pour l'invitation Fred, malheureusement je deteste etre en retard aux rendez vous, c'est pourquoi je ne prends jamais de de RDV le matin, mais si je suis dispo ca sera avec plaisir :)

**Comment by jpic** [comment]
Effectivement, hier je bossais jusqu'a 7h du mat, la je me suis leve a 7h pour votre atelier, bon, c'est assez brutal physiquement.
