### ISSUE TITLE
Rétention du nb de backup

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#651]
Pour préserver l'espace disque, il faut réduire le nb de backup de 90 à 10.

**Comment by jpic** [comment]
Malheureusement j'ai pas recupere grand chose ce faisant, le repo de backups fait tjs 30 gigs.

**Comment by jpic** [comment]
Ma question c'est est-ce-que vous voulez bien que je prune l'integralite des backups ? :joy:

Je pense que l'incrementiel n'est pas effectif entre differentes backups qu'on garde. On a aussi un peu change les chemins de fichiers (normalisation) en derniere version par exemple et je pense que l'incrementiel par rapport a de plus vielles versions n'est pas effectif.

**Comment by jpic** [comment]
Etant donner le plantage en prod, je shoot les backups.

**Comment by jpic** [comment]
Je n'ai pas eu d'autre choix que de shooter les backups de prod.
