### ISSUE TITLE
ETQ admin je suis averti en cas de suspission d' erreur de liquidation

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#658]
Dans la continuité de US 650,

En cas d'erreur de liquidation, le montant (base de remboursement) remonté par la  CPAM (import vers MRS) est plus important que le montant attendu. 

Pourrions nous avoir une alerte sentry lorsque c'est le cas ?

Cette mesure nous permettre de voir combien de cas sont concernés par mois et si cela nécessite d'envisager un signalement à la CPAM.

merci

**Comment by vindarel** [comment]
ps: priorité basse

**Comment by vindarel** [comment]
vérification manuelle: 3 demandes à économies négatives en novembre:

```
2018-11-21 17:37:09.526532+00:00, 201811210049
2018-11-10 16:35:39.999758+00:00, 201811100017
2018-11-09 10:50:24.888128+00:00, 201811090021
2018-08-31 12:32:39.228683+00:00, 201808310012
2018-08-21 14:57:48.391112+00:00, 201808210006
2018-07-12 15:12:49.071179+00:00, 201807120016
```

**Comment by vindarel** [comment]
- [X] fix server sentry inaccessible

**Comment by vindarel** [comment]
Problèmes d'espace disque à régler (en cours) avant de continuer sur ce ticket.

**Comment by jpic** [comment]
Petite question: pk ne pas envoyer un mail plutot qu'une alerte sentry ?
Ou encore, ajouter un filtre "economie negative" dans la page de liste pour les admins ?

**Comment by fb86** [comment]
Lors des premiers échanger l alerte sentry apparaissait la plus simple à mettre en place. Mais on est absolument pas figé sur la solution a mettre en oeuvre. 




Télécharger Outlook pour Android







On Sat, Dec 15, 2018 at 5:55 PM +0100, "∞" <notifications@github.com> wrote:












Petite question: pk ne pas envoyer un mail plutot qu'une alerte sentry ?

Ou encore, ajouter un filtre "economie negative" dans la page de liste pour les admins ?

**Comment by jpic** [comment]
D'apres ce que j'ai vu pour l'instant tu demandes regulierement des exports, autant les consulter directement dans le site, pour l'instant j'ai ajouté la colonne econnomie dans la page de liste pour les admin.

![2018-12-15-200201_1663x528_scrot](https://user-images.githubusercontent.com/94636/50046491-9bcc3a00-00a4-11e9-97e5-81a2a0a0f80c.png)

Je fais tourner l'issue dans la prochaine colonne mais n'hesites pas a re-ouvrir si tu as du nouveau.

**Comment by fb86** [comment]
Ok, merci 




Télécharger Outlook pour Android







On Sat, Dec 15, 2018 at 8:04 PM +0100, "∞" <notifications@github.com> wrote:












Closed #658.

**Comment by notmoebius** [comment]
Erreur 500 sur le filtre pour afficher l'alerte dans la page caisse.

**Comment by jpic** [comment]
Résolu !
