### ISSUE TITLE
impact nouveau formulaire, introduction ATP - Stats multi-modal

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#666]
Dans le SI de l'Assurance Maladie, on dissocie les VP des autres transports particuliers (ATP) que représentent les transports en commun, l'avion ou le train.

L'introduction de ce nouveau mode dans le formulaire nécessite de distinguer les deux modes dans la base MRS.

Il faut donc introduire une distinction entre les 2 dans les tables.

Cette distinction sera visible
- lors des import / export : il faut faire apparaître le type de transport ATP ou VP . En cas de déclaration simultanée du VP et ATP, il faut pouvoir exporter 2 lignes pour une même demande (une ligne pour la partie VP et l'autre pour la partie ATP) : voir https://github.com/betagouv/mrs/issues/631

- À l'affichage dans la partie synthèse : il faut distinguer les informations relevant du VP et celles de ATP https://github.com/betagouv/mrs/issues/629

![nouvel affichage synthese](https://user-images.githubusercontent.com/34480111/47295053-0619ae80-d60f-11e8-8ba2-6580f1821545.GIF)

- modifier les stats en back office pour visualiser le nombre de demandes relevant d'un ATP + Nbr d'assuré ayant fait une demande en ATP : voir https://github.com/betagouv/mrs/issues/630

**Comment by jpic** [comment]
Exporter deux lignes pour une même demande ok mais n'y-a-t-il aucun impact sur l'import ? On reste sur un champs de base de paiement ? Merci

**Comment by fb86** [comment]
Yes, c là la difficulté. Il faut qu on en parle demain. 




Télécharger Outlook pour Android







On Mon, Oct 22, 2018 at 8:55 PM +0200, "∞" <notifications@github.com> wrote:












Exporter deux lignes pour une même demande ok mais n'y-a-t-il aucun impact sur l'import ? On reste sur un champs de base de paiement ? Merci

**Comment by jpic** [comment]
Reste la #630
