### ISSUE TITLE
SORTIE STAT PAR PRESCRIPTEURS

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#672]
j'aii besoin d'une extraction des données par prescripteurs 

pourrais je avoir un fichier m'indiquant par prescripteurs le nombre de demandes, le nombre d'assurés, le montant globale des montants remboursées, le montant des économies

A partir de cette extraction, il pourra être mené une reflexion sur de nouvelles sorties de stat;

**Comment by vindarel** [comment]
(prescripteur: récupéré avec n° adeli ou finess)

**Comment by notmoebius** [comment]
feature done
