### ISSUE TITLE
Stats: écarts de chiffres (nombre d'assurés ayant basculé, délai de traitement,…)

### ISSUE THREAD

**Issue by vindarel** [betagouv/mrs#678]
entre le front et le back: 147 vs 189.

Pourquoi ? Lequel est le bon ???

**Comment by jpic** [comment]
C'est déjà connu, c'est parce que des utilisateurs ont plusieurs demandes avec le champs bascule.

**Comment by vindarel** [comment]
Écart du délai moyen de traitement (4.05 / 4.36).

**Comment by jpic** [comment]
Mieux vaut de faire une issue par bug.

**Comment by jpic** [comment]
Le delai ne sera jamais exactement le meme car les données des deux pages ne sont pas calculés au même moment avec les mêmes données.

**Comment by fb86** [comment]
L 'ecart entre les stat front office et back office est stabilisé sur le nombre d'assuré ayant basculé. Il reste un écart de 4 qui doit être analysé avec l'Ariege et l'Aude pour identifier si les assurés sont de véritable bascule.

L'ecart sur le montant basculé est lié à l'ecart évoqué ci-dessus.

Concernant l'écart sur le délai de traitement, Il n'y a en fait pas d'écart mais une différence de calcul.

EN front , il s'agit de la moyenne de l'ensemble des delais de traitement, sur le back il s'agit de la moyen des moyennes quotidienne des délais de traitement.

solution préconisée : modifier le libélé du delais de moyen de traitement sur le back office.

**Comment by jpic** [comment]
Est-ce-que c'est regle ?

**Comment by fb86** [comment]
Pratiquement, il faut juste que je fasse verufier 4 dossiers pour savoir si les assures sont oui ou non basculer et on a aura fini. 




Télécharger Outlook pour Android







On Sat, Nov 10, 2018 at 11:30 AM +0100, "∞" <notifications@github.com> wrote:












Est-ce-que c'est regle ?

**Comment by fjg** [comment]
duplicate
