### ISSUE TITLE
Différence d'affichage entre staging et production

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#696]
En staging, l'admin affiche cela:
![image](https://user-images.githubusercontent.com/32330644/47711549-c6b61800-dc35-11e8-9c04-0561cfb6c9d8.png)

la prod:
![image](https://user-images.githubusercontent.com/32330644/47711584-d6cdf780-dc35-11e8-818e-434751eace1c.png)

**Comment by jpic** [comment]
Voici pour le titre:

![2018-10-30-124712_1246x544_scrot](https://user-images.githubusercontent.com/94636/47720948-5916e580-dc4f-11e8-93c6-748d1dd1c6fa.png)

Quelles autres actions à prendre pour fermer l'issue svp ?

**Comment by notmoebius** [comment]
C'est bon pour moi
