### ISSUE TITLE
Traduire les infos affichant "prendre le rôle de..."

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#698]
Quand je prend le rôle d'un utilisateur, le menu affiche "become". Possible de mettre à la place: "Prendre le rôle" ou "Devenir":
![image](https://user-images.githubusercontent.com/32330644/47712179-59a38200-dc37-11e8-94c7-5ce23fb4e159.png)

Une fois que l'on a basculé vers l'utilisateur, un message d'état s'affiche en EN:
![image](https://user-images.githubusercontent.com/32330644/47712233-7475f680-dc37-11e8-89a4-b710fe3e4234.png)

**Comment by jpic** [comment]
![2018-11-14-180410_274x31_scrot](https://user-images.githubusercontent.com/94636/48499112-f40ae480-e837-11e8-9d48-e3079e90f1c9.png)
![2018-11-14-180402_258x41_scrot](https://user-images.githubusercontent.com/94636/48499113-f4a37b00-e837-11e8-9f10-1010cfbab93b.png)

wech usurpateur :joy:
