### ISSUE TITLE
Import/export de dates de mandatements par mode pour recalcul des delais

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#703]
Actuellement, l'admin ne voit que les délais de paiements VP, qui sont calculés à partir du champs `mandate_date`, qui est importé en CSV par l'équipe stats.

Quand une demande multimode sera validée deux jours différents, il faut utiliser la date la plus récente pour les calculs de délais, et recalculer toutes les stats de délais en fonction: notamment les stats quotidiennes à partir de la plus ancienne date de mandatement.

Dans le même temps, le script SQL ne traite que les demandes exportées, il faut donc bel et bien conserver les dates de mandatement de chaque mode, pour continuer d'exporter les demandes auxquelles il manque une date de mandatement pour un mode.

De part l'expression des besoins ci-dessus, du point A au point B, compte tenu des contraintes, les actions à prendre sur la codebase de ce repo découlent ainsi:

- [x] ajouter les colonnes `modeatp` et `modevp` dans l'export
- [x] renommer `MRSRequest.mandate_date` en `MRSRequest.mandate_datevp`,
- [x] ajouter `MRSRequest.mandate_dateatp`,
- [x] ajouter `MRSRequest.mandate_date`, qui retourne la plus récente des dates
- [x] renommer la colonne dans l'export `mandate_datevp`
- [x] ajouter une colonne vide dans l'export `mandate_dateatp`,
- [x] importer `mandate_datevp` colonne dans l'import,
- [x] changer l'export qui actuellement n'exporte que les demandes qui n'ont pas de date de mandatement vp, pour qu'il exporte toutes les demandes qui ont `modevp` et pas `mandate_datevp` ou alors qui ont `modeatp` et pas `mandate_dateatp`
- [x] changer l'import pour qu'il recalcule aussi toutes les stats de delais à partir de la date de mandatement, pour la meme caisse/institution, caisse sans etablissement, et caisse avec etablissement, etablissement sans caisse

**Comment by notmoebius** [comment]
> 
> 
> La question qui reste en suspens c'est est-ce-qu'on ajoute une deuxieme colonne de délais **par demande** ou est-ce-qu'on change le calcul existant pour faire une moyenne des deux.

Je reformule: si une demande contient deux types de transports VP+ATP, faut-il faire une moyenne des deux ? Je dirais qu'il ne faut pas faire de moyenne, ils seront traités dans la foulée donc les dates seront identiques. Sous réserve que Fred ou la liquidation infirme. 

Je pose la question pour connaître l'état de la date de mandatement.

**Comment by jpic** [comment]
@fjg ce qui s'est passé c'est qu'à l'atelier avec @fb86 on a fait le tour de ce qui était *possible*, reste à définir ce qui *fait sens*.

**Comment by jpic** [comment]
@notmoebius Juste Fred disait que ça serait pas forcément les mêmes dates.

En quete de sens ma question est donc: que cherche-t-on a obtennir ? Est-il possible de rédiger une US qui fait sens, au delas de "on modifie le form donc tout le reste"

**Comment by fb86** [comment]
Yes, le paiemenr en atp et vp etant dissocier dans nos chaine de paiement, il est théoriquement possible que les date de liquidation soient differente. C pour ca sue j avais proposé de retenir la date la plus recente en cas de nécessité de choix.... Apres c est peu probable dans la vie de tous les jours 




Télécharger Outlook pour Android







On Tue, Oct 30, 2018 at 4:16 PM +0100, "∞" <notifications@github.com> wrote:












@notmoebius Juste Fred disait que ça serait pas forcément les mêmes dates.


En quete de sens ma question est donc: que cherche-t-on a obtennir ? Est-il possible de rédiger une US qui fait sens, au delas de "on modifie le form donc tout le reste"

**Comment by jpic** [comment]
Merci effectivement c'est ce que tu m'as dit !

Actuellement, la fonction de recalcul des stats affectées par une sauvegarde de demandes recalcule toutes les stats de la meme date et pour la meme caisse/institution, caisse sans etablissement et caisse avec etablissement.

Dans ce cas, ça veut dire qu'il faudra, en plus des étapes listées ci-dessus, lors de l'import et quand la date de mandatement changera, recalculer toutes les stats de delais à partir de la date de mandatement, pour la meme caisse/institution, caisse sans etablissement, et caisse avec etablissement.

J'ai mit à jour le post ci-dessus. Si vous voulez prioriser cette tache alors je conseille de le faire en connaissance de cause du reste du backlog.

**Comment by jpic** [comment]
J'ai terminé la rédaction de l'issue, d'avance merci pour vos commentaires, si c'est bon pour vous on peut l'accepter en dev.

**Comment by fb86** [comment]
Super, juste tu nous dis laquelle c est. Son numéro. 




Télécharger Outlook pour Android







On Wed, Oct 31, 2018 at 12:06 AM +0100, "∞" <notifications@github.com> wrote:












J'ai terminé la rédaction de l'issue, d'avance merci pour vos commentaires, si c'est bon pour vous on peut l'accepter en dev.

**Comment by fb86** [comment]
Je propose de mettre 2 champs date de mandatement comme le propose jamesi. Dans la majorité des cas, il n'y aura qu une date. Celle du paiement du vp ou de atp. De tant en temps, nous aurons une date pour le vp et l autre pour le atp (date identique). Et exceptionnellement, nous aurons une date différente piur le vp et atp. Dans ce cas, on prend la date la plus recente pour le cacul du delais, en considerant que le dossier est terminé lorsque tout est payé.💪
Attention, la plupart du temps, il n y aura qu une date. Donc il faudra faire attention sur la comparaison entre les 2 dates.

**Comment by notmoebius** [comment]
Une précision pour être sûr d'avoir compris: quand on parle de date récente, on prend:
- date de réception: 10/10/2018
- date de mandatement VP: 12/10/2018
- date de mandatement ATP: 13/10/2018
la date du 13/10/2018 comme date la plus récente, c'est ça @fb86 ?

**Comment by fb86** [comment]
Yes, c est ça 




Télécharger Outlook pour Android







On Wed, Oct 31, 2018 at 10:17 AM +0100, "notmoebius" <notifications@github.com> wrote:












Une précision pour être sûr d'avoir compris: quand on parle de date récente, on prend:

date de réception: 10/10/2018
date de mandatement VP: 12/10/2018
date de mandatement ATP: 13/10/2018

la date du 13/10/2018 comme date la plus récente, c'est ça @fb86 ?

**Comment by jpic** [comment]
Les changements n'impactant pas la compat sont passes en master.
Les autres sont dans la #763.
