### ISSUE TITLE
Modifier le mail d'archivage suite à update nir/date naissance

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#707]
Ajouter la notion de modification nir/date de naissance.

Le texte actuel en normal, les propositions de MAJ en gras:

> Bonjour,
> 
> Voici l'archive de la demande de remboursement via MRS n°201810300000 :
> 
>   Référence : 201810300000
>    Prescription Médicale de Transport (PMT) : Capture d’écran 2018-10-25 à 14.54.24.png
>    Prénom : test fjg
>    Nom de famille : fjg
>    Date de naissance : 1 janvier 1970 **initialement saisie 1 janvier 1971**
>    NIR : 1234567891212 **initialement saisie 1345566778734**
>    Adresse email : testfjg@fjg.com
>    Date du trajet aller simple 1: 1 octobre 2018
>    Date du trajet aller simple 2: 10 octobre 2018
>    Kilométrage total parcouru en voiture : 10
>    Montant total des frais en VP : 0,00
> 
> Cordialement,
> L'équipe MRS

Fini quand le mail d'archivage tient compte de la modification.

**Comment by vindarel** [comment]
S'assurer que le sujet du mail contient le dernier NIR.

**Comment by vindarel** [comment]
Testable sur ma staging (vince.mrs…)

**Comment by fjg** [comment]
Attention il faut utiliser la 1ère modification (quand il y a plusieurs) pour référencer le NIR ou la date de naissance d'origine cf. exemple https://staging.mrs.beta.gouv.fr/admin/mrsrequest/b42aff9b-6348-4821-87ec-d3ebae584033

**Comment by vindarel** [comment]
Déployé sur staging.
