### ISSUE TITLE
Etq assuré je veux déposer la reference de ma PEL 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#719]
En cours de redaction, ne pas prendre e' compte cette issue en l etat

Etq assuré, je peux indiquer la reference de ma prescription electronique en ligne plutôt que de dépose ma pmt scanner.

Cette us necessite une modification du formulaire. Il faut :
- creer un champ texte dénommé " reference de votre prescription en ligne électronique". Champs x caractere alpha numerie
- modifier les regles de gestion sur la pmt en imposant soit la pmt scannee ou la référence du dossier pel.
- préparer un petit zoom expliquant ce qu est la pmt electronique. 
-modifier la faq en consequence (a faire par entrapreneur)

**Comment by jpic** [comment]
A priori c'est fait merci de reouvrir autrement
