### ISSUE TITLE
Rajouter le bloc "Ils ont déjà utilisé notre service" (témoignages utilisateurs)

### ISSUE THREAD

**Issue by fjg** [betagouv/mrs#72]
C'est pas une urgence, mais tant qu'on est sur la reprise de la page actuelle, ca peut en faire partie.
A vous de voir.

**Comment by tbinetruy** [comment]
Salut !
voila les deux commits @jpic :
- https://github.com/sgmap/mrs/commit/1a199b8efa6cf8f7a44c235e8d1b297c25d8f5f1
- https://github.com/sgmap/mrs/commit/6ce27cc03256961c5c9bcc8f0b6be51d8cb70fa6

;)
