### ISSUE TITLE
Modale de modification de date de naissance: format de date sur IE

### ISSUE THREAD

**Issue by vindarel** [betagouv/mrs#726]
On obtient seulement 2 petites flèches, pas de widget date comme sur le formulaire.

**Comment by jpic** [comment]
C'est l'implementation du navigateur internet explorer qui est ainsi.

**Comment by notmoebius** [comment]
![image](https://user-images.githubusercontent.com/32330644/49430791-42166680-f7ac-11e8-9736-41f636fe6657.png)

Proposer la saisir en FR.

**Comment by vindarel** [comment]
note comme discuté hier: on avait vu ça avec @Johan1983 et ce n'était pas sur IE.
