### ISSUE TITLE
Suppression utilisateurs dans admin

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#729]
EN admin quand on veut supprimer un utilisateur cette fonction n'est pas possible à travers le menu "Action".
Cela est possible néanmoins lorsque l'on coche un profil, en bas de fenetre apparait un bouton 'delete object".
Il faudrait que la fonction "supprimer" apparaisse dans le menu "action".

**Comment by jpic** [comment]
On avait dit qu'on ne supprimerait pas d'utilisateur car cela affecterai l'historique, on peut cependant les désactiver.

C'est pour quel utilisateur sur quelle instance ?

**Comment by Johan1983** [comment]
C’est pour les utilsateurs chef de projet qui ont la casquette upn + stat. Ces personnes avaient deux identifiants differents. Avec le multi support il faut supprimer ou desactiver un des identifiants.
J’ai supprimé le profil stat de Carole M. du 65. J’ai test le profil multisupport sur son profil.

**Comment by jpic** [comment]
Pk on a reouvert au fait svp ?
