### ISSUE TITLE
calcul du nombre d'assuré ne fonctionne plus

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#731]
Sur la page stat du back office, le  "nombre d'assurés avec un dossier traité durant la période" est égal à 0 quelques que soit la période.

**Comment by jpic** [comment]
Bien vu !!!!

Un petit oubli depuis la nouvelle version, on appelait l'ancienne fonction pour securiser les demandes par rapport a l'utilisateur, et j'ai du voir passer la modif dans les tests, c'etait obligé qu'on ait un bug comme ca statistiquement, la question qui m'interresse est y-en-a-t-il d'autres dans le genre, "objets que je voie plus en base" ? C'est une possibilité a garder a l'esprit quand on teste ;)

Encore merci pour l'issue :heart:

**Comment by fb86** [comment]
Avec plaisir... 




Télécharger Outlook pour Android







On Sun, Nov 18, 2018 at 7:03 PM +0100, "∞" <notifications@github.com> wrote:












Bien vu !!!!


Un petit oubli depuis la nouvelle version, on appelait l'ancienne fonction pour securiser les demandes par rapport a l'utilisateur, et j'ai du voir passer la modif dans les tests, c'etait obligé qu'on ait un bug comme ca statistiquement, la question qui m'interresse est y-en-a-t-il d'autres dans le genre, "objets que je voie plus en base" ? C'est une possibilité a garder a l'esprit quand on teste ;)


Encore merci pour l'issue ❤️

**Comment by jpic** [comment]
En fait je crois que c'est parce que j'ai regenere ces fixtures a un moment ou les demandes du jeu de test n'etaient plus a la suite, du coup j'ai accepte le passage a 0 dans les tests en me disant que je le fixerai en fixant le jeu de data de tests, que j'ai fais par la suite en faisant un rebase (il me semble que j'ai rebasé cette branche du code discretement depuis plusieurs semaines hihi)

**Comment by jpic** [comment]
Et la #598 alors ? :joy:

**Comment by jpic** [comment]
2 regles d'or pour bien gerer les issues:

- pas de duplication d'issue
- pas de recyclage d'issue
