### ISSUE TITLE
Design contact form

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#75]
Actuellement le formulaire de contact semble s'étendre sur moins de largeur que l'autre formulaire ce qui lui donne un air "étroit" notamment par rapport a la version actuellement en production.

Le formulaire de contact est dispo sur la branch master. J'ai jetté un oeil rien vu qui sautait aux yeux et moved on, peux-tu checker stp ?

Merci ;)

**Comment by jpic** [comment]
Coucou @tbinetruy  !

Est-ce-que t'as bien eu le contact form qui est sur la master branch ?

Merci ;)

**Comment by jpic** [comment]
@tbinetruy c'est ta mission à faire pour demain si possible (avec #78)

**Comment by tbinetruy** [comment]
Hello !
 
J'ai eu un imprevu cette apres midi, desoler pour cette reponse tardive. Le commit du fix : https://github.com/betagouv/mrs/commit/fb32e73247f2c15937ea7eef295955c51326a63c
