### ISSUE TITLE
Dette champs modifies

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#765]
Bug: dans les modales la date ne s'affiche pas en FR.

Nous rencontrons quelques galeres avec la detection de modification de champs ainsi que la recuperation et l'affichage.

Actuellement non bloquantes, elles causent tout de meme un nombre de requettes SQL excessives.

A noter que le fait que le JSONField ne supporte le stockage de datetime en soit, qu'il y a une operation a faire sur la valeur stockee en champs texte avant de pouvoir la comparer.

Il faut une nouvelle methode propre pour recuperer la valeur originale d'un champs, et refactoriser celle ci avec l'actuelle field_changed, penser a egalement limiter le nombre de DB hits qui passe la barre des **20 requettes** sur la vue de detail.

**Comment by vindarel** [comment]
- [] design session entre devs

**Comment by vindarel** [comment]
testable en staging:

- [ ] les champs de dates, notamment dans la fenêtre de "suivi du dossier", sont au format français jj/mm/yyyy.
