### ISSUE TITLE
Affichage de la distance en km sur BO/admin

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#768]
Vu en stagging: si je souhaite modifier une demande soumise, dans le cas d'un ATP (donc sans VP et donc de distance), je peux ajouter une distance.
![image](https://user-images.githubusercontent.com/32330644/49361951-97377700-f6dd-11e8-90be-cf2ec8ab070c.png)

Cas usage : MAJ d'une demande VP ou VP+ATP, le champ distance peut être présenté en modificaiton.

Cas usage : MAJ d'une demande ATP uniquement, ne pas permettre de mettre à jour le champ distance.

**Comment by notmoebius** [comment]
En lien peut-être avec l'issue #717

**Comment by jpic** [comment]
Bravo d'avoir trouve cette regression introduite par mes soins dans 2e154b465dbf284c5824e63ebbcbb16024dd0f05

C'est lié a la copie automatique de la date d'aller a la date retour, visiblement, j'essayais d'introduire une verification avant d'ecraser la date de retour suite a la modification de la date de depart. Cette verification n'etait pas efficace lors de la saisie manuelle, qui rempli le champs bout par bout et non d'une traite , ce qui est le cas via le widget.
