### ISSUE TITLE
Pas de delete du nombre de trajets itératifs

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#774]
Actuellement : une fois saisi un nombre de 1 trajet itératif, il n'est pas possible de le supprimer.
Il est uniquement possible de l'augmenter avec le clavier fleche.

DOD :
Quand on fait back space, possibiliter de supprimer le chiffre saisie

![bug saisie trajet iteratif](https://user-images.githubusercontent.com/34479425/49458291-d56f8c00-f7ec-11e8-8ece-fef8cd9c6f76.png)

**Comment by jpic** [comment]
In staging 70631c5541b582d29447d040724d01431c6ac020
