### ISSUE TITLE
Trigger d'erreur sentry en cas d'erreur de POST ajax sur le formulaire de demande

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#779]
J'ai voulu saisir la même demande (pour valider l'issue #581) et le serveur m'a affiché ce message :
![image](https://user-images.githubusercontent.com/32330644/49515705-f9d47280-f897-11e8-882b-a75cc8479112.png)

Après avoir saisie une première demande, j'ai cliqué sur "**_Nouvelle demande : même assuré_**" ("same player, shoot again !"), je fais une saisie identique et j'ai cette erreur.

Pour cloturer cette issue, il faut que le client remonte l'erreur a sentry. Si le message tombe pendant des messages de deploiement c'est pas grave. Autrement, c'est qu'il faut se ruer sur les logs serveurs :joy:

**Comment by jpic** [comment]
Merci, cependant je n'arrive pas a reproduire.

Pour info, cela arrive lorsqu'aucune donnee n'est envoyee en requete POST.

J'ai saisi une premiere demande, cliqué sur nouvelle demande: meme assuré, j'ai resaisi la demande et je suis bien tombe sur la page de confirmation.

**Comment by jpic** [comment]
D'acc moi je demarre mon windows pour tester :joy:

**Comment by notmoebius** [comment]
Bon, je ne reproduis plus....j'ai dû tombé pendant un down ou déploy...Je ferme l'issue

**Comment by jpic** [comment]
J'ai corrige un bug comme ca ce matin, mais je ne me rappelle pas si c'etait avant ou apres l'avoir envoyé en staging ... et je /crois/ que non :joy:
