### ISSUE TITLE
Centrer le bouton Envoyer issue #60 et #75

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#78]
Centrer le bouton Envoyer (tester sous Chrome) du formulaire de contact.
Il est actuellement aligné à gauche par rapport au champ Message.

**Comment by jpic** [comment]
@tbinetruy c'est ta mission à faire pour demain si possible un bon coup de bichonnage sur le form de contact (aussi trop "étroit" en largeur par rapport à la prod cf. #75)

**Comment by tbinetruy** [comment]
ok !!

**Comment by jpic** [comment]
@tbinetruy rencontres tu un blocage ?

**Comment by tbinetruy** [comment]
Salut !

J'ai eu un imprevu cette apres midi, desoler pour cette reponse tardive. Le commit du fix : https://github.com/betagouv/mrs/commit/363c5d54bb500e9f5efefdb6ffee36f3446182e9
