### ISSUE TITLE
Pas de signalement date identique

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#780]
J'ai saisie 2 demandes: 201812050015 et 201812050016 pour la même assurée avec une date qui chevauche (26/11/2018), je n'ai pas eu de signalement, la seconde demande est passée sans signalement.

Première demande:
![image](https://user-images.githubusercontent.com/32330644/49516576-3acd8680-f89a-11e8-8827-0183ec14e48a.png)

Seconde demande:
![image](https://user-images.githubusercontent.com/32330644/49516649-6486ad80-f89a-11e8-929a-bab016fa5035.png)

La différence entre les 2 demandes, une n'a que des aller(s), la seconde a des A/R ! Mais avec une date en commun, le 26/11/2018.
MRS aurait dû au moins signalé la date du 26/11/2018 comme déjà saisie.

DoD:
- si une date de trajet en commun, un signalement doit apparaître signalant que le trajet du 26/11/2018 est identique dans un demande précédente.

**Comment by notmoebius** [comment]
Test fait en stagging bien sûr.

**Comment by notmoebius** [comment]
Le signalement fonctionne sur le même type de demande, j'ai fait une demande avec que des aller et avec le 26/11/2018 en commun et le signalement est bien géré:
![image](https://user-images.githubusercontent.com/32330644/49516922-12925780-f89b-11e8-9354-3709625b1dd8.png)

J'ai forcé la demande est est la n°201812050017.

**Comment by jpic** [comment]
La raison pour laquelle la premiere demande n'a pas ete detectee est que le NIR est different entre les deux demandes.
![2018-12-05-145630_457x33_scrot](https://user-images.githubusercontent.com/94636/49518147-399e5880-f89e-11e8-83c3-8d6f650d3352.png)
![2018-12-05-145625_440x39_scrot](https://user-images.githubusercontent.com/94636/49518148-3a36ef00-f89e-11e8-92e1-a1eaafbf0202.png)

**Comment by jpic** [comment]
Pour info les tests sont ici : https://github.com/betagouv/mrs/blob/master/src/mrsrequest/tests/test_mrsrequest_form.py#L101-L138

**Comment by notmoebius** [comment]
Ah oui, je vois l'erreur !! 'est entre le clavier et l'écran. Autant pour moi.
