### ISSUE TITLE
Modification du statut d'une demande impossible

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#80]
Dans le nouvel écran de consultation et maj du BO, le changement de statut n'est plus possible:
- passer de soumise à rejetée ou
- passer de soumise à validée
Pourtant ces statuts apparaissent comme filtre.

**Comment by jpic** [comment]
Dupliqué de l'issue #24 ?

**Comment by jpic** [comment]
La nouvelle interface d'admin met à jour le status en base ;)

![2018-01-16-011353_971x183_scrot](https://user-images.githubusercontent.com/94636/34966234-9fa141c6-fa5a-11e7-8b4b-c0e1932871e4.png)
