### ISSUE TITLE
Evolution formulaire contact assuré

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#804]
Actuellement, le visiteur peut saisir son nom/mail/message dans la page de formulaire de contact, ce qui lui envoie un accuse de réception et envoie un mail à l'équipe MRS.

Pour cloturer l'issue, modifier la page contact du site MRS de la sorte:

- [x] ajouter un champs de selection de motif parmis les choix suivants:
  - Erreur dans votre demande
  - Réclamation sur le traitement de votre demande
  - Question sur le site
  - Autre
- [x] ajouter le champs de selection "Votre caisse" parmis les caisses actives
- [x] afficher la caisse et le motif dans le corps du mail envoyé à la soumission du formulaire
- [x] si l'utilisateur a choisi "erreur" ou "réclamation" sur demande:
  - [x] le destinnataire du mail est l'équipe de la caisse (`Caisse.email`) choisie (au lieu de l'envoyer à l'équipe MRS)
  - [x] le sujet de mail est "RECLAMATION MRS" au lieu de "Nouveau message depuis le site",
  - [x] le corps du mail commence par une phrase d'introduction type "Bonjour, veuillez trouver ci-dessous une réclamation déposée ce jour sur le site par un de vos assurés".

**Comment by vindarel** [comment]
Use betagouv's Vue framework ? https://assurance-maladie-digital.github.io/vue-dot/

**Comment by jpic** [comment]
Il faut en discuter assez longuement après la MEP, mais je vois plusieurs
debats a avoir en équipe :

- le code en Ajax sur le formulaire de front devient de plus en plus
limitant comme on peut le constater avec l'épic de confirmation de date, il
faut une exit strategy
- la CPAM reprendra le projet en 2020, je suppose qu'ils préfèrent que le
front soit avec leur bibliothèque d'UI, plutôt que le spaghetti code qu'est
l'Ajax en jQuery actuellement en place
- dans ce cas faut il remplacer les 2-3 Components preact pour virer preact
en avance de phase ? Où est ce que ça attendra une phase d'optimisation
- la design session est bien entendue de rigueur avant de commencer a coder
-

**Comment by vindarel** [comment]
Devrait être bon. Reste un peu de code cleanup et adapter les tests.

**Comment by vindarel** [comment]
CI: damn, it works locally TM©.

**Comment by notmoebius** [comment]
Petit bug d'affichage sur la combo:
![image](https://user-images.githubusercontent.com/32330644/50596738-8416f300-0ea5-11e9-815d-68325220fc34.png)

**Comment by notmoebius** [comment]
La soumission du formulaire en erreur ne permet pas de corriger sa saisie:
![image](https://user-images.githubusercontent.com/32330644/50596920-f556a600-0ea5-11e9-8298-9d7e7f376a6d.png)
