### ISSUE TITLE
[paused] Accorder l'icône sur le suivi des demandes (contact, modification, rejet, validation...)

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#811]
Actuellement, il y a une icone de loupe sur tous les items de l'historique de demande dans la page d'admin detail de demande.

Pour cloturer cette issue, il faudrait que chaque type d'evenement historique ait sa propre icone.

**Comment by vindarel** [comment]
Le titre et le contenu parlent-ils de la même chose ?

> (contact, modification, rejet, validation...)

vs

> icone de loupe sur tous les items de l'historique de demande dans la page d'admin detail de demande.

pour ce point je propose ces trois icônes:

![selection_263](https://user-images.githubusercontent.com/3721004/50294090-642f0a80-0475-11e9-8f8f-c26884262c91.png)

**Comment by notmoebius** [comment]
Pour moi, l'icône NIR et Date mon conviennent.
L'icône "puce" pour la localisation géo me semble pas forcément clair, une route ou un véhicule ?

**Comment by notmoebius** [comment]
Pour l’instant, on garde la loupe avec appel au clic (bleu...?). Çà passe en production et l'équipe attend le retour des utilisateurs après information newsletter sur la feature de modification d'une demande par le liquidateur.

**Comment by jpic** [comment]
Resultat suite au changement d'icone:
![2019-02-11-125514_440x423_scrot](https://user-images.githubusercontent.com/94636/52561805-bf89d300-2dfc-11e9-9b2e-f07a9c773bd5.png)

**Comment by jpic** [comment]
![2019-02-11-130812_470x129_scrot](https://user-images.githubusercontent.com/94636/52562365-979b6f00-2dfe-11e9-9fef-19bc3f2c3dfb.png)
![2019-02-11-130756_480x133_scrot](https://user-images.githubusercontent.com/94636/52562366-979b6f00-2dfe-11e9-982a-b0705d73b913.png)
