### ISSUE TITLE
Integration vidéo tuto sur Front

### ISSUE THREAD

**Issue by Johan1983** [betagouv/mrs#813]
@FrancoisPhilippe  a réalisé un psd du front pour l'intégration de la vidéo tuto.
Des modifications ont eu lieu : suppression du bloc "avant" "apres" pour intégration du player.
Le lien Youtube et le code embed sera envoyé sur Slack.

DOD :
L'utilisateur à accès à un tuto vidéo "Comment faire ma demande de remboursement de transport VP" sur le site MRS.
![maquettemrs_desktophome1218_960px](https://user-images.githubusercontent.com/34479425/50276483-5a3fe400-0442-11e9-9ecd-04003a0f6918.png)
[maquetteMRS_desktopHome1218.psd.zip](https://github.com/betagouv/mrs/files/2698187/maquetteMRS_desktopHome1218.psd.zip)

**Comment by jpic** [comment]
Quelle est l'URL de la video svp ?

**Comment by Johan1983** [comment]
Yes pour le moment je ne l’ai pas indexé.
Voici le lien :
https://youtu.be/TzrDppmF4vY

**Comment by jpic** [comment]
En staging.
Largeur: max.
Hauteur: redimensionnement automatique en 16/9emes

**Comment by jpic** [comment]
OK pour moi sur:

- firefox
- ie11
- chrome
