### ISSUE TITLE
[US] ETQ admin, jeux exporter les données de la BDD

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#815]
objectif: permettre d'extraire via un requêteur SQL (ou Query By Example) les données nécessaire aux études stats et comportementales.

Pour clôturer l'issue, ajouter un item "Extraction SQL" dans le menu stats du BO permettant:
- [ ] afficher les tables disponibles existantes et les jointures possibles
- [ ] afficher les attributs des tables
- [ ] rédiger une requête "select" dans un champ prévu à cet effet
- [ ] cliquer un bouton pour exécuter la requête
- [ ] d'avoir un lien ou bouton pour télécharger le résultat au format texte CSV le contenu du select

Pour le devops, s'assurer que l'exécution de la requête ne charge pas le serveur dans sa fonction première.

**Comment by jpic** [comment]
> Pour le devops, s'assurer que l'exécution de la requête ne charge pas le serveur dans sa fonction première.

On peut les faire passer par un acces readonly ca ira ?

**Comment by fb86** [comment]
C'est quoi un acces readonly ?

**Comment by fb86** [comment]
jpic, 

je t'ai assigné toutes les dernières issues pour que tu puisses les valider et voir qui les traites entre toi et vindarel
