### ISSUE TITLE
[US] ETQ Admin, je peux connaître la date du dernier import par caisse

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#816]
Objectif: suivre les export/import des stats des caisses.

Pour clôturer l'issue, un item "Suivi des imports" dans le menu caisse>liste permet:

- [ ] de choisir une caisse dans une combo (caisse avec état 'activé')
- [ ] d'afficher la date du dernier import des stats (+ possibilité d'un tri par date)

**Comment by fb86** [comment]
@notmoebius ok pour moi . Je propose que la date de la dernière mise à jour soit indiqué dans la liste des caisses avec possibilité de trié par date.
>Accueil>Caisses>liste

**Comment by jpic** [comment]
J'ai du mal a bien cerner les intentions de l'implementation proposee ici:

- concernant le champs combo, quelle est l'intention de l'utilisateur que cette implementation essaye de resoudre ?
- est-ce-que vous voulez juste la datetime du dernier import ou est-ce-que vous voulez une sauvegarde de tous les imports ?

**Comment by fb86** [comment]
Hello, juste la datetime du dernier import' sur le même modèle de l ajout pour l economie et ou du nombre de modi par agent.... Il faut ajouter la date time de mise a jour sur la rurbique liste caisse. 




Télécharger Outlook pour Android







On Sat, Dec 29, 2018 at 4:13 PM +0100, "∞" <notifications@github.com> wrote:












J'ai du mal a bien cerner les intentions de l'implementation proposee ici:

concernant le champs combo, quelle est l'intention de l'utilisateur que cette implementation essaye de resoudre ?
est-ce-que vous voulez juste la datetime du dernier import ou est-ce-que vous voulez une sauvegarde de tous les imports ?
