### ISSUE TITLE
Valoriser les champs dans l'historique

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#82]
L'historique des modifications d'une demande est accessible sur le BO. En revanche, est-il possible d'afficher ou de valoriser les modifications effectuées ? 

Par exemple: si je modifie un montant, l'historique peut-il afficher l'ancienne valeur et la nouvelle afin de voir et de valoriser ce qui a changé ?

**Comment by jpic** [comment]
On en a jamais parlé.

**Comment by fjg** [comment]
Pas dans le périmètre actuel, on verra quand ca sera à prioriser

**Comment by jpic** [comment]
On a un modèle de données sans hack "rigolo" du coup n'importe quelle de ces apps devrait le faire:
https://djangopackages.org/grids/g/versioning/

Surtout django-reversion qui est le "bon citoyen historique" en la matière. Très rapide à installer, mais à tester en long en large et en travers (on sait qu'on peut compter sur Brice ;))

Cependant tant qu'on replace la page de modif en consultation seule (disons, jusqu'au jour ou un utilisateur fait une typo dans son NIR ;)), on en a ptet pas besoin.

Sauf si on veut garder une trace au moment des validations/rejets, mais c'est pas à l'ordre du jour n'est-ce-pas ?

Je propose de fermer l'issue en attendant que ce sujet ne revienne à l'ordre du jour.
