### ISSUE TITLE
modifier message d'erreur suite à mauvaise saisie du NIR

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#820]
Aujourd'hui, lorsqu'un assuré oublié un caractère de son numéro de sécurité sociale, le message suivant apparaît : "vous devez entrer une valeur comprise entre 1000000000000 et 99999999999999 ". selon la taille de l'écran le message n’apparaît pas toujours sous le champs Numéro de Sécurité sociale et disparaît dès qu'on fait remonter la page ce qui entraîne une confusion et des réclamations nous demandant quoi faire suite à ce message.

![erreur nir](https://user-images.githubusercontent.com/34480111/50448686-d8105d80-0922-11e9-8798-576c7eebdc14.png)

Pour cloturer l'issue :  modifier le message comme suit  : " Votre numéro de sécurité sociale est incorrect, Ce dernier doit comporter uniquement les 13 premiers chiffres "

**Comment by fb86** [comment]
Correctif fonctionne bien, 

juste revoir le libellé. le terme NIR ne parle pas à nos assurés. peux tu changer NIR par votre " le numéro de sécurité sociale doit comporté 13 caractères"

**Comment by jpic** [comment]
Est-ce-que ca ira ainsi ?

![2018-12-28-144551_562x180_scrot](https://user-images.githubusercontent.com/94636/50517235-aaa4ea80-0aaf-11e9-8e23-dec346f9e122.png)
