### ISSUE TITLE
Correctif base montant économie négative 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#822]
Aujourd'hui lorsqu'un assuré se déplace le même jour à 2 endroits différents (2 prescriptions de transports), il bénéficie de 2 remboursements dissocier. Lors de l'import des données de la base de remboursement de l'Assurance Maladie, la requête fusionne ces 2 remboursements et ne remonte qu'un seul montant.

Darnelle travaille à résoudre ce problème.

Pour clôturer l'issue, il faut pouvoir traiter manuellement les 4 cas identifiés et modifier dans la base les éléments suivants :

Pour la demande 201808310012, indiqué comme montant de Base de remboursement et de montant remboursé 17.10€ à la place de 319.50 €

Pour la demande 201808210006, ajouter un montant total des frais ATP égal à  259.89 €

Pour la demande 201807120016, indiqué comme montant de Base de remboursement et de montant remboursé 3.90 € à la place de 120.90 €

Pour la demande 201812120014, indiqué comme montant de Base de remboursement et de montant remboursé 4.50 € à la place de 28.50 €

**Comment by jpic** [comment]
Fait en base en reu avec Fred
