### ISSUE TITLE
ETQ Assuré je peux modifier ma saisie tant que celle ci est en état soumise

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#835]
Aujourd'hui , lorsqu'un assuré a soumis sa demande il ne peut plus la modifier.

Dans le mail de confirmation, il reçoit deux liens:
- [ ] un lien pour annuler sa demande : la demande change de statut dans MRS pour "ANNULEE"

L'issue est clôturée lorsque l'assuré peut annuler  sa demande à partir du mail de confirmation de saisie sous réserve que sa demande est encore à l'état soumis.

Dans les faits, mettre un lien sur le mail de confirmation permettant à minima de supprimer la demande soumise.

**Comment by vindarel** [comment]
notes de spéc technique:

- ajout d'un champ `link_edit` dans la table mrsrequest, de type uuid (str)
- à la validation de la demande, générer une chaine de caractères unique, la stocker dans `link_edit`
- nouvelles urls: `demande/<link>/modifier` et `demande/<link>/annuler`. Quand ce n'est pas possible, afficher un message expliquant pourquoi.

**Comment by jpic** [comment]
@vindarel est-il possible de trouver un nom de variable plus parlant que link_edit ? Peut etre "update_token" ?
Autre spec sur la page de modif/annulation: ne pas pouvoir si la demande n'est plus en status soumise.
Enfin, je pense qu'il faut commencer par deployer l'annulation avant de commencer le dev sur la modif, ca permettra de lever les potentiels loups et le developement de la modification sera plus challenging egalement cote technique.

**Comment by vindarel** [comment]
WIP: checks the url is correct, the request exists, the request can be cancelled (in "submitted" status), has a CANCEL button.

misses:

- review for best practices
- successful POST: user notification
- and oops, link into email^^

**Comment by jpic** [comment]
L'annulation est disponnible en staging.
![2019-01-29-055240_1905x859_scrot](https://user-images.githubusercontent.com/94636/51885147-9728c000-238a-11e9-8298-13e45a58e8ea.png)
![2019-01-29-055230_845x250_scrot](https://user-images.githubusercontent.com/94636/51885148-9728c000-238a-11e9-94b8-cf1858f88656.png)

Il reste un peu de fignole sur la partie test et design, mais pas grand chose avant d'etre prodable, merci d'avance pour vos retours demain aprem ;)

**Comment by notmoebius** [comment]
Hello, mon retour sur la page qui s'affiche pour annuler:
![image](https://user-images.githubusercontent.com/32330644/51915012-640e1d00-23da-11e9-969c-3c64a2d95f3e.png)

Sinon, c'est top !!

**Comment by notmoebius** [comment]
Si la demande a basculé dans le statut "en cours de liquidation", le message suivant apparait:
![image](https://user-images.githubusercontent.com/32330644/51916051-c7994a00-23dc-11e9-869c-cdca5a4fa01f.png)

Peut-on modifier la phrase pour l'assuré par:
"Nous ne pouvons pas annuler cette demande car elle est déjà en cours de traitement."

**Comment by jpic** [comment]
Et voici, mobile first design :joy:

![2019-01-29-160632_863x463_scrot](https://user-images.githubusercontent.com/94636/51917773-8efb6f80-23e0-11e9-820f-00a1e9a30483.png)

**Comment by jpic** [comment]
L'annulation est en prod. On attend de voir l'usage avant de reconsiderer la modification.

Appreciation personnelle: il faudrait que le formulaire de date propose une gestion un peu plus classique (ajouter, enlever un transport) pour que ce soit assez ergonnomique a utiliser.

**Comment by jpic** [comment]
Je me demande si on a pas fait fausse route en reflechissant a la modification de demande. Plutot, je me demande si l'objectif n'est pas de permettre a l'utilisateur de creer une nouvelle demande en se basant sur une demande precedente (pre-remplissage de champs). Cela serait peut etre plus compatible avec les contraintes legales.

**Comment by notmoebius** [comment]
Oui, tu as totalement raison. C'est à cela que l'on pensait car de toute façon l'assuré n'a pas de compte ou de dossier. Juste une demande à actualiser.

**Comment by jpic** [comment]
Annulation: en production
Modification: formalisation d'une nouvelle issue #940
