### ISSUE TITLE
ETQ admin, je peux cliquer le nb de signalement par caisse pour avoir les demandes

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#838]
Actuellement, on voie le nombre de signalements par caisse dans la page de liste de caisse, mais c'est un compteur simple (qui vient de #586)

Pour cloturer cette issue, il faudrait que l'admin puisse cliquer sur le nombre de signalements par caisse, pour afficher la liste des demandes avec signalement correspondant a cette caisse.

Le nombre de signalements devra donc apparaitre en colonne triable dans le tableau de la page de liste de demandes.

**Comment by jpic** [comment]
En staging dans ~15 minutes.
