### ISSUE TITLE
Embarquement: import de nouveaux liquidateurs

### ISSUE THREAD

**Issue by vindarel** [betagouv/mrs#839]
Pour faire démarrer de nouveaux liquidateurs, Johan fait remplir un fichier csv à chaque caisse et a besoin de l'importer dans MRS.

Les besoins sont:

- [] créer une page d'upload de csv: champ "fichier", bouton "importer".
- [] l'écran suivant affiche les données parsées, sans traitement d'erreur, et demande confirmation
- [] au POST, soumission des données parsées, affichage récapitulatif, et envoi de mail aux nouveaux utilisateurs, avec mot de passe généré.
  - [] revoir génération du mdp

![img_20190108_170557_8](https://user-images.githubusercontent.com/3721004/50842892-f5ecb200-1367-11e9-96c4-8085d4b8c4e4.jpg)

L'issue est terminée lorsque l'utilisateur reçoit par mail son login et mot de passe  (via mailjet).

**Comment by jpic** [comment]
Suite a un quick-call avec @Johan1983 
Pas d'import d'utilisateur a faire la semaine prochaine, par contre il y aura 4 fichiers (50 users) la semaine suivante.
