### ISSUE TITLE
Modification du montant ne désactive pas les PJ

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#84]
Comme montré sur le screenshot, lors de la création d'une demande, je peux saisir un montant > à 0€. Cette action fait apparaître le champ pour ajouter des PJ. J'ajoute donc une PJ.
Si je modifie le montant dans ce même formulaire et que je saisie un montant à 0€, le champ des PJ disparait. C'est le comportement attendu.

Dans l'interface admin sur le BO, je peux consulter la demande. Or celle-ci montre un montant à 0€ et une PJ justificative: normalement, ce n'est pas possible.

Proposition: si montant à 0€, ne pas stocker la PJ.
![modification de requete site d_administration de django - google chrome_2018-01-15_09-31-33](https://user-images.githubusercontent.com/32330644/34936354-5cb71cf6-f9e1-11e7-9bbe-65579a574cd3.png)

**Comment by jpic** [comment]
Lol, ok Brice, je vais le mettre dans l'admin aussi.

Un peu dommage de repousser une MEP pour des trucs comme ça mais bon.

**Comment by fjg** [comment]
On ne doit pas pouvoir modifier de demande dans le BO, unqiuement valider ou refuser

**Comment by jpic** [comment]
N'empêche que je kiffe le professionnalisme de Brice, ça c'est de l'issue ;)
