### ISSUE TITLE
Ouvrir la PMT d'une demande conflictuelle en popup

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#843]
Actuellement la page de detail de demande montre la liste des demandes qui ont une date de trajet conflictuel pour un utilisateur.

Pour cloturer cette issue, il faut qu'on puisse ouvrir la PMT de la demande conflictuelle dans une popup.

**Comment by vindarel** [comment]
On commence par une proposition au plus simple, comme discuté avec jpic:

> c'est l'utilisateur qui glissera la deuxieme fenetre sur son deuxieme ecran d'apres ce que j'ai compris

> au plus simple, pas besoin de passer plus de 30 minutes pour ajouter le lien

Ici un clic sur la PMT des demandes conflictuelles l'ouvre dans un nouvel onglet (et pas en pop-up, pour ne pas géner l'ouverture de la PMT de la demande).

pouvoir ouvrir les 2 PMT côte à côte demande plus de taf, est à priori possible (https://fengyuanchen.github.io/viewerjs/) sauf avec un pdf.

**Comment by jpic** [comment]
Comme dit par chat, on ne peut pas compter sur viewerjs qui ne supporte pas les PDF.

**Comment by vindarel** [comment]
see #863

**Comment by jpic** [comment]
A fermer ?
