### ISSUE TITLE
Exclure les demandes juste soumises de la recherche de conflits

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#844]
Actuellement, un utilisateur peut soumettre deux demandes avec la même date et l'admin verra dans chaque demande, l'autre demande soumise avec la meme date en conflit.

Pour cloturer cette issue, il faut que les demandes avec le statut soumise soient exclues de la recherche de conflits à l'instar des demandes rejettées.

**Comment by vindarel** [comment]
pour tester, j'ai créé 2 demandes du même jour, les 2 montraient un conflit. Avec ce patch, aucune ne montrait de conflit par défaut. En passant une demande en cours de validation, un conflit apparaît de nouveau sur la seconde demande.
