### ISSUE TITLE
CI: que ecole soit le reflet de la prod plutôt que staging

### ISSUE THREAD

**Issue by vindarel** [betagouv/mrs#845]

**Comment by jpic** [comment]
@fb86 @Johan1983 Je confirme qu'on a du revenir en arierre, c'est la source du deploiement prod effet de bord de la modification objet de cette issue. Nous avons une [demande de support au fabricant de la CI en attente de retour dans ce lien](https://gitlab.com/gitlab-org/gitlab-ce/issues/56186), on a peut etre des chances de pouvoir le patcher nous meme en looseder ("en avance de phase") sur notre serveur de CI.

**Comment by fb86** [comment]
Ok pas de soucis, on a le temps, cette issue a un facteur de gravité faible. 




Télécharger Outlook pour Android







On Mon, Jan 14, 2019 at 10:17 PM +0100, "∞" <notifications@github.com> wrote:












@fb86 @Johan1983 Je confirme qu'on a du revenir en arierre, c'est la source du deploiement prod effet de bord de la modification objet de cette issue. Nous avons une demande de support au fabricant de la CI en attente de retour dans ce lien, on a peut etre des chances de pouvoir le patcher nous meme en looseder ("en avance de phase") sur notre serveur de CI.

**Comment by jpic** [comment]
Ok, je la remet en preparation histoire de laisser une chance au fabricant de repondre a la demande de support.

**Comment by Johan1983** [comment]
avant de traiter cette issue > sortir la CI de Gitlab
