### ISSUE TITLE
Saisie Nir avec code alpha numérique

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#849]
Aujourd'hui les assurés ne peuvent saisir que les NIR numérique

l'issue est terminé lorsque un assuré peut saisir dans le formulaire un NIR alpha numérique.

**Comment by jpic** [comment]
En cours de lecture de [la page wikipedia du NIR](https://fr.wikipedia.org/wiki/Num%C3%A9ro_de_s%C3%A9curit%C3%A9_sociale_en_France) dans le but d'affiner la spec.

Mais il me semble en tout cas que la lettre ne peut etre en toute place.

La migration de data sera egalement un defi car actuellement c'est en Integer (nombre entier).

**Comment by jpic** [comment]
Un [autre pythoniste fut confronte au pb avant nous](https://gist.github.com/revolunet/1154911).

Je propose de creer une deuxieme issue pour egalement verifier la clef de NIR en fin, ca pourra tjs aider un utilisateur a identifier une faute de frappe ...

**Comment by jpic** [comment]
[Source wiki](https://fr.wikipedia.org/wiki/Num%C3%A9ro_de_s%C3%A9curit%C3%A9_sociale_en_France#Signification_des_chiffres_du_NIR), en position 6 et 7, on peut avoir "2A" et "2B" pour les Corses. Apres un coup de rasoir d'Ockham, il me semble que seules les lettres A et B sont acceptables seulement a la position 7 du NIR.

@Fred peux tu confirmer stp ?

**Comment by jpic** [comment]
Exemples en staging:

![2019-01-09-213029_363x101_scrot](https://user-images.githubusercontent.com/94636/50926824-42162000-1456-11e9-9575-68bc5de1552b.png)
![2019-01-09-213019_353x109_scrot](https://user-images.githubusercontent.com/94636/50926825-42162000-1456-11e9-99d3-77c78bf47f53.png)
![2019-01-09-212954_345x146_scrot](https://user-images.githubusercontent.com/94636/50926828-42aeb680-1456-11e9-9f06-7eb36dfcf850.png)
![2019-01-09-213013_364x140_scrot](https://user-images.githubusercontent.com/94636/50926826-42162000-1456-11e9-8547-73cafee29611.png)
![2019-01-09-213002_360x137_scrot](https://user-images.githubusercontent.com/94636/50926827-42aeb680-1456-11e9-84f0-88b411e7b321.png)
