### ISSUE TITLE
Cas de plantage serveur sur le formulaire de contact

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#852]
Actuellement en production nous avons un formulaire de contact tres simple sans traitement de cas d'erreur dans l'interface utilisateur.

Maintenant que le formulaire est plus complexe, il peut planter cote serveur, auquel cas cela n'est pas remonte a l'utilisateur dans l'interface.

Pour cloturer cette issue, demander a l'utilisateur de re-essayer plus tard en cas d'erreur serveur.

**Comment by vindarel** [comment]
\+1
