### ISSUE TITLE
Etude Stockage externe sur C14

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#862]
Actuellement, nous remplissons tranquillement le disque dur.

Pour cloturer cette issue, externaliser le storage sur [C14](https://www.online.net/en/c14), puis, ajouter un cache si necessaire.

**Comment by jpic** [comment]
Voici l'epique que j'identifie:

- [ ] Repliquer la prod en staging avec anonymisation
- [ ] Sortir les fichiers de la db
- [ ] Ajouter feature pour archiver
- [ ] Et desarchiver une demande
- [ ] Archiver automatiquement les demandes assez vielles (a definir)
- [ ] desarchiver automatiquement toutes les demandes d'un user qui cree une nouvelle demande pour faciliter les controles

En somme plutot couteux, je pense qu'il est trop tot car la on a que 21Gigs de documents. Pour moi ca vaudrait le coup de d'abord migrer sur un plus gros serveur.

![Uploading IMG_20190112_000454.jpg…]()

**Comment by jpic** [comment]
A terme une solution differente, pour l'instant plus gros serveur.

**Comment by fb86** [comment]
Pour l'instant : stop travaux sur le C 14 , la CNAM préconise une augmentation de la taille du serveur.

**Comment by jpic** [comment]
Egalement ma preco, 2 comms au dessus ;)
