### ISSUE TITLE
Admin: page de detail de personne

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#869]
Actuellement nous avons bien une base de donnees de personnes, mais qui n'est pas visible dans l'admin.

Cette issue est en preparation, specs a terminer en atelier.

Cette issue depend de la #868 (admin: page de liste de personnes), qui fournit le point d'entree vers la page de detail de personne, que cette issue doit decrire.

Pour cloturer cette issue, il faut une page permettant de consulter une personne:

- nom
- prenom
- nir
- email
- date de naissance
- nb signalements
- liste demandes

**Comment by fb86** [comment]
A retravailler ensemble mais je me demande au final a quoi va nous servir cette vue.

**Comment by jpic** [comment]
@fb86 tu as au moins les nombres de signalements culumes par personne
