### ISSUE TITLE
Correctif signalement assuré date de trajet(s) conflictuelles > a modifier en zone commentaires

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#875]
Depuis issue #838, on peut distinguer les signalements résolus et les confirmés.

Aucun signalement n’apparaît résolu alors que le compteur fonctionne ( tester en staging)

![signalement resolu a 0](https://user-images.githubusercontent.com/34480111/51261092-e72d7d00-19af-11e9-90af-532749ee6892.GIF)

sur la Haute Garonne, plus de 30 signalements ont entraîné un rejet du technicien lors du traitement.
le constat est donc que les assurés cliquent sur continuer sans jamais corriger leur saisie.

l'issue est terminée lorsqu'un assuré qui clic sur CONTINUER sans modifier les dates ou annuler sa demande voit apparaître un message lui demandant de justifier 2 trajets le même jour.

message : "Pour faciliter le traitement de votre dossier merci de nous préciser le motif justifiant 2 trajets le même jour : 2 rendez vous médicaux distincts, une entrée d’hospitalisation suivant une consultation, une sortie d'établissement précédent une consultation médicale,......."

mettre un champ texte.

Rendre impossible de valider la demande si le champs texte est vide.

le motif décrit par l'assuré devra être visible dans le signalement fait au liquidateur lors du signalement (ajouter une loupe).
![signalement liquidateur](https://user-images.githubusercontent.com/34480111/51262080-e7c71300-19b1-11e9-8aca-b34ebc8a13df.GIF)

**Comment by fb86** [comment]
@notmoebius  pour avis, notamment sur la formulation.

Dès que c'est ok pour toi on lance en prod.

**Comment by notmoebius** [comment]
D’un point de vue liquidateur, je suis ok mais comment justifier si plusieurs trajet au même jour ? Si 10 dates en signalements, l’assuré doit saisir un justificatif ou 10 soit 1 par trajet ?

**Comment by jpic** [comment]
Attention, on ne compte les "conflits resolus" en prod QUE depuis la MEP
d'hier ! D'ou les compteurs a 0. Si vous voulez, je remet l'autre compteur
aussi a 0.

**Comment by fb86** [comment]
Merci de la précision jamesi. On va effectivement tout remettre a 0 à ton retour de congés..... Histoire de vérifier avant tout changement. 




Télécharger Outlook pour Android







On Wed, Jan 16, 2019 at 8:44 PM +0100, "∞" <notifications@github.com> wrote:










Attention, on ne compte les "conflits resolus" en prod QUE depuis la MEP

d'hier ! D'ou les compteurs a 0. Si vous voulez, je remet l'autre compteur

aussi a 0.

**Comment by fb86** [comment]
Pour Brice, dans issue j ai mis une proposition de msg. Il s agit pas temps d avoir l explication que de declencher un acte volontaire en devant le justifier. J avais mis plusieurs exemple:


Plusieurs rendez vous medicaux le meme jour


Une entree d hospitalisation précédée d un rendez vous medical.






Mais bon si le compteur n etait pas alimenter ca repond à la question et on va pas bouger tant qu on est pas sur du manque d impact. 




Télécharger Outlook pour Android







On Wed, Jan 16, 2019 at 8:44 PM +0100, "∞" <notifications@github.com> wrote:










Attention, on ne compte les "conflits resolus" en prod QUE depuis la MEP

d'hier ! D'ou les compteurs a 0. Si vous voulez, je remet l'autre compteur

aussi a 0.

**Comment by jpic** [comment]
Effectivement, dans cette version l'incrementation des compteurs se fait lors de la confirmation de la demande.
Il faudrait ouvrir une API sur le serveur pour que le front puisse commencer a incrementer des compteurs sans soumission de formulaire.

**Comment by notmoebius** [comment]
Idée: proposer une zone de saisie pour informer du forçage avant de soumettre.

**Comment by fb86** [comment]
reecrire issue a partir de la dernier idée de brice
