### ISSUE TITLE
installer nouveau serveur

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#876]
Installer nouveau serveur dès que disponible

**Comment by jpic** [comment]
On a vraiment bcp plus d'espace, mais netdata remonte des erreurs lorsqu'on fait la backup sur le meme raid1 (read & write). On a un autre raid1 de dispo pour faire les backups. Il y aurait pas mal de travail sur les playbooks pour supporter des chemins variables, avec un peu de chance un bind-mount a l'ancienne dans la configuration des montages fera l'affaire sans toucher aux playbooks.

Netdata est en place, mais il manque les emails d'alerting.
Sentry a ete migre, mais l'instance de prod n'arrive pas a la joindre, il doit manquer une regle de firewall (la nouvelle version de docker a l'air un peu mieux faite en terme de firewall.

![2019-02-02-032216_1457x241_scrot](https://user-images.githubusercontent.com/94636/52158678-212e9c80-269b-11e9-9216-483577f0a3e9.png)
