### ISSUE TITLE
Email de confirmation d'annulation de demande

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#883]
Coucou !

Je suis en train de terminer l'annulation et je constate qu'on a pas eu la spec pour le mail de confirmation de l'annulation.

Est-ce-que tu peux me le ~~bichonner~~ rediger l'ajouter dans cette issue ?

D'avance merci :joy:

**Comment by fb86** [comment]
Proposition de mail de confirmation:

Bonjour, 

L annulation de votre demande **numero demande** a ete enregistré.

Cordialement 

L equipe MRS
