### ISSUE TITLE
Certaines PJ ne sont pas stockés

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#885]
Navigateur: chrome Version 72.0.3626.81 (Build officiel) (32 bits)

Lors de la saisie d'un formulaire certains fichiers ne sont pas mémorisés. Je joins le fichier qui pose problème par mail. L'upload se lance mais ne se termine pas, je ne peux pas l'effacer par exemple.

![image](https://user-images.githubusercontent.com/32330644/52114051-58556d00-260b-11e9-9db6-709a608ba97b.png)

Lors de la soumission, MRS indique que le fichier n'a pas pu être copié.

**Comment by jpic** [comment]
Ah non effectivement, j'arrive a reproduire avec ce fichier, merci !

**Comment by jpic** [comment]
Le fichier ne traverse pas le load balancer nginx qui repond avec une HTTP 413, request entity too large.

Le script d'upload traite ce cas comme un succes et ne presente pas de message d'erreur.

**Comment by jpic** [comment]
C'est resolu avec un paliatif en prod.

Il faut que je voie pk la config ne persistait pas.

**Comment by jpic** [comment]
La config s'est bien mise, pas de nouvel indice de mon cote, c'est peut etre en rapport avec la boulette de deploiement automatique que j'ai fais en installant le serveur dans la config avant de recevoir l'ip finale, si j'ai utilise une vielle version des playbooks peut etre ? Bref c'est ok pour moi sur la nouvelle prod, merci de reouvrir si on a du nouveau !
