### ISSUE TITLE
ETQ Assuré, je peux téléverser plusieurs pièces pour le champ PMT

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#900]
Permettre d'enregistrer plusieurs fichiers PDF ou images lors de l'import de la PMT.
En effet, certaines caisses demandent d'autre pièces comme le bulletin d'hospitalisation.

Fini qd : 

- [ ] l'assuré peut ajouter sa PMT et d'autres pièces. (A l'identique des PJ parking et péages.)
- [ ] l'admin peut consulter tous les documents PMT dans l'admin

**Comment by jpic** [comment]
Vous etes certains que vous ne voulez pas un nouveau champs pour un autre document non-pmt ?

**Comment by notmoebius** [comment]
C'est plus simple pour toi ? Je pensais reproduire le champ des PJ péages et parking.

**Comment by jpic** [comment]
Pas forcement plus simple en terme de developpement mais pour l'utilisateur il semble tres contre-intuitif de televerser des documents non-PMT dans un champs de PMT, j'ai peur que ce soit galere d'utilisation.
