### ISSUE TITLE
Recherche en page de liste: ajouter indicateur de chargement de page

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#908]
Actuellement, la page de liste se met a jour automatiquement lorsqu'on modifie un filtre de recherche.

Pour cloturer cette issue, afficher un indicateur de chargement de page lorsqu'on change un filtre de recherche dans l'admin.

**Comment by jpic** [comment]
Question posee en upstream: https://github.com/stimulusjs/stimulus/issues/243

**Comment by notmoebius** [comment]
Ne concerne que Fred. Abandon, abort, abort.
