### ISSUE TITLE
ETQ Assuré, je peux saisir mon num de PEL

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#912]
Revoir le formulaire pour ajouter un bouton radio:
o PMT (Prescription papier)
o PEL (Prescription électronique)

Mettre par défaut la PMT comme choix par défaut, cela ne change pas les habitudes.

Fini quand l'assuré peut par bouton radio : 
- téléverser une PMT papier (numérisé ou prise de photo)
- saisir le n° PEL

**Comment by jpic** [comment]
![2019-03-19-151529_1048x451_scrot](https://user-images.githubusercontent.com/94636/54613096-6e53ab80-4a5a-11e9-87aa-3accbe0b5aa4.png)
![2019-03-19-151508_1061x412_scrot](https://user-images.githubusercontent.com/94636/54613097-6e53ab80-4a5a-11e9-9dde-f5a751fcb751.png)

**Comment by jpic** [comment]
Besoin de quelques specs pour cloturer si vous le voulez bien:

Qu'est-ce-qu'on met comme texte dans le champs d'aide en bas ?

Nous avons donc un patch qui fonctionne en runtime (mais pete les tests ^^):

![2019-03-22-034710_1170x452_scrot](https://user-images.githubusercontent.com/94636/54797755-c60a3680-4c55-11e9-840e-62e9a372d3d1.png)

**Comment by jpic** [comment]
Egalement, merci de formaliser les regles de validation du champs PEL.

**Comment by fb86** [comment]
Le champs pour la pel est en 14 caracteres alpha numerique.

Sur l exemplaire patient, il est indiqué prescription medicale electronique de transport. Il faudrait plutôt indique n° de prescription médicale electronique.

Le texte d aide pourrait etre : " le numero de votre prescription médicale electronique est indiqué sur l exemplaire patient remis par votee medecin".

L ideal serait de pouvoir afficher l exemple  factice suivant que j ajoute plus haut.
