### ISSUE TITLE
ETQ Liquidateur, je peux consulter une PEL

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#913]
Lors de la consultation d'une demande, le liquidateur peut consulter une PEL grâce à TROC.

Un clic lance l'application métier TROC avec les bons paramètres. Le liquidateur peut valider en cliquant sur le bouton rechercher pour consulter la PEL.

![image](https://user-images.githubusercontent.com/323301620931555597162093155559716209315555971620931555597644/53019672-9220d300-3455-11e9-98a7-c30a30455608.png)

http://troc.cnamts.fr:20022/IhmBQ/rechercherPrescription.go?action=rechercher&menuCourant=rechercherPrescription&beneficiairePO.nir=...&prescriptionPO.numPrescription=FR...&prescriptionPO.statut=Prescrit-VP-ATP

**Comment by jpic** [comment]
Question: est-ce-que vous comptez le prefixe "FR" comme faisant partie des 14 caracteres du num de PEL ?

Merci :heart:

**Comment by jpic** [comment]
![2019-03-26-211310_536x316_scrot](https://user-images.githubusercontent.com/94636/55030422-9d46c000-500c-11e9-9804-a42539097a12.png)
