### ISSUE TITLE
Bug écart entre nb de demandes front et back stats

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#916]
Constat: le nb de demandes validées et rejetées et différent entre le FO et le BO.
Revoir règle de calcul : why ?

**Comment by jpic** [comment]
Un recalcul est en cours.

**Comment by jpic** [comment]
Le recalcul n'a rien donné.

Mais ceci m'a mit la puce à l'oreille:

![2019-03-05-160429_347x342_scrot](https://user-images.githubusercontent.com/94636/53814942-eef5b080-3f60-11e9-92df-f05bbe9505ad.png)

Elementaire mon cher watson, la stat est en triple en db:

```
>>> Stat.objects.filter(date='2019-01-24', caisse=None, institution=None)
<QuerySet [<Stat: Stat for 2019-01-24, caisse: None, etab: None>, <Stat: Stat for 2019-01-24, caisse: None, etab: None>, <Stat: Stat for 2019-01-24, caisse: None, etab: None>]>
```

**Comment by jpic** [comment]
Surement que, la fonction spooler qui fait le "get or create" s'est executée deux fois en meme temps.

Normalement, ça ne devait pas arriver, [ce code doit faire une contrainte en db](https://github.com/betagouv/mrs/blob/master/src/mrsstat/models.py#L241-L244).

La solution la plus simple consiste à paramêtrer le spooler "stat" pour ne traiter qu'un job a la fois, eliminant la race condition.

**Comment by jpic** [comment]
J'ai le patch préventif en cours de merge.

Une fois ce patch en production, il faudra effacer les stats dupliquées de la DB.

Voir, toutes les effacer et les regenerer.

**Comment by jpic** [comment]
Pour cloturer l'issue:

- faire un drop de toutes les stats,
- lancer un recalcul

Dans la nuit

**Comment by jpic** [comment]
On a un bugfix preventif en prod et un recalcul a ete fait.
L'ecart s'est largement amoindri.
On attend quelques semaines voir si le bugfix preventif est bien effectif avant de continuer des fixes.
