### ISSUE TITLE
[Bug] Pas de lien dans le mail de rejet

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#933]
En staging, j'ai rejeté des demandes mais le lien de l'issue [904](https://github.com/betagouv/mrs/issues/904) n'apparait pas dans mailcatcher.

Le lien à insérer : "Renouveler votre demande en cliquant sur le lien: https://www.mrs.beta.gouv.fr/demande"

**Comment by jpic** [comment]
Merci effectivement je l'ai mis dans le mail d'annulation a la place

**Comment by jpic** [comment]
Follow-up: #940
