### ISSUE TITLE
Indicateur de délais de traitement sur la page de liste de demandes

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#936]
Pour cloturer cette issue:

- [x] retirer la colonne Etablissement de la liste de demandes
- [x] ajouter une colonne "délais de traitement", correspondant au délais de traitement de la demande
- [x] renommer le filtre "Institution" en "Etablissement" sur la page de detail liste de demandes

**Comment by jpic** [comment]
![2019-03-12-200348_1483x482_scrot](https://user-images.githubusercontent.com/94636/54228456-7bc0e100-4502-11e9-987f-d830c9d984c7.png)

**Comment by notmoebius** [comment]
Juste, je remplacerai paiement par traitement si c'est le délai de traitement.
