### ISSUE TITLE
ETQ liquidateur je peux mettre en suspend le traitement d'un dossier sans impacter le délai de traitement.

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#937]
- [ ] Créer une nouvelle variable "Dossier en cours d'étude", peut être attribuee à une demande "soumise" ou "en cours de liquidation".
- [ ] historisation avec un champs texte "Merci d'indiquer le motif de mise en suspend du dossier" obligatoire pour justifier de la mise en suspens
- [ ] Les demandes qui ont eu une etude sont exclues du calcul de delai de traitement moyen pour les stats

**Comment by jpic** [comment]
@fb86 il semblerait que pour l'instant on calcule le délais moyen de traitement uniquement sur les demandes validées, après validation. Par conséquent, les demandes actuellement suspendues qui n'ont pas encore été validée n'affecteraient pas le delais moyen de traitement.

**Comment by fb86** [comment]
Yes, donc no soucis pour l instant




Télécharger Outlook pour Android







On Wed, Mar 6, 2019 at 4:34 PM +0100, "∞" <notifications@github.com> wrote:












@fb86 il semblerait que pour l'instant on calcule le délais moyen de traitement uniquement sur les demandes validées, après validation. Par conséquent, les demandes actuellement suspendues qui n'ont pas encore été validée n'affecteraient pas le delais moyen de traitement.

**Comment by jpic** [comment]
On a un bugfix preventif en prod et un recalcul a ete fait.
L'ecart s'est largement amoindri.
On attend quelques semaines voir si le bugfix preventif est bien effectif avant de continuer des fixes.
