### ISSUE TITLE
ETQ caisse je reçois mensuellement les stats des lignes vide de plus de 30 jours

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#939]
Aujourd'hui lors de l'import des données Erasme, certaines lignes restent vides.

L'issue est terminée lorsque les CPAM reçoivent sur leur mail tous les 1ers jours du mois, la liste (format CSV) des demandes ( Demandes de plus de 30 jours ayant un statut validé ) ayant des lignes vides.

exemple de mail :

Bonjour,

Veuillez trouver ci joint l'extraction mensuelle des demandes n'ayant pas fait l'objet d'une remonté stat.

Pour rappel, lors d’une demande d’un assuré via MRS, il y a parfois des erreurs de saisie du NIR, de  la date de naissance ou de la date du trajet. Les techniciens font la plupart du temps la correction sous Progrès au regard de la BDO mais oublient parfois de modifier les données sous MRS. A cause du décalage entre la saisie MRS et la saisie Progrès , certaines données ne remontent pas. 

Afin de qualifier ces données et avoir vos métriques à jour, nous vous invitons à corriger les données soit directement  sur les demandes MRS lorsqu'il s'agit d'erreur de NIR ou de dates de naissance ou en nous renvoyant le fichier ci joint complété. 

Bien cordialement,

L'Equipe MRS

**Comment by jpic** [comment]
Quel objet pour le mail ?

**Comment by fb86** [comment]
Titre: suivi mensuel des erreurs de saisies. 




Télécharger Outlook pour Android







On Wed, Apr 3, 2019 at 9:49 AM +0200, "∞" <notifications@github.com> wrote:












Quel objet pour le mail ?

**Comment by fb86** [comment]
peut on refaire un test en staging ?

**Comment by notmoebius** [comment]
Ne fonctionne toujours pas:
Doit sortir les dossiers non qualifiés.
