### ISSUE TITLE
ETQ ADMIN je peux consulter le suivi des signalements

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#942]
ETQ administrateur je peux consulter le suivi des signalements .

Actuellement le suivi des signalements est indiqué dans caisses>liste
![capture revision champs signalements](https://user-images.githubusercontent.com/34480111/53814520-0d0ee100-3f60-11e9-87ae-47cb710f719d.GIF)

l'issue est terminé lorsque les champs signalements confirmés et signalements résolus sont remplacés par les champs
 - nombre de page confirmation (sous le libelle "signalements assurés ")
 - nombre de demandes soumises avec conflit non résolue (sous le libellé  " signalements liquidateurs")
 - nombre de "signalements traités" . (Signalements traités = "signalements assurés" - "signalements liquidateur")

**Comment by jpic** [comment]
A noter un certain nombre d'etapes preliminaires:

- compter le nombre de "signalements traités"
- stocker ce chiffres, quelque part, on ne sait pas ou, mais il le faut bien
- l'afficher avec les deux autres

**Comment by jpic** [comment]
@fb86 il faudra noter qu'au moment ou l'utilisateur voie la page de confirmation, le compteur de signalements assuré ET de signalements traités augmente de 1.

SI l'utilisateur confirme sa demande avec les conflits, le nombre de signalements traités redescendra a 0, du fait de l'augmentation du compteur de nombre de signalements confirmés au moment de la sauvegarde.

Est-ce-que ce point est clair ? Voila il ne faudra donc pas s'etonner de voir le nombre de signalement traité monter et descendre au cours de la journée: le chiffre n'est final que le lendemain.

**Comment by fb86** [comment]
Hello,




Alors non pas claire a la 1er lecture mais car je sors d une tres grosse journée et d un sprint pour prendre mon train. Je relis a tete reposer. Et je te dis.... 




Télécharger Outlook pour Android







On Wed, Mar 13, 2019 at 6:10 PM +0100, "∞" <notifications@github.com> wrote:












@fb86 il faudra noter qu'au moment ou l'utilisateur voie la page de confirmation, le compteur de signalements assuré ET de signalements traités augmente de 1.



SI l'utilisateur confirme sa demande avec les conflits, le nombre de signalements traités redescendra a 0, du fait de l'augmentation du compteur de nombre de signalements confirmés au moment de la sauvegarde.



Est-ce-que ce point est clair ? Voila il ne faudra donc pas s'etonner de voir le nombre de signalement traité monter et descendre au cours de la journée: le chiffre n'est final que le lendemain.

**Comment by jpic** [comment]
![2019-03-13-182845_459x330_scrot](https://user-images.githubusercontent.com/94636/54301027-6c9f6900-45be-11e9-85b5-46e55193ee44.png)
