### ISSUE TITLE
Champs à remettre quand on clique sur "Nouveau"

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#96]
Quand on soumet un formulaire, et qu'on clique sur "Cliquez ici pour soumettre une nouvelle demande": cela charge un nouveau formulaire vide.

Question pour @notmoebius : faut-il recopier des champs dans le nouveau formulaire histoire de pas repartir à 0 ou pas ?

**Comment by notmoebius** [comment]
Effectivement, on peut supposer que l'assuré est le même:
- reprendre n° de sécurité sociale et email

Le bénéficiaire aussi (personne transportée):
- reprendre nom, prénom et date de naissance.

Nice feature !

**Comment by jpic** [comment]
En fait c'est un peu plus compliqué que je pensais, et maintenant qu'on a confirmé qu'on envoie l'itératif en prod ça n'a peut-être plus trop de valeur ?
