### ISSUE TITLE
Coquille affichage libellé signalement

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#961]
Il semble y  avoir une erreur dans l'affichage du libellé des signalements ( accueil>caisses>liste).
![erreur affichage signalement](https://user-images.githubusercontent.com/34480111/54524997-8b617f00-4973-11e9-8085-bdfc62fdf46b.GIF)

il est probable qu'il y ai eu une inversion entre les libellés signalement liquidateurs et signalements assurés.
les signalements assurés étant naturellement plus important que ceux liquidateurs.

**Comment by jpic** [comment]
Effectivement, tu peux meme le corriger toi meme j'en suis certain [par ici](https://github.com/betagouv/mrs/blob/master/src/caisse/crudlfap.py#L56-L57) si tu acceptes le challenge :joy:

**Comment by fb86** [comment]
Je relève le defis demain matin ! J ai pas d ordi ce soir.....




Télécharger Outlook pour Android







On Mon, Mar 18, 2019 at 11:52 AM +0100, "∞" <notifications@github.com> wrote:












Effectivement, tu peux meme le corriger toi meme j'en suis certain par ici si tu acceptes le challenge 😂
