### ISSUE TITLE
ETQ assuré, je peux voir une info sur PMT ou PEL

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#963]
en lien issue #912 , il faut ajouter une info-bulle pour : 
- pour la PMT : expliquer à quoi ressemble une PMT avec une image fac-similé
- pour la PEL : afficher un facsimilé d'une PEL

En cliquant sur "i", une popup affiche l'affiche facsimilé soit de la PMT, soit PEL.

**Comment by fb86** [comment]
issue cloturer au profit #987
