### ISSUE TITLE
ETQ Superviseur, suivre les motifs de rejets de mes caisses

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#964]
Un Superviseur doit pouvoir consulter la liste des motifs de rejets, voir leur nombre d'utilisations sur les caisses auxquelles ils ont accès, filtrer par période et liquidateurs des caisses accessibles.

**Comment by fb86** [comment]
aujourd'hui en tant que superviseur je peux selectionner l'ensemble des profil de ma caisse.

correction terminé lorsque en tant que superviseur, lorsque je filtre avec le nom d'un agent, je ne vois que les profils UPN de ma caisse.

**Comment by fb86** [comment]
ok modif fonctionne
