### ISSUE TITLE
ETQ Liquidateur, suivre mes motifs de rejets par nombre et période

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#965]
Actuellement, liquidateur ne peut pas consulter ses propres statistiques.

Pour cloturer cette issue, permettre au liquidateur de voir ses motifs de rejets par nombre d'utilisation et par période.

Dépend de #962

**Comment by fb86** [comment]
ETQ techniciens je peux voir combien de fois j'ai utilisé le motif de rejet ou contact ( = utilisations).

A quoi correspond le counter ?
nombre de fois ou le rejet à été utilisé dans la CPAM ou nombre de fois où il a été utilisé sur l'ensemble des caisses. Je pense que c'est la proposition 1 mais à confirmer

**Comment by jpic** [comment]
C'est l'ancien compteur denormalisé que je voulais garder dans un premier temps a titre comparatif mais finnalement je vais m'en passer. C'etait juste un moyen d'evaluer la qualité de la migration.

**Comment by fb86** [comment]
tout comme il faut
:+1:
