### ISSUE TITLE
Ajout d'un item dans la FAQ

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#966]
Ajouter un item dans la page FAQ:

Texte:
=begin
« Qu'est-ce qu'une PEL ? »
Une PEL est une Prescription Electronique en Ligne est une version dématérialisée de la prescription médicale de transport.
=end

**Comment by jpic** [comment]
Le texte dit ce que c'est, mais ne donne pas d'instructions a l'utilisateur: est-ce-que j'ai une PEL ou une PMT ? Comment je fais pour savoir comment remplir le formulaire ?

**Comment by fb86** [comment]
Je te prépare ca en fin de journée. 




Format du numero de pmt 


Texte expliquant où trouver le numero de pmt. + exemple de pel




Télécharger Outlook pour Android







On Sat, Mar 23, 2019 at 3:02 PM +0100, "∞" <notifications@github.com> wrote:












Le texte dit ce que c'est, mais ne donne pas d'instructions a l'utilisateur: est-ce-que j'ai une PEL ou une PMT ? Comment je fais pour savoir comment remplir le formulaire ?

**Comment by fb86** [comment]
Bonsoir, 




J ai repondu sur issue. 




Ci joint la pmet. 




Bonne soirée 




Télécharger Outlook pour Android







On Sat, Mar 23, 2019 at 6:28 PM +0100, "frederic.boulay@beta.gouv.fr" <frederic.boulay@beta.gouv.fr> wrote:










Je te prépare ca en fin de journée. 




Format du numero de pmt 


Texte expliquant où trouver le numero de pmt. + exemple de pel




Télécharger Outlook pour Android







On Sat, Mar 23, 2019 at 3:02 PM +0100, "∞" <notifications@github.com> wrote:












Le texte dit ce que c'est, mais ne donne pas d'instructions a l'utilisateur: est-ce-que j'ai une PEL ou une PMT ? Comment je fais pour savoir comment remplir le formulaire ?

**Comment by fb86** [comment]
Le format est en 14 caracteres alpha numerique.

Il vaut mieux parler de prescritpion medicale electronique de transport. Une prescritpion electronique de transport est similaire a la prescritpion papier. Votre medecin vous remettra un exemplaire papier

**Comment by fb86** [comment]
issue cloturé , elements repris dans #987
