### ISSUE TITLE
ETQ Admin, suivre les motifs de rejets par nombre, caisse et période

### ISSUE THREAD

**Issue by jpic** [betagouv/mrs#967]
Actuellement, l'admin ne peut consulter que le compteur dénormalisé d'utilisation de templates de mails.

Pour cloturer cette issue, l'Admin doit pouvoir consulter les nombres d'utilisation des motifs de rejets, et filtrer par période et caisses.

A noter que l'Admin aura les droits d'utiliser les features de #964 qui complêtent.

Depend de #962

**Comment by fb86** [comment]
aujourd'hui ETQ admin je peux selectionner l'ensemble des caisses et techniciens (tout profil confondus)

correction terminé lorsque ETQ admin je en puisse filtrer que par les caisses actives et uniquement sur les profils UPN

**Comment by fb86** [comment]
Aujourd'hui les filtres s'appliquent sur le compteur "utilisations"

peut on les faire appliquer sur "counter"?

**Comment by jpic** [comment]
Le counter c'est l'ancien compteur denormalisé, en tant que tel il n'est pas filtrable. Je voudrais attendre de voir ce que la migration donne en production avant de definitivement le retirer, a des fins comparatives.

Je m'occuppe du reste des modifs.

**Comment by fb86** [comment]
A revoir mais on pourrait remplacer counter par total des utilisation sur le dept.... A réfléchir 




Télécharger Outlook pour Android







On Wed, Apr 10, 2019 at 6:25 PM +0200, "∞" <notifications@github.com> wrote:












Closed #967 via 102e51a.

**Comment by fb86** [comment]
ok pour moi, modification fonctionne en staging
