### ISSUE TITLE
Revoir la validation des données 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#97]
Today, il est possible de revenir sur une demande qui a déjà été validé et de la traiter une deuxième fois. Ainsi on peut valider une demande, puis reprendre cette même demande et la rejeter. Il faudrait bloquer le statut de la demande une fois qu'elle a été traité.

**Comment by notmoebius** [comment]
Effectivement, c'est le comportement pour l'instant acter sur les demandes dans le BO.
Il faudrait bloquer cela car le contenu des mails ont évolué pour proposer de refaire une demande en ligne avec les bons documents et les rendre lisibles.
