### ISSUE TITLE
Revoir la complexité CAPTCHA

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#971]
Le captcha actuel n'est pas assez complexe.

Fini quand le nb de spam est proche de 0.

**Comment by jpic** [comment]
On va se tester ca : https://github.com/mbi/django-simple-captcha

**Comment by jpic** [comment]
C'est une captcha sympa, bien reglable avec le support audio moyennant quelques nouveaux packages dans le Dockerfile.

Pour l'instant j'ai juste la base qui marche, j'ai testé en display inline et j'ai obtennu un bon positionnement aligné en vertical, mais il faut que je le passe en flex pour pouvoir gerer une belle disposition des colonnes.

![2019-03-23-172555_1197x688_scrot](https://user-images.githubusercontent.com/94636/54868861-7466c680-4d91-11e9-8733-16ef0011a72e.png)

**Comment by jpic** [comment]
Question positionnement on est bon. Reste a ajouter le clic pour refresh ainsi que l'audio si possible.

![2019-03-23-190833_1091x455_scrot](https://user-images.githubusercontent.com/94636/54869927-a41ccb00-4d9f-11e9-8ffc-175696942642.png)

**Comment by jpic** [comment]
J'ai bien l'audio qui marche, mais c'est en anglais donc je le vire.

On pourra ouvrir une nouvelle carte si on veut l'audio en francais, mais ca risque de prendre [une bonne journee de plus](https://boredomed.wordpress.com/2019/03/07/festvox-to-flite-tts-conversion/).

**Comment by jpic** [comment]
La captcha est en staging et un audit secu est commandé. Mais rien n'empeche de deployer avant, a moins que ca ne soit pire que ce qu'on a deja.

D'avance merci pour votre feedback en staging

**Comment by jpic** [comment]
![2019-03-27-022649_1481x442_scrot](https://user-images.githubusercontent.com/94636/55043869-5b337380-5038-11e9-8587-a7c01d81973b.png)
![2019-03-27-022641_427x735_scrot](https://user-images.githubusercontent.com/94636/55043870-5c64a080-5038-11e9-8c8a-2598bbfb0dd5.png)

**Comment by jpic** [comment]
https://www.lancaster.ac.uk/news/new-attack-could-make-website-security-captchas-obsolete
https://www.lancaster.ac.uk/staff/wangz3/publications/ccs18.pdf
