### ISSUE TITLE
Impossible envoyer mail à contact

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#98]
Pb pour remplir questionnaire de contact.
Lorsqu'on veut rentrer son adresse mail dans la partie contact, sa renvoi directement sur le questionnaire de saisie (rubrique mail du questionnaire de saisie)

**Comment by notmoebius** [comment]
@fb86 Je viens d'essayer avec le PMF, c'est ok pour moi. En revanche, sous mobile et Android, le formulaire n'envoi pas de message au clic sur Envoyer. Il reste figer.

**Comment by jpic** [comment]
Sous endroit ça marche pour moi, pouvez-vous re-essayer et confirmer ?

Pour info, c'est le meme script d'envoie de formulaire que pour l'autre formulaire, donc a priori, pas de raison que lun fonctionne et pas l'autre.

Merci

**Comment by notmoebius** [comment]
Je te confirme que cela fonctionne. le formulaire est envoyé !

**Comment by fb86** [comment]
OK pour moi également.

**Comment by jpic** [comment]
Fantastique :)
