### ISSUE TITLE
Formulaire de demande boucle

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#982]
Lors de la saisie d'un demande suite à l'ajout de l'option PEL/PMT papier, le formulaire boucle en cliquant sur "Soumettre".

Pour reproduire:
- faire une demande complète avec PMT sans la soumettre
- revenir au niveau du choix PMT/PEL et cliquer sur PEL
- cliquer de nouveau sur PMT: la PJ est bien présente
- Tenter de soumettre la demande, le formulaire boucle sans indiquer d'erreur.

**Comment by jpic** [comment]
Pour moi le formulaire ne boucle pas, mais on se retrouve bien avec PMT et PEL en admin.

Peux-tu m'en dire plus sur la partie "boucle" stp ?

Merci
