### ISSUE TITLE
ETQ assuré je peux voir ce qu'est une PEL

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#987]
Aujourd’hui, en tant qu'assuré je peux saisir mon numéro de PEL

Sur l exemplaire patient, il est indiqué prescription medicale electronique de transport. Il faudrait plutôt indique n° de prescription médicale électronique et enrichir la FAQ.

l'issue est terminée lorsque 

- on remplace le terme PEL par PMET (Prescription Médicale Electronique de Transport)
- qu'on ajoute le texte suivant sous numéro de PMET :" où trouver  votre numero de PMET ?"
-  on réalise un lien qui renvoi sur la question de la FAQ " Qu'est ce qu'une prescription Médicale de transport ? (voir ci après). 

Dans la FAQ, 
- je corrige le paragraphe ci dessous en remplacant  le terme "la prescription médicale de transport" par " la prescription médicale de transport ou le numéro de la prescription médicale électronique de transport,"
![correction faq](https://user-images.githubusercontent.com/34480111/55895616-c8a8dd80-5bbc-11e9-8a0d-40794adc3d47.GIF)

- incruster un nouveau paragraphe après me paragraphes "quels justificatifs dois je fournir pour être rem..."  
titre : Qu'est ce qu'une  Prescription Médicale de transport ? (en rouge)
corps de texte : Le médecin détermine, dans la prescription médicale de transport, le mode de transport le mieux adapté à votre l'état de santé. Il peut alors compléter  le formulaire  sous une forme papier, il s'agit alors d'une « Prescription médicale de transport » (n° S3138), ou  réaliser une prescription médicale électronique de transport grâce au service de prescription électronique. Dans ce second cas, vous n'avez pas besoins de transmettre l'exemplaire papier de la prescription électronique de transport remit par vos médecin. Il suffit d'indique le numéro de prescription électronique que vous trouverez en haut de l'exemplaire papier (voir ci dessous). 
illustration : [SPE exemplaire patient (3).pdf](https://github.com/betagouv/mrs/files/3043516/SPE.exemplaire.patient.3.pdf)

**Comment by fb86** [comment]
@jpic si elle est assez claire pour toi, on la passe en to do.

**Comment by jpic** [comment]
La FAQ « Quel document dois-je fournir ? » a aussi besoin de mise a jour ?

**Comment by fb86** [comment]
Yes, je regarde cela demain matin.




Télécharger Outlook pour Android







On Fri, Apr 5, 2019 at 6:52 PM +0200, "∞" <notifications@github.com> wrote:












La FAQ « Quel document dois-je fournir ? » a aussi besoin de mise a jour ?
