### ISSUE TITLE
Disposer d'une jauge de volume

### ISSUE THREAD

**Issue by notmoebius** [betagouv/mrs#99]
Dans le BO, est-il possible d'avoir un indicateur du volume de fichiers PJ et PMT ?

N'est-il pas nécessaire de faire de la purge ou archivage et de suivre l'évolution des PJ transmises ?
Cela éviterait le mail bombing ?

**Comment by jpic** [comment]
Normalement il y a les jauges sur les outils de monitoring.

**Comment by notmoebius** [comment]
Ok, je clôture alors.
