### ISSUE TITLE
ETQ assuré je peux remplir le questionnaire quali primo utilisateur

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#990]
Nous avons réalisé un questionnaire à l'attention des primo utilisateurs de MRS sur limesurvey.

Les primo utilisateurs sont les assurés faisant leur 1ere demande sur MRS pour eux même ou un de leur enfant , cela veut dire qu'ils sont identifier uniquement par leur NIR. (=1er demande du NIR)

L'issue est terminée lorsque
-  Lorsque l'assuré valide sa demande, sur la page de confirmation de sa demande (sur le site MRS). Le message suivant apparaît :
"Nous vous remercions de l'utilisation de MRS. Afin d'améliorer la qualité de notre service et vous garantir un traitement dans les meilleurs, nous vous proposons de répondre à quelques questions, cela nous vous prendra que 3 minutes maximum. Merci par avance ! L'équipe MRS

- Ajout d'un bouton call to action en dessous de ce rédac.
- Le bouton se nomme "JE REMPLIS LE QUESTIONNAIRE"
- Le bouton renvoie vers le questionnaire LimeSurvey hébergé en externe sur cpam31
- Le lien LimeSurevey sera fourni dans un second temps (réalisation en cours du sondage).

**Comment by fb86** [comment]
@Johan1983 @fjg , merci de votre relecture et commentaire avant transmission à jamesi

**Comment by Johan1983** [comment]
Ajout de commentaires :
Lorsque l'assuré valide sa demande, sur la page de confirmation de sa demande (sur le site MRS). Le message suivant apparait :
"Nous vous remercions de l'utilisation de MRS. Afin d'améliorer la qualité de notre service et vous garantir un traitement dans les meilleurs, nous vous proposons de répondre à quelques questions, cela nous vous prendra que 3 minutes maximum. Merci par avance ! L'équipe MRS

- Ajout d'un bouton call to action en dessous de ce rédac.
- Le bouton se nomme "JE REMPLIS LE QUESTIONNAIRE"
- Le bouton renvoie vers le questionnaire LimeSurvey hébergé en externe sur cpam31
- Le lien LimeSurevey sera fourni dans un second temps (réalisation en cours du sondage).

**Comment by fjg** [comment]
Nickel, j'ajouterai le lien limesurvey lorsqu'on aura validé le questionnaire.

**Comment by fjg** [comment]
Voici l'url vers lesquels les rediriger : https://www.sondage.cpam31.fr/index.php/725937?newtest=Y&lang=fr

**Comment by jpic** [comment]
@fb86 est-ce-qu'on a le go finnalement ?

Merci ;)

**Comment by fb86** [comment]
Non pas go, :0(




Télécharger Outlook pour Android







On Thu, Apr 18, 2019 at 11:43 AM +0200, "∞" <notifications@github.com> wrote:












@fb86 est-ce-qu'on a le go finnalement ?


Merci ;)

**Comment by Johan1983** [comment]
@jpic 
le sondage sera effectué sur la plateforme Vocaza (analyse par la cnam).
Tu trouveras ci dessous le lien vers lequel diriger nos primo utilisateurs :
https://saas2.vocaza.net/cgi-bin/HE/SF?P=73z7z4z-1z-1z53DA1E7B4F

tu as le rédactionnel à afficher dans le post du 11 avril

**Comment by Johan1983** [comment]
la nouvelle url a integrer est la suivante : https://saas2.vocaza.net/cgi-bin/HE/SF?P=73z12z8z-1z-1zFBD49B6498
