### ISSUE TITLE
ETQ liquidateur je peux visualise les montants remboursés en VP et ATP

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#996]
Aujourd'hui, lorsqu'un assuré demande dans une meme demande un remboursement de VP et ATP, le montant total de remboursement, ci dessous en rouge, correspond à la somme du montant du au VP et au ATP
![vp atp](https://user-images.githubusercontent.com/34480111/56205331-bd850000-6049-11e9-8e6d-07976426def9.GIF)

l'issue est terminée lorsque le recap VP est harmoniser sur celui ATP, 

a savoir affichée unique les points suivants :

VP
Montant total de la dépense VP (en gras).....€
distance parcourus ...................................................Km
total des frais VP .....................................................€
cout théorique du trajet en taxi..........................€
justificatifs attachés

**Comment by fb86** [comment]
Oui c est bien cela. Il faut conserver le champs actuel dans la base et ajouter 2 nouveaux champs dans la base.

**Comment by jpic** [comment]
Bonjour,

Dans "Montant total de la dépense VP" faut il afficher juste la somme des frais ou la somme des frais plus le remboursement des kilometres ?

Merci

**Comment by fb86** [comment]
"Le Montant total de la dépense VP" correspond à la somme des frais plus le remboursement des kilométres.

**Comment by fb86** [comment]
En staging, le montant total de la dépense VP correspond uniquement au frais de VP alors qu'il devrait correspondre à :

montant total des frais de VP + nbr de km déclarée x 0,3€

**Comment by fb86** [comment]
@fb86 refaire un test avec cpam n'incluant pas les frais de parking

**Comment by fb86** [comment]
ok bon en test
