### ISSUE TITLE
Dans la sauvegarde dissocier en base les frais de stationnement et les frais de péage 

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#997]
Tout est dans le titre,

**Comment by fb86** [comment]
@fb86 penser à indiquer dans le MOP la date à laquelle nous pourrons requête sur le montant des frais de parking pris en charge

**Comment by jpic** [comment]
Quid des donnees legacy ? A revoir en atelier.

**Comment by fb86** [comment]
C quoi les données legacy




Télécharger Outlook pour Android







On Mon, Apr 22, 2019 at 7:52 PM +0200, "∞" <notifications@github.com> wrote:












Quid des donnees legacy ? A revoir en atelier.

**Comment by jpic** [comment]
Les données qui sont deja dans la base.

**Comment by fb86** [comment]
On va laisser une rubrique frais vp qui contient les données stationnement + péage avant la mise a jour puis uniquement les frais de stationnement lorsqu on aura mise en œuvre frais de stationnement. 




Télécharger Outlook pour Android







On Mon, Apr 22, 2019 at 8:07 PM +0200, "∞" <notifications@github.com> wrote:












Les données qui sont deja dans la base.

**Comment by jpic** [comment]
D'accord mais tu veux qu'on affiche plus du tout la somme pour les nouvelles demandes ?

**Comment by fb86** [comment]
Si bien sur. 




Télécharger Outlook pour Android







On Mon, Apr 22, 2019 at 9:12 PM +0200, "∞" <notifications@github.com> wrote:












D'accord mais tu veux qu'on affiche plus du tout la somme pour les nouvelles demandes ?

**Comment by jpic** [comment]
C'est toujours trop confus pour produire un code de qualité.

**Comment by jpic** [comment]
Je comprends toujours pas puisque le champs actuelement en DB est stationnement + peage  est-ce-que ca veut dire qu'on doit garder ce champs et en ajouter deux autres, un pour le peage et l'autre pour le stationnement ?

Desoler mais c'est la confusion complete dans ma tete la.

**Comment by jpic** [comment]
Pour tester la bonne retranscription des demandes de l'ancienne version, partir sur les documents anonymisés qui avaient ete importés de la prod en staging a l'epoque du developpement des stats, comparer le rendu de la page de detail de demande avec la demande correspondante au meme numero en prod.
Egalement tester le bon support des demandes nouvellement crées.

**Comment by fb86** [comment]
peux tu nous préciser de quels "   documents anonymisés qui avaient ete importés de la prod en staging a l'epoque du developpement des stats" parles tu ?

la demande initiale porté sur l'ajout de variables dans la base de données. l 'assuré saisie ces frais de stationnement ainsi que ces frais de péage. Aujourd'hui nous ne conservons en base que la somme des deux (montant total des frais de VP).

l'issue est terminée lorsque la donnée "frais de stationnement" est conservé dans la base. A terme, nous devrions trouver dans la base :
- les données " montant total des frais de VP), données actuelles correspondants au frais de stationnement saisie + frais de péage,
- les données "frais de stationnement" (reflet de ce qui est saisie par l'assuré). Données uniquement disponible à compter de la date de la mise en production.

L'issue n'implique aucune modification d'affichage sur le back office.

**Comment by fb86** [comment]
L'impact étant sur la base , merci de nous préciser comment avoir accès  à l'équivalent de requêtes sql explore en staging ou à defaut de nous confirmer que les demandes réalisés remontes correctement

**Comment by fb86** [comment]
j'ai voulu tester avec sql explorer. 

ma requête remonte à vide mais le pb est peut être plus entre l'écran et le clavier que sur le code.

**Comment by jpic** [comment]
En fait tout marche pour moi avec la requette suivante:

select expensevp_parking, expensevp_toll from mrsrequest_mrsrequest where expensevp_parking is not null;

https://staging.mrs.beta.gouv.fr/explorer/3/

**Comment by fb86** [comment]
test OK après quelques semaines de mise en oeuvre. @jpic peux tu juste indiqué la date de la mise en prod ?
