### ISSUE TITLE
Refonte architecture page demande BO

### ISSUE THREAD

**Issue by fb86** [betagouv/mrs#999]
Refonte de la page de détails de la demande en Back office.
![BO detail demande](https://user-images.githubusercontent.com/34480111/56223359-df907980-606d-11e9-9535-2b38befc1119.GIF)
 A partir du modèle ci dessous, les modifications suivantes
- [x] réduire les marges sur les cotés
- [x] déplacer l'encadrer ATP au dessus de l'encadrer VP,
- [ ] transformer le bouton radio en barre de menu en bas de page reprenant les  différentes commandes

![nouveau radio](https://user-images.githubusercontent.com/34480111/56224248-94776600-606f-11e9-9d99-ab555cf070f7.GIF)

le bouton valider correspond à la commande "en cours de liquidation" lorsque la demande est en statut soumis

**Comment by notmoebius** [comment]
On ne fait pas le bouton en menu.
